/**
 * Tests RealiseImportService (Lot 5.1) via pg-mem.
 *
 * Couvre :
 *  - Parsing CSV (cas nominal)
 *  - Validation : code inconnu, mois mal formé
 *  - Upsert : création + mise à jour ligne IMPORTE existante
 *  - Upsert : ligne VALIDE existante → ignorée
 *  - Périmètre : ligne CR hors périmètre → ignorée avec raison
 *  - Rapport : compteurs corrects
 *  - Audit IMPORTER_REALISE généré
 */
import ExcelJS from 'exceljs';
import { DataType, IMemoryDb, newDb } from 'pg-mem';
import { DataSource } from 'typeorm';

import { AuditLog } from '../../audit/entities/audit-log.entity';
import { AuditService } from '../../audit/audit.service';
import { PerimetreService } from '../../budget/services/perimetre.service';
import { DimCentreResponsabilite } from '../../referentiels/centre-responsabilite/entities/dim-centre-responsabilite.entity';
import { DimCompte } from '../../referentiels/compte/entities/dim-compte.entity';
import { DimDevise } from '../../referentiels/devise/entities/dim-devise.entity';
import { DimLigneMetier } from '../../referentiels/ligne-metier/entities/dim-ligne-metier.entity';
import { DimStructure } from '../../referentiels/structure/entities/dim-structure.entity';
import { DimTemps } from '../../referentiels/temps/entities/dim-temps.entity';
import { Permission } from '../../roles/entities/permission.entity';
import { Role } from '../../roles/entities/role.entity';
import { RolePermission } from '../../roles/entities/role-permission.entity';
import { User } from '../../users/entities/user.entity';
import { UserPerimetre } from '../../users/entities/user-perimetre.entity';
import { UserRole } from '../../users/entities/user-role.entity';
import { FaitRealise } from '../entities/fait-realise.entity';
import { RealiseImportService } from './realise-import.service';

function buildMemDb(): IMemoryDb {
  const db = newDb({ autoCreateForeignKeyIndices: true });
  db.public.registerFunction({
    name: 'current_database',
    args: [],
    returns: DataType.text,
    implementation: () => 'test',
  });
  db.public.registerFunction({
    name: 'version',
    args: [],
    returns: DataType.text,
    implementation: () => 'PG 15',
  });
  return db;
}

async function createDataSource(): Promise<DataSource> {
  const db = buildMemDb();
  const ds = db.adapters.createTypeormDataSource({
    type: 'postgres',
    entities: [
      FaitRealise,
      AuditLog,
      User,
      UserRole,
      UserPerimetre,
      Role,
      Permission,
      RolePermission,
      DimCentreResponsabilite,
      DimCompte,
      DimLigneMetier,
      DimDevise,
      DimTemps,
      DimStructure,
    ],
    synchronize: true,
  }) as DataSource;
  await ds.initialize();
  // Lot 8.5.G — la query EXISTS sur fait_budget exige juste les 5 fk
  // (centre/compte/ligne_metier/devise/temps). On crée une table
  // minimale pour pg-mem sans tirer FaitBudget complet (qui aurait
  // forcé l'import + synchronize d'un module supplémentaire).
  await ds.query(`
    CREATE TABLE fait_budget (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      fk_centre bigint NOT NULL,
      fk_compte bigint NOT NULL,
      fk_ligne_metier bigint NOT NULL,
      fk_devise bigint NOT NULL,
      fk_temps bigint NOT NULL
    )
  `);
  return ds;
}

interface SeedRefs {
  adminId: string;
  saisisseurId: string;
  cr1Code: string;
  cr1Id: string;
  compteCode: string;
  ligneMetierCode: string;
  deviseCode: string;
}

async function seed(ds: DataSource): Promise<SeedRefs> {
  await ds.query(
    `INSERT INTO "user" (email, mot_de_passe_hash, nom, prenom, est_actif)
     VALUES ('admin@m.io','h','A','D',true), ('sai@m.io','h','S','I',true)`,
  );
  const users = (await ds.query(`SELECT id, email FROM "user"`)) as Array<{
    id: string;
    email: string;
  }>;
  const adminId = String(users.find((u) => u.email === 'admin@m.io')!.id);
  const saiId = String(users.find((u) => u.email === 'sai@m.io')!.id);

  await ds.query(
    `INSERT INTO ref_role (code_role, libelle, est_actif, utilisateur_creation)
     VALUES ('ADMIN','Admin',true,'system'), ('LECTEUR','Lecteur',true,'system')`,
  );
  const roles = (await ds.query(
    `SELECT id, code_role FROM ref_role`,
  )) as Array<{ id: string; code_role: string }>;
  const adminRoleId = String(roles.find((r) => r.code_role === 'ADMIN')!.id);
  const lecteurRoleId = String(
    roles.find((r) => r.code_role === 'LECTEUR')!.id,
  );

  await ds.query(
    `INSERT INTO bridge_user_role (fk_user, fk_role, perimetre_type, est_actif, utilisateur_creation)
     VALUES ($1::bigint, $2::bigint, 'global', true, 'system'),
            ($3::bigint, $4::bigint, 'global', true, 'system')`,
    [adminId, adminRoleId, saiId, lecteurRoleId],
  );

  // Référentiels
  await ds.query(
    `INSERT INTO dim_structure
       (code_structure, libelle, type_structure, niveau_hierarchique,
        date_debut_validite, version_courante, est_actif, utilisateur_creation)
     VALUES ('S1','Struct1','filiale',1,'2026-01-01',true,true,'system')`,
  );
  const struct = (await ds.query(`SELECT id FROM dim_structure`)) as Array<{
    id: string;
  }>;
  await ds.query(
    `INSERT INTO dim_centre_responsabilite
       (code_cr, libelle, type_cr, fk_structure,
        date_debut_validite, version_courante, est_actif, utilisateur_creation)
     VALUES ('CR_A','CR A','profit_center',$1::bigint,'2026-01-01',true,true,'system'),
            ('CR_B','CR B','profit_center',$1::bigint,'2026-01-01',true,true,'system')`,
    [struct[0]!.id],
  );
  const crs = (await ds.query(
    `SELECT id, code_cr FROM dim_centre_responsabilite ORDER BY id`,
  )) as Array<{ id: string; code_cr: string }>;
  const cr1Id = String(crs[0]!.id);

  await ds.query(
    `INSERT INTO dim_compte
       (code_compte, libelle, classe, niveau, est_compte_collectif,
        est_porteur_interets, date_debut_validite, version_courante,
        est_actif, utilisateur_creation)
     VALUES ('611100','Salaires','6',4,false,false,'2026-01-01',true,true,'system')`,
  );
  await ds.query(
    `INSERT INTO dim_ligne_metier
       (code_ligne_metier, libelle, niveau, date_debut_validite,
        version_courante, est_actif, utilisateur_creation)
     VALUES ('RETAIL','Retail',1,'2026-01-01',true,true,'system')`,
  );
  await ds.query(
    `INSERT INTO dim_devise
       (code_iso, libelle, symbole, nb_decimales, est_devise_pivot,
        est_active, utilisateur_creation)
     VALUES ('XOF','Franc CFA','F CFA',0,true,true,'system')`,
  );
  await ds.query(
    `INSERT INTO dim_temps
       (date, annee, trimestre, mois, jour, jour_ouvre, est_fin_de_mois,
        est_fin_de_trimestre, est_fin_d_annee, exercice_fiscal, libelle_mois)
     VALUES ('2027-01-01',2027,1,1,1,true,false,false,false,2027,'Janvier')`,
  );

  // Saisisseur a user_perimetres CR_A uniquement
  await ds.query(
    `INSERT INTO user_perimetres (fk_user, cible_type, cible_id, origine, date_debut, actif, utilisateur_creation)
     VALUES ($1::bigint, 'CR', $2::bigint, 'AFFECTATION', '2026-01-01', true, 'system')`,
    [saiId, cr1Id],
  );

  return {
    adminId,
    saisisseurId: saiId,
    cr1Code: 'CR_A',
    cr1Id,
    compteCode: '611100',
    ligneMetierCode: 'RETAIL',
    deviseCode: 'XOF',
  };
}

function csv(lignes: string[]): {
  buffer: Buffer;
  originalname: string;
  mimetype: string;
  size: number;
} {
  const text = lignes.join('\n');
  const buffer = Buffer.from(text, 'utf-8');
  return {
    buffer,
    originalname: 'realise.csv',
    mimetype: 'text/csv',
    size: buffer.length,
  };
}

const HEADER = 'code_cr,code_compte,code_ligne_metier,mois,code_devise,montant';

describe('RealiseImportService', () => {
  let ds: DataSource;
  let svc: RealiseImportService;
  let auditSvc: AuditService;
  let perimSvc: PerimetreService;
  let refs: SeedRefs;

  beforeAll(async () => {
    ds = await createDataSource();
  });
  afterAll(async () => {
    await ds.destroy();
  });

  beforeEach(async () => {
    await ds.query('DELETE FROM fait_realise');
    await ds.query('DELETE FROM fait_budget');
    await ds.query('DELETE FROM audit_log');
    await ds.query('DELETE FROM bridge_user_role');
    await ds.query('DELETE FROM ref_role');
    await ds.query('DELETE FROM user_perimetres');
    await ds.query('DELETE FROM dim_centre_responsabilite');
    await ds.query('DELETE FROM dim_structure');
    await ds.query('DELETE FROM dim_temps');
    await ds.query('DELETE FROM dim_compte');
    await ds.query('DELETE FROM dim_ligne_metier');
    await ds.query('DELETE FROM dim_devise');
    await ds.query('DELETE FROM "user"');
    refs = await seed(ds);
    auditSvc = new AuditService(ds.getRepository(AuditLog));
    perimSvc = new PerimetreService(
      ds.getRepository(UserRole),
      ds.getRepository(UserPerimetre),
    );
    svc = new RealiseImportService(ds, perimSvc, auditSvc);
  });

  function admin() {
    return { userId: refs.adminId, email: 'admin@m.io' };
  }
  function saisisseur() {
    return { userId: refs.saisisseurId, email: 'sai@m.io' };
  }

  it('import nominal 1 ligne valide → INSERT + statut IMPORTE + source IMPORT', async () => {
    const file = csv([
      HEADER,
      `${refs.cr1Code},${refs.compteCode},${refs.ligneMetierCode},2027-01,${refs.deviseCode},1500000`,
    ]);
    const r = await svc.importFichier(file, admin());
    expect(r.nbLignesTraitees).toBe(1);
    expect(r.nbLignesCreees).toBe(1);
    expect(r.nbLignesMisesAJour).toBe(0);
    expect(r.nbErreurs).toBe(0);
    const persist = await ds.getRepository(FaitRealise).find();
    expect(persist).toHaveLength(1);
    expect(persist[0]!.statut).toBe('IMPORTE');
    expect(persist[0]!.source).toBe('IMPORT');
    expect(Number(persist[0]!.montant)).toBe(1500000);
  });

  it('code CR inconnu → erreur dans le rapport', async () => {
    const file = csv([
      HEADER,
      `CR_INCONNU,${refs.compteCode},${refs.ligneMetierCode},2027-01,${refs.deviseCode},1000000`,
    ]);
    const r = await svc.importFichier(file, admin());
    expect(r.nbErreurs).toBe(1);
    expect(r.erreurs[0]!.message).toMatch(/CR_INCONNU/);
    expect(r.nbLignesCreees).toBe(0);
  });

  it('mois mal formé → erreur de validation', async () => {
    const file = csv([
      HEADER,
      `${refs.cr1Code},${refs.compteCode},${refs.ligneMetierCode},2027,${refs.deviseCode},1000000`,
    ]);
    const r = await svc.importFichier(file, admin());
    expect(r.nbErreurs).toBe(1);
    expect(r.erreurs[0]!.message).toMatch(/Format YYYY-MM/);
  });

  it('upsert : ligne IMPORTE existante mise à jour', async () => {
    const file1 = csv([
      HEADER,
      `${refs.cr1Code},${refs.compteCode},${refs.ligneMetierCode},2027-01,${refs.deviseCode},1000000`,
    ]);
    await svc.importFichier(file1, admin());
    // 2e import : même clé, montant différent
    const file2 = csv([
      HEADER,
      `${refs.cr1Code},${refs.compteCode},${refs.ligneMetierCode},2027-01,${refs.deviseCode},2500000`,
    ]);
    const r = await svc.importFichier(file2, admin());
    expect(r.nbLignesCreees).toBe(0);
    expect(r.nbLignesMisesAJour).toBe(1);
    const persist = await ds.getRepository(FaitRealise).find();
    expect(persist).toHaveLength(1);
    expect(Number(persist[0]!.montant)).toBe(2500000);
  });

  it('upsert : ligne VALIDE existante → ignorée avec raison', async () => {
    // Première création + validation manuelle SQL (pour éviter la dépendance
    // au RealiseService dans ce spec dédié à l'import).
    const file1 = csv([
      HEADER,
      `${refs.cr1Code},${refs.compteCode},${refs.ligneMetierCode},2027-01,${refs.deviseCode},1000000`,
    ]);
    await svc.importFichier(file1, admin());
    await ds.query(
      `UPDATE fait_realise SET statut='VALIDE', valide_le=NOW(), fk_valide_par=$1::bigint`,
      [refs.adminId],
    );
    const file2 = csv([
      HEADER,
      `${refs.cr1Code},${refs.compteCode},${refs.ligneMetierCode},2027-01,${refs.deviseCode},9999999`,
    ]);
    const r = await svc.importFichier(file2, admin());
    expect(r.nbLignesCreees).toBe(0);
    expect(r.nbLignesMisesAJour).toBe(0);
    expect(r.nbLignesIgnorees).toBe(1);
    expect(r.lignesIgnorees[0]!.raison).toMatch(/déjà validée/);
    const persist = await ds.getRepository(FaitRealise).findOne({ where: {} });
    expect(Number(persist!.montant)).toBe(1000000); // pas modifié
  });

  it('périmètre : ligne CR hors user_perimetres ignorée avec raison', async () => {
    const file = csv([
      HEADER,
      `CR_B,${refs.compteCode},${refs.ligneMetierCode},2027-01,${refs.deviseCode},5000000`,
    ]);
    const r = await svc.importFichier(file, saisisseur());
    expect(r.nbLignesCreees).toBe(0);
    expect(r.nbLignesIgnorees).toBe(1);
    expect(r.lignesIgnorees[0]!.raison).toMatch(/hors de votre périmètre/);
  });

  it('rapport contient les compteurs corrects sur batch mixte', async () => {
    // 1 OK, 1 erreur (CR inconnu), 1 ignorée (déjà validée)
    await svc.importFichier(
      csv([
        HEADER,
        `${refs.cr1Code},${refs.compteCode},${refs.ligneMetierCode},2027-01,${refs.deviseCode},111`,
      ]),
      admin(),
    );
    await ds.query(
      `UPDATE fait_realise SET statut='VALIDE', valide_le=NOW(), fk_valide_par=$1::bigint`,
      [refs.adminId],
    );
    const file = csv([
      HEADER,
      `${refs.cr1Code},${refs.compteCode},${refs.ligneMetierCode},2027-01,${refs.deviseCode},222`,
      `CR_INCONNU,${refs.compteCode},${refs.ligneMetierCode},2027-01,${refs.deviseCode},333`,
    ]);
    const r = await svc.importFichier(file, admin());
    expect(r.nbLignesTraitees).toBe(2);
    expect(r.nbErreurs).toBe(1);
    expect(r.nbLignesIgnorees).toBe(1);
    expect(r.nbLignesCreees + r.nbLignesMisesAJour).toBe(0);
  });

  it('audit IMPORTER_REALISE généré (1 par fichier)', async () => {
    const file = csv([
      HEADER,
      `${refs.cr1Code},${refs.compteCode},${refs.ligneMetierCode},2027-01,${refs.deviseCode},111`,
    ]);
    await svc.importFichier(file, admin());
    const audits = (await ds.query(
      `SELECT 1 FROM audit_log WHERE type_action='IMPORTER_REALISE'`,
    )) as unknown[];
    expect(audits).toHaveLength(1);
  });

  it('header invalide → BadRequestException', async () => {
    const file = csv([
      'col1,col2,col3',
      `${refs.cr1Code},${refs.compteCode},foo`,
    ]);
    await expect(svc.importFichier(file, admin())).rejects.toThrow(
      /Header invalide/,
    );
  });

  it('XLSX cellule formule → extraction valeur calculée (régression Lot 6.6.B-8.3)', async () => {
    // ExcelJS retourne { formula, result } pour les cellules avec formule.
    // Avant le fix : String({formula, result}).trim() donnait '[object Object]'
    // → Zod rejetait la ligne avec erreur incompréhensible.
    // Après fix : extraction de .result.
    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet('Realise');
    ws.addRow(HEADER.split(','));
    const dataRow = ws.addRow([
      refs.cr1Code,
      refs.compteCode,
      refs.ligneMetierCode,
      '2027-01-01',
      refs.deviseCode,
      '',
    ]);
    // Cellule montant (6ème colonne) = formule avec result précalculé.
    dataRow.getCell(6).value = { formula: '750000+750000', result: 1500000 };
    const buf = (await wb.xlsx.writeBuffer()) as ArrayBuffer;
    const buffer = Buffer.from(new Uint8Array(buf));
    const file = {
      buffer,
      originalname: 'realise-formule.xlsx',
      mimetype:
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      size: buffer.length,
    };

    const r = await svc.importFichier(file, admin());
    expect(r.nbLignesCreees).toBe(1);
    expect(r.nbErreurs).toBe(0);
  });

  // ─── Lot 8.5.G — warning « ligne sans budget correspondant » ─────
  it('Lot 8.5.G — ligne sans budget correspondant → warning + ligne créée quand même', async () => {
    // fait_budget vide (DELETE FROM fait_budget en beforeEach), donc
    // EXISTS retourne 0 → la ligne est flaggée warning mais reste créée.
    const file = csv([
      HEADER,
      `${refs.cr1Code},${refs.compteCode},${refs.ligneMetierCode},2027-01,${refs.deviseCode},1500000`,
    ]);
    const r = await svc.importFichier(file, admin());
    expect(r.nbLignesCreees).toBe(1); // ligne créée malgré le warning
    expect(r.nbErreurs).toBe(0);
    expect(r.nbLignesSansBudget).toBe(1);
    expect(r.lignesSansBudget).toHaveLength(1);
    expect(r.lignesSansBudget[0]!.ligne).toBe(2); // 1 = header, 2 = data
    expect(r.lignesSansBudget[0]!.raison).toMatch(/absente de fait_budget/);
    expect(r.lignesSansBudget[0]!.raison).toContain(refs.compteCode);
    expect(r.lignesSansBudget[0]!.raison).toContain(refs.cr1Code);
    // Persistance vérifiée : la ligne EST bien dans fait_realise.
    const persist = await ds.getRepository(FaitRealise).find();
    expect(persist).toHaveLength(1);
  });

  it('Lot 8.5.G — batch mixte (1 avec budget + 1 sans) → nbLignesSansBudget=1, les 2 créées', async () => {
    // Pré-insérer un fait_budget qui matche EXACTEMENT la 1ère ligne
    // CSV (mêmes 5 fk : centre, compte, ligne_metier, devise, temps).
    const fkCompte = (
      await ds.query<Array<{ id: string }>>(
        `SELECT id FROM dim_compte WHERE code_compte = $1 LIMIT 1`,
        [refs.compteCode],
      )
    )[0]!.id;
    const fkLm = (
      await ds.query<Array<{ id: string }>>(
        `SELECT id FROM dim_ligne_metier WHERE code_ligne_metier = $1 LIMIT 1`,
        [refs.ligneMetierCode],
      )
    )[0]!.id;
    const fkDevise = (
      await ds.query<Array<{ id: string }>>(
        `SELECT id FROM dim_devise WHERE code_iso = $1 LIMIT 1`,
        [refs.deviseCode],
      )
    )[0]!.id;
    const fkTemps = (
      await ds.query<Array<{ id: string }>>(
        `SELECT id FROM dim_temps WHERE date = '2027-01-01' AND jour = 1 LIMIT 1`,
      )
    )[0]!.id;
    await ds.query(
      `INSERT INTO fait_budget (fk_centre, fk_compte, fk_ligne_metier, fk_devise, fk_temps)
       VALUES ($1::bigint, $2::bigint, $3::bigint, $4::bigint, $5::bigint)`,
      [refs.cr1Id, fkCompte, fkLm, fkDevise, fkTemps],
    );

    // 2 lignes CSV : (1) CR_A → matche le fait_budget pré-inséré
    //                (2) CR_B → pas de fait_budget pour ce centre.
    const file = csv([
      HEADER,
      `${refs.cr1Code},${refs.compteCode},${refs.ligneMetierCode},2027-01,${refs.deviseCode},1000000`,
      `CR_B,${refs.compteCode},${refs.ligneMetierCode},2027-01,${refs.deviseCode},2000000`,
    ]);
    const r = await svc.importFichier(file, admin());
    expect(r.nbLignesTraitees).toBe(2);
    expect(r.nbLignesCreees).toBe(2); // les 2 créées (warning ≠ erreur)
    expect(r.nbErreurs).toBe(0);
    expect(r.nbLignesSansBudget).toBe(1);
    expect(r.lignesSansBudget[0]!.ligne).toBe(3); // 2e ligne data = csv ligne 3
    expect(r.lignesSansBudget[0]!.raison).toContain('CR_B');
  });
});
