import type { QueryRunner } from 'typeorm';

/**
 * Helpers DRY pour les 13 migrations ref_*.
 * Toutes les tables ont exactement le même schéma — cf. Lot 2.5-bis-A.
 */

export interface RefSecondaireSeed {
  code: string;
  libelle: string;
  description?: string | null;
  ordre: number;
  estSysteme: boolean;
}

export async function createRefSecondaireTable(
  q: QueryRunner,
  tableName: string,
): Promise<void> {
  await q.query(`
    CREATE TABLE "${tableName}" (
      "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      "code" varchar(50) NOT NULL,
      "libelle" varchar(200) NOT NULL,
      "description" text NULL,
      "ordre" int NOT NULL DEFAULT 0,
      "est_actif" boolean NOT NULL DEFAULT true,
      "est_systeme" boolean NOT NULL DEFAULT false,
      "date_creation" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "utilisateur_creation" varchar(255) NOT NULL DEFAULT 'system',
      "date_modification" timestamp NULL,
      "utilisateur_modification" varchar(255) NULL,
      CONSTRAINT "PK_${tableName}" PRIMARY KEY ("id")
    )
  `);
  await q.query(
    `ALTER TABLE "${tableName}" ALTER COLUMN "id" SET GENERATED ALWAYS`,
  );
  await q.query(
    `CREATE UNIQUE INDEX "uq_${tableName}_code" ON "${tableName}" ("code")`,
  );
  await q.query(
    `CREATE INDEX "ix_${tableName}_actif_ordre" ON "${tableName}" ("est_actif", "ordre")`,
  );
  await q.query(
    `CREATE INDEX "ix_${tableName}_est_systeme" ON "${tableName}" ("est_systeme")`,
  );
}

export async function dropRefSecondaireTable(
  q: QueryRunner,
  tableName: string,
): Promise<void> {
  await q.query(
    `DROP INDEX IF EXISTS "public"."ix_${tableName}_est_systeme"`,
  );
  await q.query(
    `DROP INDEX IF EXISTS "public"."ix_${tableName}_actif_ordre"`,
  );
  await q.query(
    `DROP INDEX IF EXISTS "public"."uq_${tableName}_code"`,
  );
  await q.query(`DROP TABLE "${tableName}"`);
}

export async function seedRefSecondaire(
  q: QueryRunner,
  tableName: string,
  rows: RefSecondaireSeed[],
): Promise<void> {
  for (const r of rows) {
    await q.query(
      `INSERT INTO "${tableName}"
        ("code", "libelle", "description", "ordre", "est_systeme", "utilisateur_creation")
       VALUES ($1, $2, $3, $4, $5, 'system')`,
      [r.code, r.libelle, r.description ?? null, r.ordre, r.estSysteme],
    );
  }
}
