/**
 * Tests unitaires VersionWorkflowService (Lot 3.5) via pg-mem.
 *
 * Cycle linéaire couvert :
 *   ouvert → soumis → valide → gele (publié, IMMUABLE)
 *                ↓
 *           rejeter → ouvert (avec commentaire de rejet conservé)
 *
 * Permissions hors scope unitaire (vérifiées par PermissionsGuard
 * côté e2e). On se concentre sur la cohérence métier des transitions
 * et les écritures `audit_log` (4 type_action nouveaux).
 *
 * La table `fait_budget` est créée en pg-mem avec une définition
 * minimale (id + fk_version) — VersionWorkflowService.soumettre la
 * requête en raw SQL pour vérifier qu'une version Brouillon n'est
 * pas vide, sans avoir besoin du chargement complet de l'entité.
 */
import {
  ConflictException,
  NotFoundException,
  UnprocessableEntityException,
} from '@nestjs/common';
import { DataType, IMemoryDb, newDb } from 'pg-mem';
import { DataSource, Repository } from 'typeorm';

import { AuditLog } from '../../audit/entities/audit-log.entity';
import { AuditService } from '../../audit/audit.service';
import { PermissionsService } from '../../auth/permissions.service';
import { DimVersion } from './entities/dim-version.entity';
import { VersionWorkflowService } from './version-workflow.service';

function buildMemDb(): IMemoryDb {
  const db = newDb({ autoCreateForeignKeyIndices: true });
  db.public.registerFunction({
    name: 'current_database',
    args: [],
    returns: DataType.text,
    implementation: () => 'test',
  });
  db.public.registerFunction({
    name: 'version',
    args: [],
    returns: DataType.text,
    implementation: () => 'PostgreSQL 15 (pg-mem)',
  });
  return db;
}

async function createDataSource(): Promise<DataSource> {
  const db = buildMemDb();
  const ds: DataSource = db.adapters.createTypeormDataSource({
    type: 'postgres',
    entities: [DimVersion, AuditLog],
    synchronize: true,
  });
  await ds.initialize();

  // Table minimale fait_budget pour la requête de comptage de
  // VersionWorkflowService.soumettre. On ne charge pas l'entité
  // FaitBudget complète car ses ManyToOne requièrent toutes les dim.
  await ds.query(`
    CREATE TABLE fait_budget (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      fk_version bigint NOT NULL
    )
  `);
  return ds;
}

async function rawInsertVersion(
  ds: DataSource,
  attrs: {
    codeVersion: string;
    statut?: 'ouvert' | 'soumis' | 'valide' | 'gele';
  },
): Promise<string> {
  await ds.query(
    `INSERT INTO dim_version
       ("code_version","libelle","type_version","exercice_fiscal",
        "statut","utilisateur_creation")
     VALUES ($1,$2,'budget_initial',2026,$3,'system')`,
    [attrs.codeVersion, attrs.codeVersion, attrs.statut ?? 'ouvert'],
  );
  const rows = (await ds.query(
    `SELECT id FROM dim_version WHERE code_version = $1`,
    [attrs.codeVersion],
  )) as Array<{ id: string | number }>;
  return String(rows[0]!.id);
}

async function addLignes(
  ds: DataSource,
  versionId: string,
  count: number,
): Promise<void> {
  for (let i = 0; i < count; i++) {
    await ds.query(
      `INSERT INTO fait_budget ("fk_version") VALUES ($1)`,
      [versionId],
    );
  }
}

describe('VersionWorkflowService', () => {
  let dataSource: DataSource;
  let repo: Repository<DimVersion>;
  let auditService: AuditService;
  let service: VersionWorkflowService;

  // Lot 4.2-fix.A : userId requis pour le helper
  // PermissionsService.getDelegationContextPour. Mock global :
  // par défaut, NATIF (retour null) — les tests dédiés via délégation
  // surchargent ce mock localement.
  const preparateur = {
    userId: '101',
    email: 'preparateur@miznas.local',
  };
  const controleur = { userId: '102', email: 'controleur@miznas.local' };
  const directeur = { userId: '103', email: 'directeur@miznas.local' };
  let permissionsServiceMock: { getDelegationContextPour: jest.Mock };

  beforeAll(async () => {
    dataSource = await createDataSource();
    repo = dataSource.getRepository(DimVersion);
    auditService = new AuditService(dataSource.getRepository(AuditLog));
    permissionsServiceMock = {
      getDelegationContextPour: jest.fn().mockResolvedValue(null),
    };
    service = new VersionWorkflowService(
      repo,
      dataSource,
      auditService,
      permissionsServiceMock as unknown as PermissionsService,
    );
  });

  afterAll(async () => {
    await dataSource.destroy();
  });

  beforeEach(async () => {
    await dataSource.query('DELETE FROM audit_log');
    await dataSource.query('DELETE FROM fait_budget');
    await dataSource.query('DELETE FROM dim_version');
  });

  // ─── Soumettre ────────────────────────────────────────────────────

  describe('soumettre', () => {
    it('passe ouvert → soumis et trace utilisateur + date', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'BI_2026',
      });
      await addLignes(dataSource, id, 3);

      const before = Date.now();
      const res = await service.soumettre(
        id,
        { commentaire: 'Prêt pour validation' },
        preparateur,
      );
      const after = Date.now();

      expect(res.statut).toBe('soumis');
      expect(res.commentaireSoumission).toBe('Prêt pour validation');
      expect(res.utilisateurSoumission).toBe(preparateur.email);
      expect(res.dateSoumission).not.toBeNull();
      const ts = new Date(res.dateSoumission as unknown as string).getTime();
      expect(ts).toBeGreaterThanOrEqual(before - 1);
      expect(ts).toBeLessThanOrEqual(after + 1);
    });

    it('refuse 422 si version vide (aucune ligne fait_budget)', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'EMPTY_2026',
      });
      await expect(
        service.soumettre(id, {}, preparateur),
      ).rejects.toThrow(UnprocessableEntityException);
    });

    it('refuse 409 si statut différent de ouvert', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'BI_2026',
        statut: 'soumis',
      });
      await addLignes(dataSource, id, 1);
      await expect(
        service.soumettre(id, {}, preparateur),
      ).rejects.toThrow(ConflictException);
    });

    it('lève 404 si version introuvable', async () => {
      await expect(
        service.soumettre('999999', {}, preparateur),
      ).rejects.toThrow(NotFoundException);
    });

    it('écrit un audit SOUMETTRE_BUDGET avec payloadApres complet', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'BI_2026',
      });
      await addLignes(dataSource, id, 5);
      await service.soumettre(
        id,
        { commentaire: 'OK' },
        preparateur,
      );

      const audits = (await dataSource.query(
        `SELECT type_action, statut, utilisateur, id_cible,
                payload_apres, commentaire
           FROM audit_log
          WHERE type_action = 'SOUMETTRE_BUDGET'`,
      )) as Array<{
        type_action: string;
        statut: string;
        utilisateur: string;
        id_cible: string;
        payload_apres: {
          codeVersion: string;
          statutAvant: string;
          statutApres: string;
          commentaire: string | null;
        };
        commentaire: string;
      }>;
      expect(audits).toHaveLength(1);
      expect(audits[0]!.statut).toBe('success');
      expect(audits[0]!.utilisateur).toBe(preparateur.email);
      expect(audits[0]!.id_cible).toBe(String(id));
      expect(audits[0]!.payload_apres.statutAvant).toBe('ouvert');
      expect(audits[0]!.payload_apres.statutApres).toBe('soumis');
      expect(audits[0]!.payload_apres.codeVersion).toBe('BI_2026');
      expect(audits[0]!.commentaire).toMatch(/5 ligne/);
    });
  });

  // ─── Valider ──────────────────────────────────────────────────────

  describe('valider', () => {
    it('passe soumis → valide et trace utilisateur', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'BI_2026',
        statut: 'soumis',
      });
      const res = await service.valider(
        id,
        { commentaire: 'Conforme' },
        controleur,
      );
      expect(res.statut).toBe('valide');
      expect(res.commentaireValidation).toBe('Conforme');
      expect(res.utilisateurValidation).toBe(controleur.email);
      expect(res.dateValidation).not.toBeNull();
    });

    it('refuse 409 si statut différent de soumis', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'BI_2026',
        statut: 'ouvert',
      });
      await expect(
        service.valider(id, {}, controleur),
      ).rejects.toThrow(ConflictException);
    });

    it('écrit un audit VALIDER_BUDGET', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'BI_2026',
        statut: 'soumis',
      });
      await service.valider(id, {}, controleur);
      const audits = (await dataSource.query(
        `SELECT statut, payload_apres FROM audit_log
          WHERE type_action='VALIDER_BUDGET'`,
      )) as Array<{
        statut: string;
        payload_apres: { statutAvant: string; statutApres: string };
      }>;
      expect(audits).toHaveLength(1);
      expect(audits[0]!.statut).toBe('success');
      expect(audits[0]!.payload_apres.statutAvant).toBe('soumis');
      expect(audits[0]!.payload_apres.statutApres).toBe('valide');
    });
  });

  // ─── Rejeter ──────────────────────────────────────────────────────

  describe('rejeter', () => {
    it('passe soumis → ouvert et conserve le commentaire de rejet', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'BI_2026',
        statut: 'soumis',
      });
      const res = await service.rejeter(
        id,
        { commentaire: 'Frais de personnel sous-estimés.' },
        controleur,
      );
      expect(res.statut).toBe('ouvert');
      expect(res.commentaireRejet).toBe(
        'Frais de personnel sous-estimés.',
      );
      expect(res.utilisateurRejet).toBe(controleur.email);
      expect(res.dateRejet).not.toBeNull();
    });

    it('réinitialise les champs de soumission (re-soumission propre)', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'BI_2026',
      });
      await addLignes(dataSource, id, 1);
      await service.soumettre(
        id,
        { commentaire: 'Première soumission' },
        preparateur,
      );
      await service.rejeter(
        id,
        { commentaire: 'À revoir' },
        controleur,
      );

      const v = (await dataSource.query(
        `SELECT commentaire_soumission, date_soumission, utilisateur_soumission
           FROM dim_version WHERE id = $1`,
        [id],
      )) as Array<{
        commentaire_soumission: string | null;
        date_soumission: Date | null;
        utilisateur_soumission: string | null;
      }>;
      expect(v[0]!.commentaire_soumission).toBeNull();
      expect(v[0]!.date_soumission).toBeNull();
      expect(v[0]!.utilisateur_soumission).toBeNull();
    });

    it('refuse 409 si statut différent de soumis', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'BI_2026',
        statut: 'valide',
      });
      await expect(
        service.rejeter(id, { commentaire: 'X' }, controleur),
      ).rejects.toThrow(ConflictException);
    });

    it('écrit un audit REJETER_BUDGET avec commentaire', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'BI_2026',
        statut: 'soumis',
      });
      await service.rejeter(
        id,
        { commentaire: 'Provisions sous-évaluées' },
        controleur,
      );
      const audits = (await dataSource.query(
        `SELECT statut, payload_apres, commentaire
           FROM audit_log WHERE type_action='REJETER_BUDGET'`,
      )) as Array<{
        statut: string;
        payload_apres: { commentaireRejet: string };
        commentaire: string;
      }>;
      expect(audits).toHaveLength(1);
      expect(audits[0]!.payload_apres.commentaireRejet).toBe(
        'Provisions sous-évaluées',
      );
      expect(audits[0]!.commentaire).toMatch(/Provisions sous-évaluées/);
    });

    it('cycle rejet puis re-soumission : champs validation/rejet remis à zéro', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'BI_2026',
      });
      await addLignes(dataSource, id, 1);
      await service.soumettre(id, {}, preparateur);
      await service.rejeter(
        id,
        { commentaire: 'À revoir' },
        controleur,
      );
      // Re-soumission après correction.
      await service.soumettre(
        id,
        { commentaire: 'Corrections faites' },
        preparateur,
      );
      const v = (await dataSource.query(
        `SELECT statut, commentaire_validation, date_validation,
                utilisateur_validation, commentaire_rejet, date_rejet,
                utilisateur_rejet, commentaire_soumission
           FROM dim_version WHERE id = $1`,
        [id],
      )) as Array<{
        statut: string;
        commentaire_validation: string | null;
        date_validation: Date | null;
        utilisateur_validation: string | null;
        commentaire_rejet: string | null;
        date_rejet: Date | null;
        utilisateur_rejet: string | null;
        commentaire_soumission: string;
      }>;
      expect(v[0]!.statut).toBe('soumis');
      expect(v[0]!.commentaire_validation).toBeNull();
      expect(v[0]!.date_validation).toBeNull();
      expect(v[0]!.utilisateur_validation).toBeNull();
      expect(v[0]!.commentaire_rejet).toBeNull();
      expect(v[0]!.date_rejet).toBeNull();
      expect(v[0]!.utilisateur_rejet).toBeNull();
      expect(v[0]!.commentaire_soumission).toBe('Corrections faites');
    });
  });

  // ─── Publier ──────────────────────────────────────────────────────

  describe('publier', () => {
    it('passe valide → gele et pose dateGel/utilisateurGel', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'BI_2026',
        statut: 'valide',
      });
      const res = await service.publier(
        id,
        { commentaire: 'Publication officielle 2026' },
        directeur,
      );
      expect(res.statut).toBe('gele');
      expect(res.commentairePublication).toBe(
        'Publication officielle 2026',
      );
      expect(res.utilisateurGel).toBe(directeur.email);
      expect(res.dateGel).not.toBeNull();
    });

    it('refuse 409 si statut différent de valide', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'BI_2026',
        statut: 'soumis',
      });
      await expect(
        service.publier(id, {}, directeur),
      ).rejects.toThrow(ConflictException);
    });

    it('refuse 409 si version déjà gelée (immuabilité)', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'BI_2026',
        statut: 'gele',
      });
      await expect(
        service.publier(id, {}, directeur),
      ).rejects.toThrow(ConflictException);
    });

    it('écrit un audit PUBLIER_BUDGET (commentaire BCEAO)', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'BI_2026',
        statut: 'valide',
      });
      await service.publier(id, {}, directeur);
      const audits = (await dataSource.query(
        `SELECT statut, payload_apres, commentaire
           FROM audit_log WHERE type_action='PUBLIER_BUDGET'`,
      )) as Array<{
        statut: string;
        payload_apres: { statutApres: string };
        commentaire: string;
      }>;
      expect(audits).toHaveLength(1);
      expect(audits[0]!.payload_apres.statutApres).toBe('gele');
      expect(audits[0]!.commentaire).toMatch(/irréversible/);
    });
  });

  // ─── Cycle complet ────────────────────────────────────────────────

  describe('cycle complet', () => {
    it('ouvert → soumis → valide → gele : 3 audits successifs', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'BI_2026',
      });
      await addLignes(dataSource, id, 2);

      await service.soumettre(id, {}, preparateur);
      await service.valider(id, {}, controleur);
      const final = await service.publier(
        id,
        { commentaire: 'Officiel' },
        directeur,
      );
      expect(final.statut).toBe('gele');

      const audits = (await dataSource.query(
        `SELECT type_action FROM audit_log
          WHERE id_cible = $1
          ORDER BY id ASC`,
        [String(id)],
      )) as Array<{ type_action: string }>;
      expect(audits.map((a) => a.type_action)).toEqual([
        'SOUMETTRE_BUDGET',
        'VALIDER_BUDGET',
        'PUBLIER_BUDGET',
      ]);

      // L'utilisateur de chaque transition est tracé séparément.
      expect(final.utilisateurSoumission).toBe(preparateur.email);
      expect(final.utilisateurValidation).toBe(controleur.email);
      expect(final.utilisateurGel).toBe(directeur.email);
    });
  });

  // ─── Lot 4.2-fix.A : via_delegation_id dans le payload audit ─────

  describe('via_delegation_id (Lot 4.2-fix.A)', () => {
    function getPayloadApres(rows: Array<{ payload_apres: unknown }>): Record<string, unknown> {
      return rows[0]!.payload_apres as Record<string, unknown>;
    }

    async function getAuditPayload(
      versionId: string,
      typeAction: string,
    ): Promise<Record<string, unknown>> {
      const rows = (await dataSource.query(
        `SELECT payload_apres FROM audit_log
          WHERE id_cible = $1 AND type_action = $2
          ORDER BY id DESC LIMIT 1`,
        [String(versionId), typeAction],
      )) as Array<{ payload_apres: unknown }>;
      return getPayloadApres(rows);
    }

    afterEach(() => {
      // Reset au défaut NATIF (null) pour ne pas polluer les autres tests.
      permissionsServiceMock.getDelegationContextPour.mockResolvedValue(null);
    });

    it('SOUMETTRE_BUDGET via délégation : payload contient via_delegation_id', async () => {
      permissionsServiceMock.getDelegationContextPour.mockResolvedValue('77');
      const id = await rawInsertVersion(dataSource, { codeVersion: 'V1' });
      await addLignes(dataSource, id, 1);
      await service.soumettre(id, {}, preparateur);
      expect(
        permissionsServiceMock.getDelegationContextPour,
      ).toHaveBeenCalledWith('101', 'BUDGET.SOUMETTRE');
      const payload = await getAuditPayload(id, 'SOUMETTRE_BUDGET');
      expect(payload.via_delegation_id).toBe('77');
    });

    it('SOUMETTRE_BUDGET natif : payload SANS via_delegation_id', async () => {
      const id = await rawInsertVersion(dataSource, { codeVersion: 'V2' });
      await addLignes(dataSource, id, 1);
      await service.soumettre(id, {}, preparateur);
      const payload = await getAuditPayload(id, 'SOUMETTRE_BUDGET');
      expect('via_delegation_id' in payload).toBe(false);
    });

    it('VALIDER_BUDGET via délégation : payload contient via_delegation_id', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'V3',
        statut: 'soumis',
      });
      permissionsServiceMock.getDelegationContextPour.mockResolvedValue('88');
      await service.valider(id, {}, controleur);
      expect(
        permissionsServiceMock.getDelegationContextPour,
      ).toHaveBeenCalledWith('102', 'BUDGET.VALIDER');
      const payload = await getAuditPayload(id, 'VALIDER_BUDGET');
      expect(payload.via_delegation_id).toBe('88');
    });

    it('VALIDER_BUDGET natif : payload SANS via_delegation_id', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'V4',
        statut: 'soumis',
      });
      await service.valider(id, {}, controleur);
      const payload = await getAuditPayload(id, 'VALIDER_BUDGET');
      expect('via_delegation_id' in payload).toBe(false);
    });

    it('PUBLIER_BUDGET via délégation : payload contient via_delegation_id', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'V5',
        statut: 'valide',
      });
      permissionsServiceMock.getDelegationContextPour.mockResolvedValue('123');
      await service.publier(id, { commentaire: 'OK' }, directeur);
      expect(
        permissionsServiceMock.getDelegationContextPour,
      ).toHaveBeenCalledWith('103', 'BUDGET.PUBLIER');
      const payload = await getAuditPayload(id, 'PUBLIER_BUDGET');
      expect(payload.via_delegation_id).toBe('123');
    });

    it('PUBLIER_BUDGET natif : payload SANS via_delegation_id', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'V6',
        statut: 'valide',
      });
      await service.publier(id, { commentaire: 'OK' }, directeur);
      const payload = await getAuditPayload(id, 'PUBLIER_BUDGET');
      expect('via_delegation_id' in payload).toBe(false);
    });

    it('REJETER_BUDGET via délégation : payload contient via_delegation_id', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'V7',
        statut: 'soumis',
      });
      permissionsServiceMock.getDelegationContextPour.mockResolvedValue('456');
      await service.rejeter(id, { commentaire: 'Erreurs détectées' }, controleur);
      expect(
        permissionsServiceMock.getDelegationContextPour,
      ).toHaveBeenCalledWith('102', 'BUDGET.VALIDER');
      const payload = await getAuditPayload(id, 'REJETER_BUDGET');
      expect(payload.via_delegation_id).toBe('456');
    });

    it('REJETER_BUDGET natif : payload SANS via_delegation_id', async () => {
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'V8',
        statut: 'soumis',
      });
      await service.rejeter(id, { commentaire: 'NOK' }, controleur);
      const payload = await getAuditPayload(id, 'REJETER_BUDGET');
      expect('via_delegation_id' in payload).toBe(false);
    });

    it('cas mixte (helper retourne null = priorité NATIF) : pas de via_delegation_id', async () => {
      // Simule un user qui a la perm en NATIF ET DELEGATION : le helper
      // applique la priorité NATIF et retourne null (cf. spec
      // PermissionsService). On vérifie ici que workflow respecte cette
      // décision et n'écrit pas via_delegation_id.
      const id = await rawInsertVersion(dataSource, {
        codeVersion: 'V9',
        statut: 'soumis',
      });
      permissionsServiceMock.getDelegationContextPour.mockResolvedValue(null);
      await service.valider(id, { commentaire: 'OK' }, controleur);
      const payload = await getAuditPayload(id, 'VALIDER_BUDGET');
      expect('via_delegation_id' in payload).toBe(false);
    });
  });
});
