/**
 * Tests d'intégration listener (Lot 4.3) — vérifient qu'un événement
 * applicatif émis par un service métier produit bien la ligne
 * email_log attendue (résolution destinataires + envoi dry-run).
 *
 * Pas de SMTP réel : on reste en dry-run. Le but est de valider que :
 *  1. l'event nommé déclenche bien le bon listener
 *  2. la résolution destinataires applique la bonne logique
 *  3. la ligne email_log est créée avec le bon evenement + statut
 */
import { ConfigService } from '@nestjs/config';
import { EventEmitter2 } from '@nestjs/event-emitter';
import { DataType, IMemoryDb, newDb } from 'pg-mem';
import { DataSource } from 'typeorm';

import {
  PermissionsService,
  type EffectivePermission,
} from '../auth/permissions.service';
import { Permission } from '../roles/entities/permission.entity';
import { Role } from '../roles/entities/role.entity';
import { RolePermission } from '../roles/entities/role-permission.entity';
import { User } from '../users/entities/user.entity';
import { UserRole } from '../users/entities/user-role.entity';
import { EmailLog } from './entities/email-log.entity';
import {
  EVENT_AFFECTATION_CREATED,
  EVENT_BUDGET_PUBLISHED,
  EVENT_BUDGET_REJECTED,
  EVENT_BUDGET_SUBMITTED,
  EVENT_BUDGET_VALIDATED,
  EVENT_DELEGATION_CREATED,
  EVENT_DELEGATION_EXPIRED,
  EVENT_DELEGATION_REVOKED,
} from './notifications.events';
import { NotificationsListeners } from './notifications.listeners';
import { NotificationsService } from './notifications.service';

function buildMemDb(): IMemoryDb {
  const db = newDb({ autoCreateForeignKeyIndices: true });
  db.public.registerFunction({
    name: 'current_database',
    args: [],
    returns: DataType.text,
    implementation: () => 'test',
  });
  db.public.registerFunction({
    name: 'version',
    args: [],
    returns: DataType.text,
    implementation: () => 'PostgreSQL 15 (pg-mem)',
  });
  return db;
}

async function createDataSource(): Promise<DataSource> {
  const db = buildMemDb();
  const ds = db.adapters.createTypeormDataSource({
    type: 'postgres',
    entities: [User, UserRole, Role, Permission, RolePermission, EmailLog],
    synchronize: true,
  }) as DataSource;
  await ds.initialize();
  await ds.query(`
    CREATE TABLE audit_log (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      type_action varchar(64) NOT NULL,
      utilisateur varchar(255) NOT NULL,
      id_cible varchar(255) NULL,
      statut varchar(20) NOT NULL,
      date_action timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`);
  return ds;
}

async function seedUser(ds: DataSource, email: string): Promise<User> {
  await ds.query(
    `INSERT INTO "user"
       (email, mot_de_passe_hash, nom, prenom, est_actif,
        notifications_email_actives, utilisateur_creation)
     VALUES ($1, 'h', 'N', 'P', true, true, 'system')`,
    [email],
  );
  const u = await ds.getRepository(User).findOne({ where: { email } });
  if (!u) throw new Error('seed user not found');
  return u;
}

function makePermsMock(
  perms: Record<string, string[]> = {},
): PermissionsService {
  return {
    getEffectivePermissions: async (): Promise<EffectivePermission[]> => [],
    hasPermission: async (uid: string, codes: string[]): Promise<boolean> => {
      const has = new Set(perms[uid] ?? []);
      return codes.some((c) => has.has(c));
    },
  } as unknown as PermissionsService;
}

describe('Notifications — intégration listener (Lot 4.3)', () => {
  let ds: DataSource;
  let service: NotificationsService;
  let listeners: NotificationsListeners;
  let events: EventEmitter2;

  beforeAll(async () => {
    ds = await createDataSource();
  });
  afterAll(async () => {
    await ds.destroy();
  });

  beforeEach(async () => {
    await ds.query('DELETE FROM email_log');
    await ds.query('DELETE FROM "user"');
    await ds.query('DELETE FROM audit_log');

    events = new EventEmitter2({ wildcard: false, delimiter: '.' });
  });

  function setupAvecPerms(perms: Record<string, string[]>): void {
    service = new NotificationsService(
      ds.getRepository(EmailLog),
      ds.getRepository(User),
      {
        get: (k: string, def?: string) =>
          k === 'EMAIL_DRY_RUN' ? 'true' : (def ?? ''),
      } as unknown as ConfigService,
      makePermsMock(perms),
    );
    listeners = new NotificationsListeners(service);
    // Câblage manuel des @OnEvent (nécessaire hors NestJS module).
    events.on(EVENT_BUDGET_SUBMITTED, (p) => listeners.onBudgetSubmitted(p));
    events.on(EVENT_BUDGET_VALIDATED, (p) => listeners.onBudgetValidated(p));
    events.on(EVENT_BUDGET_REJECTED, (p) => listeners.onBudgetRejected(p));
    events.on(EVENT_BUDGET_PUBLISHED, (p) => listeners.onBudgetPublished(p));
    events.on(EVENT_DELEGATION_CREATED, (p) =>
      listeners.onDelegationCreated(p),
    );
    events.on(EVENT_DELEGATION_EXPIRED, (p) =>
      listeners.onDelegationExpired(p),
    );
    events.on(EVENT_DELEGATION_REVOKED, (p) =>
      listeners.onDelegationRevoked(p),
    );
    events.on(EVENT_AFFECTATION_CREATED, (p) =>
      listeners.onAffectationCreated(p),
    );
  }

  async function attendreLogs(timeoutMs = 500): Promise<void> {
    // Petit délai pour que les @OnEvent async finissent.
    await new Promise((r) => setTimeout(r, timeoutMs));
  }

  // ─── 1. budget.submitted déclenche email_log E1 ──────────────────

  it('budget.submitted → email_log BUDGET_SOUMIS pour les VALIDATEUR', async () => {
    const auteur = await seedUser(ds, 'sais@miznas.local');
    const valid = await seedUser(ds, 'valid@miznas.local');
    setupAvecPerms({ [valid.id]: ['BUDGET.VALIDER'] });

    await events.emitAsync(EVENT_BUDGET_SUBMITTED, {
      versionId: '1',
      codeVersion: 'BI_2027',
      auteurEmail: auteur.email,
      auteurId: auteur.id,
      commentaire: null,
    });
    await attendreLogs();

    const logs = await ds.getRepository(EmailLog).find();
    expect(logs).toHaveLength(1);
    expect(logs[0]!.evenement).toBe('BUDGET_SOUMIS');
    expect(logs[0]!.destinataireEmail).toBe('valid@miznas.local');
    expect(logs[0]!.statut).toBe('SUPPRIME'); // dry-run
  });

  // ─── 2. budget.validated → soumetteur + publieurs ────────────────

  it('budget.validated → email_log BUDGET_VALIDE pour soumetteur + PUBLIER', async () => {
    const soum = await seedUser(ds, 'soum@miznas.local');
    const pub = await seedUser(ds, 'pub@miznas.local');
    await ds.query(
      `INSERT INTO audit_log (type_action, utilisateur, id_cible, statut)
       VALUES ('SOUMETTRE_BUDGET', $1, '7', 'success')`,
      [soum.email],
    );
    setupAvecPerms({ [pub.id]: ['BUDGET.PUBLIER'] });

    await events.emitAsync(EVENT_BUDGET_VALIDATED, {
      versionId: '7',
      codeVersion: 'BI_2027',
      auteurEmail: 'controleur@miznas.local',
      auteurId: '999',
      commentaire: 'OK',
    });
    await attendreLogs();

    const logs = await ds.getRepository(EmailLog).find({
      order: { id: 'ASC' },
    });
    expect(logs).toHaveLength(2);
    expect(new Set(logs.map((l) => l.destinataireEmail))).toEqual(
      new Set(['soum@miznas.local', 'pub@miznas.local']),
    );
    expect(logs.every((l) => l.evenement === 'BUDGET_VALIDE')).toBe(true);
  });

  // ─── 3. budget.rejected → soumetteur uniquement ──────────────────

  it('budget.rejected → email_log BUDGET_REJETE soumetteur seul', async () => {
    const soum = await seedUser(ds, 'soum@miznas.local');
    await seedUser(ds, 'autre@miznas.local');
    await ds.query(
      `INSERT INTO audit_log (type_action, utilisateur, id_cible, statut)
       VALUES ('SOUMETTRE_BUDGET', $1, '5', 'success')`,
      [soum.email],
    );
    setupAvecPerms({});

    await events.emitAsync(EVENT_BUDGET_REJECTED, {
      versionId: '5',
      codeVersion: 'BI_2027',
      auteurEmail: 'controleur@miznas.local',
      auteurId: '999',
      commentaire: 'Erreurs Q3',
    });
    await attendreLogs();

    const logs = await ds.getRepository(EmailLog).find();
    expect(logs).toHaveLength(1);
    expect(logs[0]!.destinataireEmail).toBe('soum@miznas.local');
    expect(logs[0]!.evenement).toBe('BUDGET_REJETE');
    // Le motif est dans le payload pour audit
    expect(logs[0]!.payload.commentaire).toBe('Erreurs Q3');
  });

  // ─── 4. budget.published → soum + valid + saisisseurs ────────────

  it('budget.published → email_log BUDGET_PUBLIE multi-destinataires', async () => {
    const soum = await seedUser(ds, 'soum@miznas.local');
    const valid = await seedUser(ds, 'valid@miznas.local');
    const sais = await seedUser(ds, 'sais@miznas.local');
    await ds.query(
      `INSERT INTO audit_log (type_action, utilisateur, id_cible, statut) VALUES
        ('SOUMETTRE_BUDGET', $1, '4', 'success'),
        ('VALIDER_BUDGET',   $2, '4', 'success')`,
      [soum.email, valid.email],
    );
    setupAvecPerms({ [sais.id]: ['BUDGET.SAISIR'] });

    await events.emitAsync(EVENT_BUDGET_PUBLISHED, {
      versionId: '4',
      codeVersion: 'BI_2027',
      auteurEmail: 'directeur@miznas.local',
      auteurId: '999',
      commentaire: 'Officiel',
    });
    await attendreLogs();

    const logs = await ds.getRepository(EmailLog).find();
    expect(logs.length).toBe(3);
    expect(logs.every((l) => l.evenement === 'BUDGET_PUBLIE')).toBe(true);
  });

  // ─── 5. delegation.created → délégataire seul ────────────────────

  it('delegation.created → email_log DELEGATION_CREEE pour délégataire', async () => {
    const dlg = await seedUser(ds, 'dlg@miznas.local');
    setupAvecPerms({});

    await events.emitAsync(EVENT_DELEGATION_CREATED, {
      delegationId: '99',
      fkDelegant: '1',
      fkDelegataire: dlg.id,
      permissions: ['VALIDATION'],
      dateDebut: '2027-01-01',
      dateFin: '2027-01-31',
      motif: 'Mission',
    });
    await attendreLogs();

    const logs = await ds.getRepository(EmailLog).find();
    expect(logs).toHaveLength(1);
    expect(logs[0]!.evenement).toBe('DELEGATION_CREEE');
    expect(logs[0]!.destinataireEmail).toBe('dlg@miznas.local');
  });

  // ─── 6. delegation.expired → délégant + délégataire ──────────────

  it('delegation.expired → email_log pour délégant ET délégataire', async () => {
    const a = await seedUser(ds, 'a@miznas.local');
    const b = await seedUser(ds, 'b@miznas.local');
    setupAvecPerms({});

    await events.emitAsync(EVENT_DELEGATION_EXPIRED, {
      delegationId: '99',
      fkDelegant: a.id,
      fkDelegataire: b.id,
      permissions: ['VALIDATION'],
      dateDebut: '2027-01-01',
      dateFin: '2027-01-31',
      motif: 'Mission',
    });
    await attendreLogs();

    const logs = await ds.getRepository(EmailLog).find();
    expect(logs).toHaveLength(2);
    expect(new Set(logs.map((l) => l.destinataireEmail))).toEqual(
      new Set(['a@miznas.local', 'b@miznas.local']),
    );
  });

  // ─── 7. affectation.created → user affecté ───────────────────────

  it('affectation.created → email_log AFFECTATION_CREEE pour le user', async () => {
    const u = await seedUser(ds, 'newbie@miznas.local');
    setupAvecPerms({});

    await events.emitAsync(EVENT_AFFECTATION_CREATED, {
      affectationId: '50',
      fkUser: u.id,
      cibleType: 'CR',
      cibleId: '12',
      cibleCrIds: null,
      dateDebut: '2027-01-15',
      motif: 'Renfort pôle Mali',
    });
    await attendreLogs();

    const logs = await ds.getRepository(EmailLog).find();
    expect(logs).toHaveLength(1);
    expect(logs[0]!.evenement).toBe('AFFECTATION_CREEE');
    expect(logs[0]!.destinataireEmail).toBe('newbie@miznas.local');
  });

  // ─── 8. delegation.revoked → délégataire ─────────────────────────

  it('delegation.revoked → email_log DELEGATION_REVOQUEE pour délégataire', async () => {
    const dlg = await seedUser(ds, 'dlg@miznas.local');
    setupAvecPerms({});

    await events.emitAsync(EVENT_DELEGATION_REVOKED, {
      delegationId: '99',
      fkDelegant: '1',
      fkDelegataire: dlg.id,
      permissions: ['VALIDATION'],
      dateDebut: '2027-01-01',
      dateFin: '2027-01-31',
      motif: 'Mission',
      motifRevocation: 'Retour anticipé',
    });
    await attendreLogs();

    const logs = await ds.getRepository(EmailLog).find();
    expect(logs).toHaveLength(1);
    expect(logs[0]!.payload.motifRevocation).toBe('Retour anticipé');
  });
});
