/**
 * Tests unitaires NotificationsService (Lot 4.3) via pg-mem.
 *
 * Couvre :
 *  - envoyer() : dry-run, mode réel mocké (succès), filtrage
 *    préférences toggle global, échec SMTP avec retry x3 → ECHEC
 *  - resoudreDestinataires() : 1 cas par événement (E1-E5,E7-E9)
 *  - rejouer() : retry manuel d'un email en ECHEC
 */
import { ConfigService } from '@nestjs/config';
import { DataType, IMemoryDb, newDb } from 'pg-mem';
import { DataSource } from 'typeorm';

import {
  PermissionsService,
  type EffectivePermission,
} from '../auth/permissions.service';
import { Permission } from '../roles/entities/permission.entity';
import { Role } from '../roles/entities/role.entity';
import { RolePermission } from '../roles/entities/role-permission.entity';
import { User } from '../users/entities/user.entity';
import { UserRole } from '../users/entities/user-role.entity';
import { EmailLog, type TypeEvenement } from './entities/email-log.entity';
import { NotificationsService } from './notifications.service';

// ─── Mock nodemailer ────────────────────────────────────────────────

const sendMailMock = jest.fn();
jest.mock('nodemailer', () => ({
  createTransport: jest.fn(() => ({
    sendMail: (...args: unknown[]) => sendMailMock(...args),
  })),
}));

// ─── DB ─────────────────────────────────────────────────────────────

function buildMemDb(): IMemoryDb {
  const db = newDb({ autoCreateForeignKeyIndices: true });
  db.public.registerFunction({
    name: 'current_database',
    args: [],
    returns: DataType.text,
    implementation: () => 'test',
  });
  db.public.registerFunction({
    name: 'version',
    args: [],
    returns: DataType.text,
    implementation: () => 'PostgreSQL 15 (pg-mem)',
  });
  return db;
}

async function createDataSource(): Promise<DataSource> {
  const db = buildMemDb();
  const ds = db.adapters.createTypeormDataSource({
    type: 'postgres',
    entities: [User, UserRole, Role, Permission, RolePermission, EmailLog],
    synchronize: true,
  }) as DataSource;
  await ds.initialize();
  // audit_log table minimale (utilisée par findUserParAuditAction).
  await ds.query(`
    CREATE TABLE audit_log (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      type_action varchar(64) NOT NULL,
      utilisateur varchar(255) NOT NULL,
      id_cible varchar(255) NULL,
      statut varchar(20) NOT NULL,
      date_action timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`);
  return ds;
}

async function seedUser(
  ds: DataSource,
  email: string,
  options: {
    notificationsEmailActives?: boolean;
    notificationsEmailTypes?: string[] | null;
  } = {},
): Promise<User> {
  await ds.query(
    `INSERT INTO "user"
      (email, mot_de_passe_hash, nom, prenom, est_actif,
       notifications_email_actives, notifications_email_types,
       utilisateur_creation)
     VALUES ($1, 'h', 'N', 'P', true, $2, $3, 'system')`,
    [
      email,
      options.notificationsEmailActives ?? true,
      options.notificationsEmailTypes ?? null,
    ],
  );
  // Repository TypeORM pour avoir le mapping camelCase correct.
  const u = await ds
    .getRepository(User)
    .findOne({ where: { email } });
  if (!u) throw new Error('seed user not found');
  return u;
}

function makeConfig(env: Record<string, string>): ConfigService {
  return {
    get: (k: string, def?: string): string => env[k] ?? def ?? '',
  } as unknown as ConfigService;
}

function makePermsMock(
  permsParUser: Record<string, string[]> = {},
): PermissionsService {
  return {
    getEffectivePermissions: async (): Promise<EffectivePermission[]> => [],
    hasPermission: async (uid: string, codes: string[]): Promise<boolean> => {
      const possessed = new Set(permsParUser[uid] ?? []);
      return codes.some((c) => possessed.has(c));
    },
  } as unknown as PermissionsService;
}

describe('NotificationsService', () => {
  let ds: DataSource;
  let service: NotificationsService;

  beforeAll(async () => {
    ds = await createDataSource();
  });
  afterAll(async () => {
    await ds.destroy();
  });

  beforeEach(async () => {
    sendMailMock.mockReset();
    await ds.query('DELETE FROM email_log');
    await ds.query('DELETE FROM "user"');
    await ds.query('DELETE FROM audit_log');
  });

  // ─── envoyer() — 4 cas ────────────────────────────────────────────

  describe('envoyer', () => {
    it('dry-run : crée une ligne SUPPRIME sans appeler SMTP', async () => {
      const cfg = makeConfig({ EMAIL_DRY_RUN: 'true' });
      service = new NotificationsService(
        ds.getRepository(EmailLog),
        ds.getRepository(User),
        cfg,
        makePermsMock(),
      );
      const u = await seedUser(ds, 'a@miznas.local');
      const r = await service.envoyer('BUDGET_SOUMIS', u, {
        codeVersion: 'V1',
        auteurEmail: 'b@miznas.local',
      });
      expect(r.envoye).toBe(false);
      expect(r.emailLog.statut).toBe('SUPPRIME');
      expect(sendMailMock).not.toHaveBeenCalled();
    });

    it('mode réel : appel sendMail OK → statut=ENVOYE', async () => {
      sendMailMock.mockResolvedValue({});
      const cfg = makeConfig({ EMAIL_DRY_RUN: 'false' });
      service = new NotificationsService(
        ds.getRepository(EmailLog),
        ds.getRepository(User),
        cfg,
        makePermsMock(),
      );
      const u = await seedUser(ds, 'a@miznas.local');
      const r = await service.envoyer('BUDGET_SOUMIS', u, {
        codeVersion: 'V1',
        auteurEmail: 'b@miznas.local',
      });
      expect(r.envoye).toBe(true);
      expect(r.emailLog.statut).toBe('ENVOYE');
      expect(r.emailLog.tentatives).toBe(1);
      expect(sendMailMock).toHaveBeenCalledTimes(1);
    });

    it('échec SMTP simulé → 3 tentatives → ECHEC + dernier_message_erreur', async () => {
      sendMailMock.mockRejectedValue(new Error('ECONNREFUSED 1025'));
      const cfg = makeConfig({ EMAIL_DRY_RUN: 'false' });
      service = new NotificationsService(
        ds.getRepository(EmailLog),
        ds.getRepository(User),
        cfg,
        makePermsMock(),
      );
      const u = await seedUser(ds, 'a@miznas.local');
      const r = await service.envoyer('BUDGET_SOUMIS', u, {
        codeVersion: 'V1',
        auteurEmail: 'b@miznas.local',
      });
      expect(r.envoye).toBe(false);
      expect(r.emailLog.statut).toBe('ECHEC');
      expect(r.emailLog.tentatives).toBe(3);
      expect(r.emailLog.dernierMessageErreur).toMatch(/ECONNREFUSED/);
      expect(sendMailMock).toHaveBeenCalledTimes(3);
    }, 30000);

    it('préférence notifications_email_actives=false → SUPPRIME', async () => {
      const cfg = makeConfig({ EMAIL_DRY_RUN: 'false' });
      service = new NotificationsService(
        ds.getRepository(EmailLog),
        ds.getRepository(User),
        cfg,
        makePermsMock(),
      );
      const u = await seedUser(ds, 'a@miznas.local', {
        notificationsEmailActives: false,
      });
      const r = await service.envoyer('BUDGET_SOUMIS', u, {
        codeVersion: 'V1',
        auteurEmail: 'b@miznas.local',
      });
      expect(r.envoye).toBe(false);
      expect(r.emailLog.statut).toBe('SUPPRIME');
      expect(r.emailLog.payload._motifSuppression).toBe(
        'PREF_TOGGLE_GLOBAL_OFF',
      );
      expect(sendMailMock).not.toHaveBeenCalled();
    });

    it('liste blanche notifications_email_types ne contient pas l\'event → SUPPRIME', async () => {
      const cfg = makeConfig({ EMAIL_DRY_RUN: 'false' });
      service = new NotificationsService(
        ds.getRepository(EmailLog),
        ds.getRepository(User),
        cfg,
        makePermsMock(),
      );
      const u = await seedUser(ds, 'a@miznas.local', {
        notificationsEmailTypes: ['BUDGET_PUBLIE'],
      });
      const r = await service.envoyer('BUDGET_SOUMIS', u, {
        codeVersion: 'V1',
        auteurEmail: 'b@miznas.local',
      });
      expect(r.emailLog.statut).toBe('SUPPRIME');
      expect(r.emailLog.payload._motifSuppression).toBe(
        'PREF_TYPE_NON_SOUSCRIT',
      );
    });
  });

  // ─── resoudreDestinataires() — 8 cas (1 par événement) ───────────

  describe('resoudreDestinataires', () => {
    beforeEach(() => {
      service = new NotificationsService(
        ds.getRepository(EmailLog),
        ds.getRepository(User),
        makeConfig({ EMAIL_DRY_RUN: 'true' }),
        makePermsMock(),
      );
    });

    it("E1 BUDGET_SOUMIS → users avec BUDGET.VALIDER (hors auteur)", async () => {
      const auteur = await seedUser(ds, 'auteur@miznas.local');
      const valid = await seedUser(ds, 'valid@miznas.local');
      await seedUser(ds, 'autre@miznas.local');
      service = new NotificationsService(
        ds.getRepository(EmailLog),
        ds.getRepository(User),
        makeConfig({ EMAIL_DRY_RUN: 'true' }),
        makePermsMock({
          [valid.id]: ['BUDGET.VALIDER'],
          [auteur.id]: ['BUDGET.VALIDER'], // auteur exclu malgré la perm
        }),
      );
      const r = await service.resoudreDestinataires('BUDGET_SOUMIS', {
        budgetVersionId: '99',
        auteurId: auteur.id,
      });
      expect(r.map((u) => u.email)).toEqual(['valid@miznas.local']);
    });

    it("E2 BUDGET_VALIDE → soumetteur (audit lookup) + users BUDGET.PUBLIER", async () => {
      const soum = await seedUser(ds, 'soum@miznas.local');
      const pub = await seedUser(ds, 'pub@miznas.local');
      // Audit log d'une soumission précédente sur cette version
      await ds.query(
        `INSERT INTO audit_log (type_action, utilisateur, id_cible, statut)
         VALUES ('SOUMETTRE_BUDGET', $1, '88', 'success')`,
        [soum.email],
      );
      service = new NotificationsService(
        ds.getRepository(EmailLog),
        ds.getRepository(User),
        makeConfig({ EMAIL_DRY_RUN: 'true' }),
        makePermsMock({ [pub.id]: ['BUDGET.PUBLIER'] }),
      );
      const r = await service.resoudreDestinataires('BUDGET_VALIDE', {
        budgetVersionId: '88',
      });
      expect(r.map((u) => u.email).sort()).toEqual([
        'pub@miznas.local',
        'soum@miznas.local',
      ]);
    });

    it("E3 BUDGET_REJETE → soumetteur uniquement", async () => {
      const soum = await seedUser(ds, 'soum@miznas.local');
      await seedUser(ds, 'autre@miznas.local');
      await ds.query(
        `INSERT INTO audit_log (type_action, utilisateur, id_cible, statut)
         VALUES ('SOUMETTRE_BUDGET', $1, '77', 'success')`,
        [soum.email],
      );
      const r = await service.resoudreDestinataires('BUDGET_REJETE', {
        budgetVersionId: '77',
      });
      expect(r.map((u) => u.email)).toEqual(['soum@miznas.local']);
    });

    it("E4 BUDGET_PUBLIE → soumetteur + validateur + saisisseurs", async () => {
      const soum = await seedUser(ds, 'soum@miznas.local');
      const valid = await seedUser(ds, 'valid@miznas.local');
      const sais = await seedUser(ds, 'sais@miznas.local');
      await ds.query(
        `INSERT INTO audit_log (type_action, utilisateur, id_cible, statut)
         VALUES
           ('SOUMETTRE_BUDGET', $1, '66', 'success'),
           ('VALIDER_BUDGET',    $2, '66', 'success')`,
        [soum.email, valid.email],
      );
      service = new NotificationsService(
        ds.getRepository(EmailLog),
        ds.getRepository(User),
        makeConfig({ EMAIL_DRY_RUN: 'true' }),
        makePermsMock({ [sais.id]: ['BUDGET.SAISIR'] }),
      );
      const r = await service.resoudreDestinataires('BUDGET_PUBLIE', {
        budgetVersionId: '66',
      });
      expect(r.map((u) => u.email).sort()).toEqual([
        'sais@miznas.local',
        'soum@miznas.local',
        'valid@miznas.local',
      ]);
    });

    it("E5 DELEGATION_CREEE → délégataire (id fourni par listener)", async () => {
      const dlg = await seedUser(ds, 'dlg@miznas.local');
      const r = await service.resoudreDestinataires('DELEGATION_CREEE', {
        destinataireUserIds: [dlg.id],
      });
      expect(r).toHaveLength(1);
      expect(r[0]!.email).toBe('dlg@miznas.local');
    });

    it("E7 DELEGATION_EXPIREE → délégant + délégataire", async () => {
      const a = await seedUser(ds, 'a@miznas.local');
      const b = await seedUser(ds, 'b@miznas.local');
      const r = await service.resoudreDestinataires('DELEGATION_EXPIREE', {
        destinataireUserIds: [a.id, b.id],
      });
      expect(r).toHaveLength(2);
    });

    it("E8 DELEGATION_REVOQUEE → délégataire", async () => {
      const dlg = await seedUser(ds, 'dlg@miznas.local');
      const r = await service.resoudreDestinataires('DELEGATION_REVOQUEE', {
        destinataireUserIds: [dlg.id],
      });
      expect(r.map((u) => u.email)).toEqual(['dlg@miznas.local']);
    });

    it("E9 AFFECTATION_CREEE → user nouvellement affecté", async () => {
      const u = await seedUser(ds, 'newbie@miznas.local');
      const r = await service.resoudreDestinataires('AFFECTATION_CREEE', {
        destinataireUserIds: [u.id],
      });
      expect(r.map((x) => x.email)).toEqual(['newbie@miznas.local']);
    });
  });

  // ─── rejouer() ────────────────────────────────────────────────────

  describe('rejouer', () => {
    it('rejoue un ECHEC → si succès SMTP, statut passe à ENVOYE', async () => {
      const cfg = makeConfig({ EMAIL_DRY_RUN: 'false' });
      const u = await seedUser(ds, 'a@miznas.local');
      service = new NotificationsService(
        ds.getRepository(EmailLog),
        ds.getRepository(User),
        cfg,
        makePermsMock(),
      );
      // 1ère tentative : échec
      sendMailMock.mockRejectedValue(new Error('SMTP DOWN'));
      const r1 = await service.envoyer('BUDGET_SOUMIS', u, {
        codeVersion: 'V42',
        auteurEmail: 'b@miznas.local',
      });
      expect(r1.emailLog.statut).toBe('ECHEC');
      // 2e tentative : succès
      sendMailMock.mockReset();
      sendMailMock.mockResolvedValue({});
      const r2 = await service.rejouer(r1.emailLog.id);
      expect(r2.envoye).toBe(true);
      expect(r2.emailLog.statut).toBe('ENVOYE');
    }, 30000);
  });

  // ─── statistiques ────────────────────────────────────────────────

  describe('statistiques', () => {
    it('compte correctement par statut sur 30 jours', async () => {
      const u = await seedUser(ds, 'a@miznas.local');
      service = new NotificationsService(
        ds.getRepository(EmailLog),
        ds.getRepository(User),
        makeConfig({ EMAIL_DRY_RUN: 'true' }),
        makePermsMock(),
      );
      // 3 envois SUPPRIME (dry-run)
      const events: TypeEvenement[] = [
        'BUDGET_SOUMIS',
        'BUDGET_SOUMIS',
        'BUDGET_VALIDE',
      ];
      for (const e of events) {
        await service.envoyer(e, u, {
          codeVersion: 'X',
          auteurEmail: 'y@m.io',
        });
      }
      const stats = await service.statistiques();
      expect(stats.parStatut.SUPPRIME).toBe(3);
      expect(stats.parEvenement.BUDGET_SOUMIS).toBe(2);
      expect(stats.parEvenement.BUDGET_VALIDE).toBe(1);
    });
  });
});
