/**
 * Tests unitaires UserPerimetreService (Lot 4.1.B.2) via pg-mem.
 *
 * Couvre :
 *  - création STRUCTURE / CR / CR_SET avec validation cible
 *  - rejet CR_SET avec < 2 CR
 *  - rejet date_fin < date_debut
 *  - audit CREER_AFFECTATION / RETIRER_AFFECTATION
 *  - retrait soft (actif=false)
 *  - lister avec filtres actif / origine / dateRef
 */
import {
  BadRequestException,
  ConflictException,
  NotFoundException,
} from '@nestjs/common';
import { DataType, IMemoryDb, newDb } from 'pg-mem';
import { DataSource } from 'typeorm';

import { AuditLog } from '../../audit/entities/audit-log.entity';
import { AuditService } from '../../audit/audit.service';
import { Permission } from '../../roles/entities/permission.entity';
import { Role } from '../../roles/entities/role.entity';
import { RolePermission } from '../../roles/entities/role-permission.entity';
import { User } from '../entities/user.entity';
import { UserPerimetre } from '../entities/user-perimetre.entity';
import { UserRole } from '../entities/user-role.entity';
import { UserPerimetreService } from './user-perimetre.service';

function buildMemDb(): IMemoryDb {
  const db = newDb({ autoCreateForeignKeyIndices: true });
  db.public.registerFunction({
    name: 'current_database',
    args: [],
    returns: DataType.text,
    implementation: () => 'test',
  });
  db.public.registerFunction({
    name: 'version',
    args: [],
    returns: DataType.text,
    implementation: () => 'PostgreSQL 15 (pg-mem)',
  });
  return db;
}

async function createDataSource(): Promise<DataSource> {
  const db = buildMemDb();
  const ds = db.adapters.createTypeormDataSource({
    type: 'postgres',
    entities: [
      User,
      UserRole,
      UserPerimetre,
      Role,
      Permission,
      RolePermission,
      AuditLog,
    ],
    synchronize: true,
  }) as DataSource;
  await ds.initialize();

  // Tables minimales dim_structure / dim_centre_responsabilite pour la
  // validation des cibles.
  await ds.query(`
    CREATE TABLE dim_structure (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_structure varchar(50) NOT NULL,
      version_courante boolean DEFAULT true,
      est_actif boolean DEFAULT true
    )
  `);
  await ds.query(`
    CREATE TABLE dim_centre_responsabilite (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_cr varchar(50) NOT NULL,
      version_courante boolean DEFAULT true,
      est_actif boolean DEFAULT true
    )
  `);
  return ds;
}

interface SeedIds {
  userId: string;
  structureCivId: string;
  crCivId: string;
  crBfaId: string;
}

async function seed(ds: DataSource): Promise<SeedIds> {
  await ds.query(
    `INSERT INTO "user" (email, mot_de_passe_hash, nom, prenom, est_actif, utilisateur_creation)
     VALUES ('preparateur@miznas.local', 'h', 'Aïcha', 'Diallo', true, 'system')`,
  );
  const userId = String(
    ((await ds.query(
      `SELECT id FROM "user" WHERE email='preparateur@miznas.local'`,
    )) as Array<{ id: string }>)[0]!.id,
  );
  await ds.query(
    `INSERT INTO dim_structure (code_structure) VALUES ('CIV'), ('BFA')`,
  );
  await ds.query(
    `INSERT INTO dim_centre_responsabilite (code_cr) VALUES ('BR_CIV'), ('BR_BFA')`,
  );
  const struct = (await ds.query(
    `SELECT code_structure, id FROM dim_structure`,
  )) as Array<{ code_structure: string; id: string }>;
  const crs = (await ds.query(
    `SELECT code_cr, id FROM dim_centre_responsabilite`,
  )) as Array<{ code_cr: string; id: string }>;
  return {
    userId,
    structureCivId: String(struct.find((s) => s.code_structure === 'CIV')!.id),
    crCivId: String(crs.find((c) => c.code_cr === 'BR_CIV')!.id),
    crBfaId: String(crs.find((c) => c.code_cr === 'BR_BFA')!.id),
  };
}

describe('UserPerimetreService', () => {
  let ds: DataSource;
  let service: UserPerimetreService;
  let auditService: AuditService;
  let ids: SeedIds;

  beforeAll(async () => {
    ds = await createDataSource();
    auditService = new AuditService(ds.getRepository(AuditLog));
    // Lot 4.3 — mock EventEmitter2 (couplage faible vers notifications)
    const events = { emit: jest.fn(), emitAsync: jest.fn() } as never;
    service = new UserPerimetreService(
      ds.getRepository(UserPerimetre),
      ds.getRepository(User),
      auditService,
      events,
    );
    ids = await seed(ds);
  });

  afterAll(async () => {
    await ds.destroy();
  });

  beforeEach(async () => {
    await ds.query('DELETE FROM user_perimetres');
    await ds.query('DELETE FROM audit_log');
  });

  // ─── Création ────────────────────────────────────────────────────

  it('crée une affectation STRUCTURE valide', async () => {
    const r = await service.creer(
      ids.userId,
      { cibleType: 'STRUCTURE', cibleId: ids.structureCivId },
      'admin@miznas.local',
    );
    expect(r.cibleType).toBe('STRUCTURE');
    expect(String(r.cibleId)).toBe(ids.structureCivId);
    expect(r.actif).toBe(true);
    expect(r.origine).toBe('AFFECTATION');
  });

  it('crée une affectation CR valide', async () => {
    const r = await service.creer(
      ids.userId,
      { cibleType: 'CR', cibleId: ids.crCivId },
      'admin@miznas.local',
    );
    expect(r.cibleType).toBe('CR');
    expect(String(r.cibleId)).toBe(ids.crCivId);
  });

  it('crée une affectation CR_SET valide (≥ 2 CR)', async () => {
    const r = await service.creer(
      ids.userId,
      { cibleType: 'CR_SET', cibleCrIds: [ids.crCivId, ids.crBfaId] },
      'admin@miznas.local',
    );
    expect(r.cibleType).toBe('CR_SET');
    expect(r.cibleCrIds).toHaveLength(2);
    expect(r.cibleId).toBeNull();
  });

  it('rejette CR_SET avec un seul CR (BadRequest)', async () => {
    await expect(
      service.creer(
        ids.userId,
        { cibleType: 'CR_SET', cibleCrIds: [ids.crCivId] },
        'admin',
      ),
    ).rejects.toThrow(BadRequestException);
  });

  it('rejette CR_SET avec cible_id non null', async () => {
    await expect(
      service.creer(
        ids.userId,
        {
          cibleType: 'CR_SET',
          cibleId: ids.crCivId,
          cibleCrIds: [ids.crCivId, ids.crBfaId],
        },
        'admin',
      ),
    ).rejects.toThrow(BadRequestException);
  });

  it('rejette STRUCTURE sans cible_id', async () => {
    await expect(
      service.creer(ids.userId, { cibleType: 'STRUCTURE' }, 'admin'),
    ).rejects.toThrow(BadRequestException);
  });

  it('rejette CR avec cible_cr_ids', async () => {
    await expect(
      service.creer(
        ids.userId,
        {
          cibleType: 'CR',
          cibleId: ids.crCivId,
          cibleCrIds: [ids.crCivId, ids.crBfaId],
        },
        'admin',
      ),
    ).rejects.toThrow(BadRequestException);
  });

  it('rejette structure inexistante', async () => {
    await expect(
      service.creer(
        ids.userId,
        { cibleType: 'STRUCTURE', cibleId: '99999' },
        'admin',
      ),
    ).rejects.toThrow(BadRequestException);
  });

  it('rejette date_fin < date_debut', async () => {
    await expect(
      service.creer(
        ids.userId,
        {
          cibleType: 'CR',
          cibleId: ids.crCivId,
          dateDebut: '2027-06-01',
          dateFin: '2027-05-01',
        },
        'admin',
      ),
    ).rejects.toThrow(BadRequestException);
  });

  it('rejette user inconnu (NotFound)', async () => {
    await expect(
      service.creer(
        '999999',
        { cibleType: 'CR', cibleId: ids.crCivId },
        'admin',
      ),
    ).rejects.toThrow(NotFoundException);
  });

  it('création écrit un audit CREER_AFFECTATION', async () => {
    await service.creer(
      ids.userId,
      { cibleType: 'CR', cibleId: ids.crCivId },
      'admin@miznas.local',
    );
    const audits = (await ds.query(
      `SELECT type_action, statut, payload_apres
         FROM audit_log WHERE type_action='CREER_AFFECTATION'`,
    )) as Array<{
      type_action: string;
      statut: string;
      payload_apres: { cibleType: string; userId: string };
    }>;
    expect(audits).toHaveLength(1);
    expect(audits[0]!.statut).toBe('success');
    expect(audits[0]!.payload_apres.cibleType).toBe('CR');
  });

  // ─── Retrait soft ────────────────────────────────────────────────

  it('retire désactive (actif=false) et écrit un audit RETIRER_AFFECTATION', async () => {
    const created = await service.creer(
      ids.userId,
      { cibleType: 'CR', cibleId: ids.crCivId },
      'admin',
    );
    await service.retirer(ids.userId, String(created.id), 'admin');
    const row = (await ds.query(
      `SELECT actif FROM user_perimetres WHERE id = $1`,
      [created.id],
    )) as Array<{ actif: boolean }>;
    expect(row[0]!.actif).toBe(false);
    const audits = (await ds.query(
      `SELECT type_action FROM audit_log WHERE type_action='RETIRER_AFFECTATION'`,
    )) as Array<{ type_action: string }>;
    expect(audits).toHaveLength(1);
  });

  it('retirer une affectation déjà inactive → Conflict', async () => {
    const created = await service.creer(
      ids.userId,
      { cibleType: 'CR', cibleId: ids.crCivId },
      'admin',
    );
    await service.retirer(ids.userId, String(created.id), 'admin');
    await expect(
      service.retirer(ids.userId, String(created.id), 'admin'),
    ).rejects.toThrow(ConflictException);
  });

  it('retirer une affectation inexistante → NotFound', async () => {
    await expect(
      service.retirer(ids.userId, '999999', 'admin'),
    ).rejects.toThrow(NotFoundException);
  });

  // ─── Lister ──────────────────────────────────────────────────────

  it('lister avec filtre actif=true ne retourne que les actives', async () => {
    const a = await service.creer(
      ids.userId,
      { cibleType: 'CR', cibleId: ids.crCivId },
      'admin',
    );
    const b = await service.creer(
      ids.userId,
      { cibleType: 'STRUCTURE', cibleId: ids.structureCivId },
      'admin',
    );
    await service.retirer(ids.userId, String(a.id), 'admin');

    const tous = await service.lister(ids.userId);
    expect(tous).toHaveLength(2);
    const actifs = await service.lister(ids.userId, { actif: true });
    expect(actifs).toHaveLength(1);
    expect(actifs[0]!.id).toBe(String(b.id));
  });

  it('lister avec filtre origine retourne uniquement les correspondants', async () => {
    await service.creer(
      ids.userId,
      { cibleType: 'CR', cibleId: ids.crCivId, origine: 'PRINCIPAL' },
      'admin',
    );
    await service.creer(
      ids.userId,
      { cibleType: 'CR', cibleId: ids.crBfaId, origine: 'AFFECTATION' },
      'admin',
    );
    const principal = await service.lister(ids.userId, { origine: 'PRINCIPAL' });
    expect(principal).toHaveLength(1);
  });

  // ─── Lot 4.1-fix2.B : transaction atomique create + audit ──────
  //
  // Note pg-mem : le ROLLBACK Postgres n'est pas implémenté côté
  // pg-mem (chaque statement est commit immédiatement). Le rollback
  // réel est validé en prod par la migration 049 + tests
  // d'intégration. Ici on valide :
  //  1) Si l'audit échoue, l'erreur remonte au caller (la transaction
  //     n'avale pas l'exception).
  //  2) auditService.log est appelé avec un EntityManager (2e arg)
  //     pour permettre le rollback solidaire en prod.

  it('Lot 4.1-fix2.B : creer — si audit échoue, l\'erreur remonte au caller', async () => {
    const auditSpy = jest
      .spyOn(auditService, 'log')
      .mockRejectedValueOnce(new Error('audit_log INSERT failed'));
    await expect(
      service.creer(
        ids.userId,
        { cibleType: 'CR', cibleId: ids.crCivId },
        'admin@miznas.local',
      ),
    ).rejects.toThrow(/audit_log INSERT failed/);
    auditSpy.mockRestore();
  });

  it('Lot 4.1-fix2.B : creer — auditService.log appelé avec EntityManager (rollback solidaire)', async () => {
    const auditSpy = jest.spyOn(auditService, 'log');
    await service.creer(
      ids.userId,
      { cibleType: 'CR', cibleId: ids.crCivId },
      'admin@miznas.local',
    );
    expect(auditSpy).toHaveBeenCalledTimes(1);
    // 2e argument = manager transactionnel (sinon rollback impossible)
    const args = auditSpy.mock.calls[0]!;
    expect(args).toHaveLength(2);
    expect(args[1]).toBeDefined();
    auditSpy.mockRestore();
  });

  it('Lot 4.1-fix2.B : retirer — audit appelé avec manager + erreur audit remonte', async () => {
    const created = await service.creer(
      ids.userId,
      { cibleType: 'CR', cibleId: ids.crCivId },
      'admin@miznas.local',
    );
    const auditSpy = jest
      .spyOn(auditService, 'log')
      .mockRejectedValueOnce(new Error('audit_log INSERT failed'));
    await expect(
      service.retirer(ids.userId, String(created.id), 'admin'),
    ).rejects.toThrow(/audit_log INSERT failed/);
    expect(auditSpy.mock.calls[0]).toHaveLength(2);
    expect(auditSpy.mock.calls[0]![1]).toBeDefined();
    auditSpy.mockRestore();
  });

  it('lister avec dateRef exclut les périmètres antérieurs / futurs', async () => {
    await service.creer(
      ids.userId,
      {
        cibleType: 'CR',
        cibleId: ids.crCivId,
        dateDebut: '2027-01-01',
        dateFin: '2027-06-30',
      },
      'admin',
    );
    const dansLeRange = await service.lister(ids.userId, {
      dateRef: '2027-03-15',
    });
    expect(dansLeRange).toHaveLength(1);
    const horsRange = await service.lister(ids.userId, {
      dateRef: '2027-12-15',
    });
    expect(horsRange).toHaveLength(0);
  });
});
