/**
 * Test de la migration 1779200000070 — vérifie que les libellés
 * des comptes 611100 et 611400 sont bien nettoyés et que l'UPDATE
 * est idempotent (aucun effet si les libellés sont déjà corrigés
 * ou si les codes n'existent pas).
 */
import { DataType, IMemoryDb, newDb } from 'pg-mem';
import { DataSource, type QueryRunner } from 'typeorm';

import { RenommerComptesTest1779200000070 } from '../1779200000070-RenommerComptesTest';

function buildMemDb(): IMemoryDb {
  const db = newDb({ autoCreateForeignKeyIndices: true });
  db.public.registerFunction({
    name: 'current_database',
    args: [],
    returns: DataType.text,
    implementation: () => 'test',
  });
  db.public.registerFunction({
    name: 'version',
    args: [],
    returns: DataType.text,
    implementation: () => 'PostgreSQL 15 (pg-mem)',
  });
  return db;
}

async function createDataSource(): Promise<DataSource> {
  const db = buildMemDb();
  const ds = db.adapters.createTypeormDataSource({
    type: 'postgres',
    entities: [],
    synchronize: false,
  }) as DataSource;
  await ds.initialize();
  // Schéma minimal (uniquement les colonnes touchées par la migration).
  await ds.query(`
    CREATE TABLE dim_compte (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_compte varchar(20) NOT NULL,
      libelle varchar(200) NOT NULL,
      classe varchar(50) NOT NULL DEFAULT '6'
    )
  `);
  return ds;
}

describe('Migration RenommerComptesTest1779200000070', () => {
  let dataSource: DataSource;
  let migration: RenommerComptesTest1779200000070;
  let queryRunner: QueryRunner;

  beforeEach(async () => {
    dataSource = await createDataSource();
    migration = new RenommerComptesTest1779200000070();
    queryRunner = dataSource.createQueryRunner();
  });

  afterEach(async () => {
    await queryRunner.release();
    await dataSource.destroy();
  });

  it('renomme 611100 et 611400 quand les libellés "(test)" sont présents', async () => {
    await dataSource.query(
      `INSERT INTO dim_compte (code_compte, libelle) VALUES
        ('611100', 'Salaires bruts (test upsert manuel)'),
        ('611400', 'Indemnites de transport (test)'),
        ('611200', 'Primes et bonus')`,
    );
    await migration.up(queryRunner);
    const rows = (await dataSource.query(
      `SELECT code_compte, libelle FROM dim_compte
        WHERE code_compte IN ('611100', '611400', '611200')
        ORDER BY code_compte`,
    )) as Array<{ code_compte: string; libelle: string }>;
    expect(rows).toEqual([
      { code_compte: '611100', libelle: 'Salaires bruts' },
      { code_compte: '611200', libelle: 'Primes et bonus' }, // intact
      { code_compte: '611400', libelle: 'Indemnités de transport' },
    ]);
  });

  it('idempotente : 2e exécution sans effet (les libellés sont déjà corrigés)', async () => {
    await dataSource.query(
      `INSERT INTO dim_compte (code_compte, libelle) VALUES
        ('611100', 'Salaires bruts (test upsert manuel)'),
        ('611400', 'Indemnites de transport (test)')`,
    );
    await migration.up(queryRunner);
    // 2e appel — les libellés sont déjà bons, le WHERE ne match plus
    await migration.up(queryRunner);
    const rows = (await dataSource.query(
      `SELECT code_compte, libelle FROM dim_compte ORDER BY code_compte`,
    )) as Array<{ code_compte: string; libelle: string }>;
    expect(rows).toEqual([
      { code_compte: '611100', libelle: 'Salaires bruts' },
      { code_compte: '611400', libelle: 'Indemnités de transport' },
    ]);
  });

  it('aucun compte concerné en base → UPDATE ne plante pas', async () => {
    // Base sans 611100 ni 611400 (env vierge).
    await dataSource.query(
      `INSERT INTO dim_compte (code_compte, libelle) VALUES
        ('700000', 'Produits divers')`,
    );
    await expect(migration.up(queryRunner)).resolves.not.toThrow();
    const rows = (await dataSource.query(
      `SELECT COUNT(*)::int AS n FROM dim_compte`,
    )) as Array<{ n: number }>;
    expect(rows[0]!.n).toBe(1); // intact
  });
});
