/**
 * Tests pg-mem de la migration 1779200000110 (Lot 4.1-fix3) :
 *  - 4 rôles métier créés (SAISISSEUR / VALIDATEUR / PUBLICATEUR /
 *    AUDITEUR) avec leurs permissions exactes
 *  - 6 personas BSIC basculés sur leurs nouveaux rôles
 *  - Idempotence (rejouable sans doublon)
 *  - Admin et lecteur globaux NE sont PAS touchés
 */
import { DataType, IMemoryDb, newDb } from 'pg-mem';
import { DataSource, type QueryRunner } from 'typeorm';

import { CreerRolesMetierEtBasculePersonasBSIC1779200000110 } from '../1779200000110-CreerRolesMetierEtBasculePersonasBSIC';

function buildMemDb(): IMemoryDb {
  const db = newDb({ autoCreateForeignKeyIndices: true });
  db.public.registerFunction({
    name: 'current_database',
    args: [],
    returns: DataType.text,
    implementation: () => 'test',
  });
  db.public.registerFunction({
    name: 'version',
    args: [],
    returns: DataType.text,
    implementation: () => 'PostgreSQL 15 (pg-mem)',
  });
  return db;
}

const PERMISSIONS = [
  ['BUDGET.LIRE', 'BUDGET'],
  ['BUDGET.SAISIR', 'BUDGET'],
  ['BUDGET.SOUMETTRE', 'BUDGET'],
  ['BUDGET.VALIDER', 'BUDGET'],
  ['BUDGET.PUBLIER', 'BUDGET'],
  ['BUDGET.SUPPRIMER', 'BUDGET'],
  ['REFERENTIEL.LIRE', 'REFERENTIEL'],
  ['CONFIGURATION.LIRE', 'CONFIGURATION'],
  ['USER.LIRE', 'USER'],
  ['ROLE.LIRE', 'ROLE'],
  ['AUDIT.LIRE', 'AUDIT'],
] as const;

const PERSONAS_EMAILS = [
  'dir.retail@miznas.local',
  'adj.retail@miznas.local',
  'dir.corporate@miznas.local',
  'controleur.gestion@miznas.local',
  'auditeur@miznas.local',
  'dga.exploitation@miznas.local',
];

async function createDataSource(): Promise<DataSource> {
  const db = buildMemDb();
  const ds = db.adapters.createTypeormDataSource({
    type: 'postgres',
    entities: [],
    synchronize: false,
  }) as DataSource;
  await ds.initialize();

  // Schéma minimal nécessaire à la migration
  await ds.query(`
    CREATE TABLE "user" (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email varchar(255) UNIQUE NOT NULL,
      mot_de_passe_hash varchar(255) NOT NULL,
      nom varchar(100) NOT NULL,
      prenom varchar(100) NOT NULL,
      est_actif boolean NOT NULL DEFAULT true,
      utilisateur_creation varchar(255) NOT NULL
    )
  `);
  await ds.query(`
    CREATE TABLE ref_role (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_role varchar(50) UNIQUE NOT NULL,
      libelle varchar(200) NOT NULL,
      description text,
      est_actif boolean NOT NULL DEFAULT true,
      utilisateur_creation varchar(255) NOT NULL DEFAULT 'system'
    )
  `);
  await ds.query(`
    CREATE TABLE ref_permission (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_permission varchar(100) UNIQUE NOT NULL,
      libelle varchar(200) NOT NULL,
      module varchar(50) NOT NULL,
      utilisateur_creation varchar(255) NOT NULL DEFAULT 'system'
    )
  `);
  await ds.query(`
    CREATE TABLE bridge_role_permission (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      fk_role bigint NOT NULL,
      fk_permission bigint NOT NULL
    )
  `);
  await ds.query(`
    CREATE TABLE bridge_user_role (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      fk_user bigint NOT NULL,
      fk_role bigint NOT NULL,
      perimetre_type varchar(50) NULL,
      perimetre_id bigint NULL,
      est_actif boolean NOT NULL DEFAULT true,
      date_creation timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
      utilisateur_creation varchar(255) NOT NULL DEFAULT 'system',
      date_modification timestamp NULL,
      utilisateur_modification varchar(255) NULL
    )
  `);

  // Seed initial : LECTEUR + ADMIN + 16 permissions + bridges
  await ds.query(
    `INSERT INTO ref_role (code_role, libelle, est_actif)
     VALUES ('ADMIN','Administrateur système', true),
            ('LECTEUR','Lecteur', true)`,
  );
  for (const [code, mod] of PERMISSIONS) {
    await ds.query(
      `INSERT INTO ref_permission (code_permission, libelle, module)
       VALUES ($1, $1, $2)`,
      [code, mod],
    );
  }
  // Seed 8 users (admin, lecteur, 6 personas)
  await ds.query(
    `INSERT INTO "user" (email, mot_de_passe_hash, nom, prenom, est_actif, utilisateur_creation)
     VALUES ('admin@miznas.local','h','Admin','X', true, 'system'),
            ('lecteur@miznas.local','h','Lecteur','X', true, 'system'),
            ('dir.retail@miznas.local','h','Directeur Retail','Amadou', true, 'system'),
            ('adj.retail@miznas.local','h','Adjoint Retail','Fatima', true, 'system'),
            ('dir.corporate@miznas.local','h','Directeur Corporate','Ibrahim', true, 'system'),
            ('controleur.gestion@miznas.local','h','CDG','Aïcha', true, 'system'),
            ('auditeur@miznas.local','h','Auditeur','Moussa', true, 'system'),
            ('dga.exploitation@miznas.local','h','DGA','Salif', true, 'system')`,
  );
  // Bridges existants : admin → ADMIN ; lecteur + 6 personas → LECTEUR/global
  // Résolution des ids côté JS (pg-mem ne supporte pas les
  // sous-SELECT scalaires dans tous les contextes).
  async function ridOf(code: string): Promise<string> {
    const r = (await ds.query(
      `SELECT "id" FROM ref_role WHERE code_role = $1`,
      [code],
    )) as Array<{ id: string }>;
    return r[0]!.id;
  }
  async function uidOf(email: string): Promise<string> {
    const u = (await ds.query(
      `SELECT "id" FROM "user" WHERE email = $1`,
      [email],
    )) as Array<{ id: string }>;
    return u[0]!.id;
  }
  const adminRoleId = await ridOf('ADMIN');
  const lecteurRoleId = await ridOf('LECTEUR');
  await ds.query(
    `INSERT INTO bridge_user_role (fk_user, fk_role, perimetre_type, est_actif)
     VALUES ($1::bigint, $2::bigint, 'global', true)`,
    [await uidOf('admin@miznas.local'), adminRoleId],
  );
  for (const email of ['lecteur@miznas.local', ...PERSONAS_EMAILS]) {
    await ds.query(
      `INSERT INTO bridge_user_role (fk_user, fk_role, perimetre_type, est_actif)
       VALUES ($1::bigint, $2::bigint, 'global', true)`,
      [await uidOf(email), lecteurRoleId],
    );
  }
  return ds;
}

describe('Migration CreerRolesMetierEtBasculePersonasBSIC1779200000110', () => {
  let ds: DataSource;
  let migration: CreerRolesMetierEtBasculePersonasBSIC1779200000110;
  let q: QueryRunner;

  beforeEach(async () => {
    ds = await createDataSource();
    migration = new CreerRolesMetierEtBasculePersonasBSIC1779200000110();
    q = ds.createQueryRunner();
  });

  afterEach(async () => {
    await q.release();
    await ds.destroy();
  });

  // ─── Section 1 : création des rôles ─────────────────────────────

  it('crée les 4 rôles métier dans ref_role', async () => {
    await migration.up(q);
    const rows = (await ds.query(
      `SELECT code_role FROM ref_role WHERE est_actif = true ORDER BY code_role`,
    )) as Array<{ code_role: string }>;
    const codes = rows.map((r) => r.code_role);
    expect(codes).toContain('SAISISSEUR');
    expect(codes).toContain('VALIDATEUR');
    expect(codes).toContain('PUBLICATEUR');
    expect(codes).toContain('AUDITEUR');
    // ADMIN et LECTEUR sont préservés
    expect(codes).toContain('ADMIN');
    expect(codes).toContain('LECTEUR');
  });

  // ─── Section 2 : permissions par rôle ────────────────────────────

  async function permsParRole(role: string): Promise<string[]> {
    const rows = (await ds.query(
      `SELECT p.code_permission AS code
         FROM bridge_role_permission brp
         JOIN ref_role r ON r.id = brp.fk_role
         JOIN ref_permission p ON p.id = brp.fk_permission
        WHERE r.code_role = $1
        ORDER BY p.code_permission`,
      [role],
    )) as Array<{ code: string }>;
    return rows.map((r) => r.code);
  }

  it('SAISISSEUR a exactement 5 permissions (BUDGET.LIRE/SAISIR/SOUMETTRE + REFERENTIEL/CONFIGURATION)', async () => {
    await migration.up(q);
    const perms = await permsParRole('SAISISSEUR');
    expect(perms).toHaveLength(5);
    expect(perms).toEqual(
      [
        'BUDGET.LIRE',
        'BUDGET.SAISIR',
        'BUDGET.SOUMETTRE',
        'CONFIGURATION.LIRE',
        'REFERENTIEL.LIRE',
      ].sort(),
    );
    // Anti-régression : ne doit PAS avoir BUDGET.VALIDER ni BUDGET.PUBLIER
    expect(perms).not.toContain('BUDGET.VALIDER');
    expect(perms).not.toContain('BUDGET.PUBLIER');
  });

  it('VALIDATEUR a exactement 6 permissions dont AUDIT.LIRE et BUDGET.VALIDER', async () => {
    await migration.up(q);
    const perms = await permsParRole('VALIDATEUR');
    expect(perms).toHaveLength(6);
    expect(perms).toContain('BUDGET.VALIDER');
    expect(perms).toContain('AUDIT.LIRE');
    // Séparation des tâches : pas de BUDGET.SAISIR ni BUDGET.SOUMETTRE
    expect(perms).not.toContain('BUDGET.SAISIR');
    expect(perms).not.toContain('BUDGET.SOUMETTRE');
    expect(perms).not.toContain('BUDGET.PUBLIER');
  });

  it('PUBLICATEUR a exactement 6 permissions dont BUDGET.PUBLIER, SANS BUDGET.VALIDER', async () => {
    await migration.up(q);
    const perms = await permsParRole('PUBLICATEUR');
    expect(perms).toHaveLength(6);
    expect(perms).toContain('BUDGET.PUBLIER');
    expect(perms).toContain('AUDIT.LIRE');
    // Séparation des tâches : pas de BUDGET.VALIDER (cf. arbitrage Phase 1)
    expect(perms).not.toContain('BUDGET.VALIDER');
    expect(perms).not.toContain('BUDGET.SAISIR');
  });

  it('AUDITEUR a exactement 6 permissions de lecture seule', async () => {
    await migration.up(q);
    const perms = await permsParRole('AUDITEUR');
    expect(perms).toHaveLength(6);
    expect(perms).toEqual(
      [
        'AUDIT.LIRE',
        'BUDGET.LIRE',
        'CONFIGURATION.LIRE',
        'REFERENTIEL.LIRE',
        'ROLE.LIRE',
        'USER.LIRE',
      ].sort(),
    );
    // Aucun droit d'écriture
    expect(perms).not.toContain('BUDGET.SAISIR');
    expect(perms).not.toContain('BUDGET.VALIDER');
    expect(perms).not.toContain('BUDGET.PUBLIER');
  });

  // ─── Section 3 : bascule des personas ────────────────────────────

  async function roleActifDuUser(email: string): Promise<string | null> {
    const rows = (await ds.query(
      `SELECT r.code_role
         FROM bridge_user_role bur
         JOIN "user" u ON u.id = bur.fk_user
         JOIN ref_role r ON r.id = bur.fk_role
        WHERE u.email = $1 AND bur.est_actif = true`,
      [email],
    )) as Array<{ code_role: string }>;
    return rows.length === 0 ? null : rows[0]!.code_role;
  }

  it('dir.retail bascule sur VALIDATEUR (et plus LECTEUR)', async () => {
    await migration.up(q);
    expect(await roleActifDuUser('dir.retail@miznas.local')).toBe(
      'VALIDATEUR',
    );
    // Ancien bridge LECTEUR désactivé
    const ancien = (await ds.query(
      `SELECT bur.est_actif
         FROM bridge_user_role bur
         JOIN "user" u ON u.id = bur.fk_user
         JOIN ref_role r ON r.id = bur.fk_role
        WHERE u.email = 'dir.retail@miznas.local'
          AND r.code_role = 'LECTEUR'`,
    )) as Array<{ est_actif: boolean }>;
    expect(ancien[0]!.est_actif).toBe(false);
  });

  it('adj.retail bascule sur SAISISSEUR', async () => {
    await migration.up(q);
    expect(await roleActifDuUser('adj.retail@miznas.local')).toBe(
      'SAISISSEUR',
    );
  });

  it('dga.exploitation bascule sur PUBLICATEUR', async () => {
    await migration.up(q);
    expect(await roleActifDuUser('dga.exploitation@miznas.local')).toBe(
      'PUBLICATEUR',
    );
  });

  it('auditeur bascule sur AUDITEUR', async () => {
    await migration.up(q);
    expect(await roleActifDuUser('auditeur@miznas.local')).toBe('AUDITEUR');
  });

  it('controleur.gestion bascule sur VALIDATEUR', async () => {
    await migration.up(q);
    expect(
      await roleActifDuUser('controleur.gestion@miznas.local'),
    ).toBe('VALIDATEUR');
  });

  it('admin et lecteur globaux NE sont PAS touchés', async () => {
    await migration.up(q);
    expect(await roleActifDuUser('admin@miznas.local')).toBe('ADMIN');
    expect(await roleActifDuUser('lecteur@miznas.local')).toBe('LECTEUR');
  });

  // ─── Idempotence ─────────────────────────────────────────────────

  it('idempotente : 2× up sans doublon de rôles ni de bridges', async () => {
    await migration.up(q);
    await migration.up(q); // 2e exécution

    // Pas de doublon de rôle
    const rolesCount = (await ds.query(
      `SELECT COUNT(*)::int AS n FROM ref_role WHERE code_role IN
        ('SAISISSEUR','VALIDATEUR','PUBLICATEUR','AUDITEUR')`,
    )) as Array<{ n: number }>;
    expect(rolesCount[0]!.n).toBe(4);

    // Pas de doublon de bridge_role_permission (cumul attendu :
    // 5 + 6 + 6 + 6 = 23)
    const brpCount = (await ds.query(
      `SELECT COUNT(*)::int AS n FROM bridge_role_permission brp
         JOIN ref_role r ON r.id = brp.fk_role
        WHERE r.code_role IN
          ('SAISISSEUR','VALIDATEUR','PUBLICATEUR','AUDITEUR')`,
    )) as Array<{ n: number }>;
    expect(brpCount[0]!.n).toBe(23);

    // Pas de doublon de bridge_user_role actif pour les personas
    const burActifCount = (await ds.query(
      `SELECT COUNT(*)::int AS n FROM bridge_user_role bur
         JOIN "user" u ON u.id = bur.fk_user
        WHERE u.email IN ($1,$2,$3,$4,$5,$6) AND bur.est_actif = true`,
      PERSONAS_EMAILS,
    )) as Array<{ n: number }>;
    expect(burActifCount[0]!.n).toBe(6); // 1 actif par persona, pas 12
  });
});
