/**
 * Test de la migration 1779200000060 — vérifie que les 6 codes
 * type_action manquants sont bien insérés et que le ON CONFLICT
 * rend la migration idempotente.
 */
import { DataType, IMemoryDb, newDb } from 'pg-mem';
import { DataSource, type QueryRunner } from 'typeorm';

import { AddRefTypeActionWorkflowAndIndicateurs1779200000060 } from '../1779200000060-AddRefTypeActionWorkflowAndIndicateurs';

function buildMemDb(): IMemoryDb {
  const db = newDb({ autoCreateForeignKeyIndices: true });
  db.public.registerFunction({
    name: 'current_database',
    args: [],
    returns: DataType.text,
    implementation: () => 'test',
  });
  db.public.registerFunction({
    name: 'version',
    args: [],
    returns: DataType.text,
    implementation: () => 'PostgreSQL 15 (pg-mem)',
  });
  return db;
}

async function createDataSource(): Promise<DataSource> {
  const db = buildMemDb();
  const ds = db.adapters.createTypeormDataSource({
    type: 'postgres',
    entities: [],
    synchronize: false,
  }) as DataSource;
  await ds.initialize();

  // Schéma minimal de ref_type_action_audit (créé par la migration
  // 1779000000130 en prod). On reproduit juste les colonnes utiles.
  await ds.query(`
    CREATE TABLE ref_type_action_audit (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code varchar(50) UNIQUE NOT NULL,
      libelle varchar(200) NOT NULL,
      description text,
      ordre int NOT NULL,
      est_systeme boolean NOT NULL DEFAULT false,
      est_actif boolean NOT NULL DEFAULT true,
      utilisateur_creation varchar(255) NOT NULL
    )
  `);
  return ds;
}

const NOUVEAUX_CODES = [
  'SOUMETTRE_BUDGET',
  'VALIDER_BUDGET',
  'REJETER_BUDGET',
  'PUBLIER_BUDGET',
  'RECALCUL_INDICATEURS',
  'IMPORT_BUDGET_BULK',
];

describe('Migration AddRefTypeActionWorkflowAndIndicateurs', () => {
  let dataSource: DataSource;
  let migration: AddRefTypeActionWorkflowAndIndicateurs1779200000060;
  let queryRunner: QueryRunner;

  beforeEach(async () => {
    dataSource = await createDataSource();
    migration = new AddRefTypeActionWorkflowAndIndicateurs1779200000060();
    queryRunner = dataSource.createQueryRunner();
  });

  afterEach(async () => {
    await queryRunner.release();
    await dataSource.destroy();
  });

  it('migration up insère les 6 codes type_action manquants', async () => {
    await migration.up(queryRunner);
    const rows = (await dataSource.query(
      `SELECT code FROM ref_type_action_audit ORDER BY code`,
    )) as Array<{ code: string }>;
    const codes = rows.map((r) => r.code);
    for (const c of NOUVEAUX_CODES) {
      expect(codes).toContain(c);
    }
  });

  it("migration up est idempotente (2x up sans erreur, pas de doublon)", async () => {
    await migration.up(queryRunner);
    await migration.up(queryRunner); // 2e appel — ON CONFLICT DO NOTHING
    const count = (await dataSource.query(
      `SELECT COUNT(*)::int AS n FROM ref_type_action_audit
        WHERE code IN ('SOUMETTRE_BUDGET','VALIDER_BUDGET',
          'REJETER_BUDGET','PUBLIER_BUDGET','RECALCUL_INDICATEURS',
          'IMPORT_BUDGET_BULK')`,
    )) as Array<{ n: number }>;
    expect(count[0]!.n).toBe(6);
  });

  it('chaque code a libelle, description et ordre renseignés', async () => {
    await migration.up(queryRunner);
    const placeholders = NOUVEAUX_CODES.map((_, i) => `$${i + 1}`).join(',');
    const rows = (await dataSource.query(
      `SELECT code, libelle, description, ordre, est_systeme, est_actif
         FROM ref_type_action_audit
        WHERE code IN (${placeholders})`,
      NOUVEAUX_CODES,
    )) as Array<{
      code: string;
      libelle: string;
      description: string;
      ordre: number;
      est_systeme: boolean;
      est_actif: boolean;
    }>;
    expect(rows).toHaveLength(6);
    for (const r of rows) {
      expect(r.libelle).toBeTruthy();
      expect(r.description).toBeTruthy();
      expect(r.ordre).toBeGreaterThan(0);
      expect(r.est_systeme).toBe(true);
      expect(r.est_actif).toBe(true);
    }
  });
});
