/**
 * Tests pg-mem de la migration 1779200000520 (fix RBAC workflow).
 *
 * Reproduit l'état cassé en prod (rôles métier sans les permissions
 * workflow, car la 110 les a skippées faute de permission préexistante)
 * et vérifie que la migration répare le bridge + reste idempotente.
 */
import { DataType, IMemoryDb, newDb } from 'pg-mem';
import { DataSource } from 'typeorm';

import { FixRbacMetierWorkflowPermissions1779200000520 } from '../1779200000520-FixRbacMetierWorkflowPermissions';

function buildMemDb(): IMemoryDb {
  const db = newDb({ autoCreateForeignKeyIndices: true });
  db.public.registerFunction({
    name: 'current_database',
    args: [],
    returns: DataType.text,
    implementation: () => 'test',
  });
  db.public.registerFunction({
    name: 'version',
    args: [],
    returns: DataType.text,
    implementation: () => 'PostgreSQL 15 (pg-mem)',
  });
  return db;
}

async function createDataSource(): Promise<DataSource> {
  const db = buildMemDb();
  const ds = db.adapters.createTypeormDataSource({
    type: 'postgres',
    entities: [],
    synchronize: false,
  }) as DataSource;
  await ds.initialize();
  await ds.query(`
    CREATE TABLE ref_role (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_role varchar(50) UNIQUE NOT NULL,
      libelle varchar(200) NOT NULL,
      description text,
      est_actif boolean NOT NULL DEFAULT true,
      utilisateur_creation varchar(255) NOT NULL DEFAULT 'system'
    )
  `);
  await ds.query(`
    CREATE TABLE ref_permission (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_permission varchar(100) UNIQUE NOT NULL,
      libelle varchar(200) NOT NULL,
      description text,
      module varchar(50) NOT NULL,
      utilisateur_creation varchar(255) NOT NULL DEFAULT 'system'
    )
  `);
  await ds.query(`
    CREATE TABLE bridge_role_permission (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      fk_role bigint NOT NULL,
      fk_permission bigint NOT NULL
    )
  `);
  return ds;
}

async function aLePermission(
  ds: DataSource,
  role: string,
  perm: string,
): Promise<number> {
  const r = (await ds.query(
    `SELECT COUNT(*)::int AS n
       FROM bridge_role_permission brp
       JOIN ref_role r ON r.id = brp.fk_role
       JOIN ref_permission p ON p.id = brp.fk_permission
      WHERE r.code_role = $1 AND p.code_permission = $2`,
    [role, perm],
  )) as Array<{ n: number }>;
  return r[0]!.n;
}

describe('Migration 520 — fix RBAC workflow', () => {
  let ds: DataSource;

  beforeEach(async () => {
    ds = await createDataSource();
    // Rôles métier présents (créés par la 110).
    for (const role of ['SAISISSEUR', 'VALIDATEUR', 'PUBLICATEUR']) {
      await ds.query(
        `INSERT INTO ref_role (code_role, libelle) VALUES ($1, $1)`,
        [role],
      );
    }
    // Permissions de base présentes, MAIS workflow ABSENTES (état cassé).
    for (const code of ['BUDGET.LIRE', 'BUDGET.SAISIR']) {
      await ds.query(
        `INSERT INTO ref_permission (code_permission, libelle, module) VALUES ($1,$1,'BUDGET')`,
        [code],
      );
    }
  });

  afterEach(async () => {
    await ds.destroy();
  });

  async function run(): Promise<void> {
    const qr = ds.createQueryRunner();
    await new FixRbacMetierWorkflowPermissions1779200000520().up(qr);
    await qr.release();
  }

  it('état cassé : SAISISSEUR n’a pas BUDGET.SOUMETTRE avant', async () => {
    expect(await aLePermission(ds, 'SAISISSEUR', 'BUDGET.SOUMETTRE')).toBe(0);
  });

  it('répare les 3 bridges workflow (insère permission + bridge)', async () => {
    await run();
    expect(await aLePermission(ds, 'SAISISSEUR', 'BUDGET.SOUMETTRE')).toBe(1);
    expect(await aLePermission(ds, 'VALIDATEUR', 'BUDGET.VALIDER')).toBe(1);
    expect(await aLePermission(ds, 'PUBLICATEUR', 'BUDGET.PUBLIER')).toBe(1);
  });

  it('idempotent : rejouable sans doublon', async () => {
    await run();
    await run();
    expect(await aLePermission(ds, 'SAISISSEUR', 'BUDGET.SOUMETTRE')).toBe(1);
    const perms = (await ds.query(
      `SELECT COUNT(*)::int AS n FROM ref_permission WHERE code_permission='BUDGET.SOUMETTRE'`,
    )) as Array<{ n: number }>;
    expect(perms[0]!.n).toBe(1);
  });

  it('n’écrase pas un bridge déjà présent (permission préexistante)', async () => {
    // Simule le cas « sain » : permission + bridge déjà là.
    await ds.query(
      `INSERT INTO ref_permission (code_permission, libelle, module) VALUES ('BUDGET.VALIDER','x','BUDGET')`,
    );
    await ds.query(
      `INSERT INTO bridge_role_permission (fk_role, fk_permission)
       SELECT r.id, p.id FROM ref_role r, ref_permission p
       WHERE r.code_role='VALIDATEUR' AND p.code_permission='BUDGET.VALIDER'`,
    );
    await run();
    expect(await aLePermission(ds, 'VALIDATEUR', 'BUDGET.VALIDER')).toBe(1);
  });
});
