/**
 * Test de la migration 1779200000090 (Lot 4.1-fix.B) — vérifie que
 * les 6 personas BSIC sont créés, qu'un bridge_user_role LECTEUR
 * leur est attribué, et que la migration est idempotente.
 */
import { DataType, IMemoryDb, newDb } from 'pg-mem';
import { DataSource, type QueryRunner } from 'typeorm';

import { AjouterPersonasBSIC1779200000090 } from '../1779200000090-AjouterPersonasBSIC';

function buildMemDb(): IMemoryDb {
  const db = newDb({ autoCreateForeignKeyIndices: true });
  db.public.registerFunction({
    name: 'current_database',
    args: [],
    returns: DataType.text,
    implementation: () => 'test',
  });
  db.public.registerFunction({
    name: 'version',
    args: [],
    returns: DataType.text,
    implementation: () => 'PostgreSQL 15 (pg-mem)',
  });
  return db;
}

async function createDataSource(): Promise<DataSource> {
  const db = buildMemDb();
  const ds = db.adapters.createTypeormDataSource({
    type: 'postgres',
    entities: [],
    synchronize: false,
  }) as DataSource;
  await ds.initialize();

  // Schéma minimal "user" + ref_role + bridge_user_role
  await ds.query(`
    CREATE TABLE "user" (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email varchar(255) UNIQUE NOT NULL,
      mot_de_passe_hash varchar(255) NOT NULL,
      nom varchar(100) NOT NULL,
      prenom varchar(100) NOT NULL,
      est_actif boolean NOT NULL DEFAULT true,
      utilisateur_creation varchar(255) NOT NULL
    )
  `);
  await ds.query(`
    CREATE TABLE ref_role (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_role varchar(50) UNIQUE NOT NULL,
      libelle varchar(200) NOT NULL,
      est_actif boolean NOT NULL DEFAULT true
    )
  `);
  await ds.query(`
    CREATE TABLE bridge_user_role (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      fk_user bigint NOT NULL,
      fk_role bigint NOT NULL,
      perimetre_type varchar(50) NULL,
      perimetre_id bigint NULL,
      est_actif boolean NOT NULL DEFAULT true,
      utilisateur_creation varchar(255) NOT NULL
    )
  `);
  // Seed du rôle LECTEUR (prérequis Lot 1)
  await ds.query(
    `INSERT INTO ref_role (code_role, libelle) VALUES ('LECTEUR', 'Lecteur')`,
  );
  return ds;
}

const PERSONAS_EMAILS = [
  'dir.retail@miznas.local',
  'adj.retail@miznas.local',
  'dir.corporate@miznas.local',
  'controleur.gestion@miznas.local',
  'auditeur@miznas.local',
  'dga.exploitation@miznas.local',
];

describe('Migration AjouterPersonasBSIC1779200000090', () => {
  let dataSource: DataSource;
  let migration: AjouterPersonasBSIC1779200000090;
  let queryRunner: QueryRunner;

  beforeEach(async () => {
    dataSource = await createDataSource();
    migration = new AjouterPersonasBSIC1779200000090();
    queryRunner = dataSource.createQueryRunner();
  });

  afterEach(async () => {
    await queryRunner.release();
    await dataSource.destroy();
  });

  it("crée les 6 personas avec est_actif=true", async () => {
    await migration.up(queryRunner);
    const placeholders = PERSONAS_EMAILS.map((_, i) => `$${i + 1}`).join(',');
    const rows = (await dataSource.query(
      `SELECT email, est_actif FROM "user" WHERE email IN (${placeholders})`,
      PERSONAS_EMAILS,
    )) as Array<{ email: string; est_actif: boolean }>;
    expect(rows).toHaveLength(6);
    for (const r of rows) {
      expect(r.est_actif).toBe(true);
    }
  });

  it('crée un bridge_user_role LECTEUR pour chaque persona', async () => {
    await migration.up(queryRunner);
    const rows = (await dataSource.query(
      `SELECT u.email, r.code_role, bur.est_actif
         FROM bridge_user_role bur
         JOIN "user" u ON u.id = bur.fk_user
         JOIN ref_role r ON r.id = bur.fk_role
        WHERE u.email LIKE '%@miznas.local'
          AND u.email != 'admin@miznas.local'
          AND u.email != 'lecteur@miznas.local'`,
    )) as Array<{ email: string; code_role: string; est_actif: boolean }>;
    expect(rows).toHaveLength(6);
    for (const r of rows) {
      expect(r.code_role).toBe('LECTEUR');
      expect(r.est_actif).toBe(true);
    }
  });

  it('mot de passe bcrypt cost 10 ($2b$10$...)', async () => {
    await migration.up(queryRunner);
    const rows = (await dataSource.query(
      `SELECT mot_de_passe_hash FROM "user" WHERE email = $1`,
      ['dir.retail@miznas.local'],
    )) as Array<{ mot_de_passe_hash: string }>;
    expect(rows[0]!.mot_de_passe_hash).toMatch(/^\$2b\$10\$/);
  });

  it("idempotente : 2× up sans doublons", async () => {
    await migration.up(queryRunner);
    await migration.up(queryRunner); // 2e appel
    const placeholders = PERSONAS_EMAILS.map((_, i) => `$${i + 1}`).join(',');
    const userCount = (await dataSource.query(
      `SELECT COUNT(*)::int AS n FROM "user" WHERE email IN (${placeholders})`,
      PERSONAS_EMAILS,
    )) as Array<{ n: number }>;
    expect(userCount[0]!.n).toBe(6);
    // 1 bridge par persona, pas 2.
    const bridgeCount = (await dataSource.query(
      `SELECT COUNT(*)::int AS n FROM bridge_user_role bur
         JOIN "user" u ON u.id = bur.fk_user
        WHERE u.email IN (${placeholders})`,
      PERSONAS_EMAILS,
    )) as Array<{ n: number }>;
    expect(bridgeCount[0]!.n).toBe(6);
  });
});
