/**
 * Tests unitaires BudgetImportService (Lot 3.7) via pg-mem.
 *
 * Approche : on monte un schéma simplifié avec uniquement les tables
 * et colonnes utiles à l'import (dim_temps, dim_compte, dim_cr,
 * dim_ligne_metier, dim_produit, dim_segment, dim_devise, dim_version,
 * dim_scenario, fait_budget). Les FK et relations TypeORM ne sont pas
 * matérialisées en pg-mem — on les remplace par des INSERT en SQL brut
 * et un index UNIQUE composite sur fait_budget.
 *
 * Fixtures : générées inline en mémoire (Buffer.from pour CSV,
 * exceljs pour XLSX) — pas de fichiers sur disque.
 */
import {
  BadRequestException,
  ConflictException,
} from '@nestjs/common';
import ExcelJS from 'exceljs';
import { DataType, IMemoryDb, newDb } from 'pg-mem';
import { DataSource } from 'typeorm';

import { AuditLog } from '../../audit/entities/audit-log.entity';
import { AuditService } from '../../audit/audit.service';
import { BudgetImportService } from './budget-import.service';
import { PerimetreService } from './perimetre.service';

// ─── Mock perimetre ──────────────────────────────────────────────────

interface PerimetreMock {
  setReturnValue: (v: string[] | null) => void;
  getCrAutorisesPourUser: (uid: string) => Promise<string[] | null>;
}
function makePerimetreMock(): PerimetreMock {
  let value: string[] | null = null;
  return {
    setReturnValue: (v) => {
      value = v;
    },
    getCrAutorisesPourUser: async () => value,
  };
}

// ─── DB setup ────────────────────────────────────────────────────────

function buildMemDb(): IMemoryDb {
  const db = newDb({ autoCreateForeignKeyIndices: true });
  db.public.registerFunction({
    name: 'current_database',
    args: [],
    returns: DataType.text,
    implementation: () => 'test',
  });
  db.public.registerFunction({
    name: 'version',
    args: [],
    returns: DataType.text,
    implementation: () => 'PostgreSQL 15 (pg-mem)',
  });
  return db;
}

async function createDataSource(): Promise<DataSource> {
  const db = buildMemDb();
  const ds: DataSource = db.adapters.createTypeormDataSource({
    type: 'postgres',
    entities: [AuditLog],
    synchronize: true,
  });
  await ds.initialize();

  // Tables minimales — uniquement les colonnes consommées par le service.
  await ds.query(`
    CREATE TABLE dim_devise (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_iso varchar(3) NOT NULL
    )`);
  await ds.query(`
    CREATE TABLE dim_produit (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_produit varchar(50) NOT NULL,
      version_courante boolean DEFAULT true,
      est_actif boolean DEFAULT true,
      niveau int DEFAULT 1
    )`);
  await ds.query(`
    CREATE TABLE dim_segment (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_segment varchar(50) NOT NULL,
      version_courante boolean DEFAULT true,
      est_actif boolean DEFAULT true
    )`);
  await ds.query(`
    CREATE TABLE dim_centre_responsabilite (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_cr varchar(50) NOT NULL,
      libelle varchar(200) NOT NULL,
      fk_structure bigint NOT NULL,
      version_courante boolean DEFAULT true,
      est_actif boolean DEFAULT true
    )`);
  await ds.query(`
    CREATE TABLE dim_compte (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_compte varchar(20) NOT NULL,
      classe varchar(50) NOT NULL,
      est_compte_collectif boolean DEFAULT false,
      version_courante boolean DEFAULT true
    )`);
  await ds.query(`
    CREATE TABLE dim_ligne_metier (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_ligne_metier varchar(50) NOT NULL,
      version_courante boolean DEFAULT true
    )`);
  await ds.query(`
    CREATE TABLE dim_temps (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      date date NOT NULL UNIQUE,
      jour int NOT NULL,
      mois int NOT NULL,
      annee int NOT NULL
    )`);
  await ds.query(`
    CREATE TABLE dim_version (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_version varchar(50) NOT NULL,
      libelle varchar(200) NOT NULL,
      statut varchar(20) NOT NULL DEFAULT 'ouvert'
    )`);
  await ds.query(`
    CREATE TABLE dim_scenario (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_scenario varchar(50) NOT NULL
    )`);
  await ds.query(`
    CREATE TABLE fait_budget (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      fk_temps bigint NOT NULL,
      fk_compte bigint NOT NULL,
      fk_structure bigint NOT NULL,
      fk_centre bigint NOT NULL,
      fk_ligne_metier bigint NOT NULL,
      fk_produit bigint NOT NULL,
      fk_segment bigint NOT NULL,
      fk_devise bigint NOT NULL,
      fk_version bigint NOT NULL,
      fk_scenario bigint NOT NULL,
      montant_devise numeric(20,2) NOT NULL,
      montant_fcfa numeric(20,2) NOT NULL,
      taux_change_applique numeric(8,5) NOT NULL,
      mode_saisie varchar(20) NOT NULL DEFAULT 'MONTANT',
      encours_moyen numeric(20,2) NULL,
      tie numeric(8,5) NULL,
      commentaire text NULL,
      utilisateur_creation varchar(255) NOT NULL,
      date_modification timestamp NULL,
      utilisateur_modification varchar(255) NULL,
      CONSTRAINT uq_fait_budget_grain UNIQUE
        (fk_temps, fk_compte, fk_structure, fk_centre, fk_ligne_metier,
         fk_produit, fk_segment, fk_devise, fk_version, fk_scenario)
    )`);

  return ds;
}

interface SeedIds {
  devise: string;
  produit: string;
  segment: string;
  crCiv: string;
  crBfa: string;
  structureCiv: string;
  structureBfa: string;
  compte611: string;
  compte76A: string;
  compte67A: string;
  compteAgrege: string;
  ligneMetier: string;
  versionId: string;
  scenarioId: string;
  tempsJanvier: string;
  tempsFevrier: string;
}

async function seedAll(ds: DataSource): Promise<SeedIds> {
  await ds.query(`INSERT INTO dim_devise (code_iso) VALUES ('XOF')`);
  await ds.query(
    `INSERT INTO dim_produit (code_produit, version_courante, est_actif, niveau)
     VALUES ('PRODUIT_TRANSVERSE', true, true, 1)`,
  );
  await ds.query(
    `INSERT INTO dim_segment (code_segment, version_courante, est_actif)
     VALUES ('SEG_DEFAUT', true, true)`,
  );
  await ds.query(
    `INSERT INTO dim_centre_responsabilite
       (code_cr, libelle, fk_structure, version_courante, est_actif)
     VALUES
       ('BR_CIV', 'Branche CIV', 100, true, true),
       ('BR_BFA', 'Branche BFA', 200, true, true)`,
  );
  await ds.query(
    `INSERT INTO dim_compte (code_compte, classe, est_compte_collectif)
     VALUES
       ('611100', '6', false),
       ('760000', '7', false),
       ('670000', '6', false),
       ('600000', '6', true)`,
  );
  await ds.query(
    `INSERT INTO dim_ligne_metier (code_ligne_metier)
     VALUES ('RETAIL_PARTICULIERS')`,
  );
  await ds.query(
    `INSERT INTO dim_temps (date, jour, mois, annee) VALUES
      ('2027-01-01', 1, 1, 2027),
      ('2027-02-01', 1, 2, 2027),
      ('2027-02-15', 15, 2, 2027)`,
  );
  await ds.query(
    `INSERT INTO dim_version (code_version, libelle, statut)
     VALUES ('BI_2027', 'Budget initial 2027', 'ouvert'),
            ('BI_2026', 'Budget initial 2026', 'soumis')`,
  );
  await ds.query(
    `INSERT INTO dim_scenario (code_scenario) VALUES ('MEDIAN_2027')`,
  );

  const fetch = async (q: string): Promise<string> => {
    const r = (await ds.query(q)) as Array<{ id: string }>;
    return String(r[0]!.id);
  };
  return {
    devise: await fetch(`SELECT id FROM dim_devise LIMIT 1`),
    produit: await fetch(`SELECT id FROM dim_produit LIMIT 1`),
    segment: await fetch(`SELECT id FROM dim_segment LIMIT 1`),
    crCiv: await fetch(
      `SELECT id FROM dim_centre_responsabilite WHERE code_cr='BR_CIV'`,
    ),
    crBfa: await fetch(
      `SELECT id FROM dim_centre_responsabilite WHERE code_cr='BR_BFA'`,
    ),
    structureCiv: '100',
    structureBfa: '200',
    compte611: await fetch(
      `SELECT id FROM dim_compte WHERE code_compte='611100'`,
    ),
    compte76A: await fetch(
      `SELECT id FROM dim_compte WHERE code_compte='760000'`,
    ),
    compte67A: await fetch(
      `SELECT id FROM dim_compte WHERE code_compte='670000'`,
    ),
    compteAgrege: await fetch(
      `SELECT id FROM dim_compte WHERE code_compte='600000'`,
    ),
    ligneMetier: await fetch(`SELECT id FROM dim_ligne_metier LIMIT 1`),
    versionId: await fetch(
      `SELECT id FROM dim_version WHERE code_version='BI_2027'`,
    ),
    scenarioId: await fetch(`SELECT id FROM dim_scenario LIMIT 1`),
    tempsJanvier: await fetch(
      `SELECT id FROM dim_temps WHERE date='2027-01-01'`,
    ),
    tempsFevrier: await fetch(
      `SELECT id FROM dim_temps WHERE date='2027-02-01'`,
    ),
  };
}

// ─── Helpers fichiers ────────────────────────────────────────────────

function csv(lignes: string[]): { buffer: Buffer; originalname: string; size: number } {
  const text = lignes.join('\n') + '\n';
  const buffer = Buffer.from(text, 'utf-8');
  return { buffer, originalname: 'budget.csv', size: buffer.length };
}

const HEADER =
  'code_cr,code_compte,code_ligne_metier,mois,mode_saisie,montant,encours_moyen,tie,commentaire';

async function xlsx(rows: string[][]): Promise<{
  buffer: Buffer;
  originalname: string;
  size: number;
}> {
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet('Budget');
  for (const r of rows) ws.addRow(r);
  const buf = (await wb.xlsx.writeBuffer()) as ArrayBuffer;
  const buffer = Buffer.from(new Uint8Array(buf));
  return { buffer, originalname: 'budget.xlsx', size: buffer.length };
}

// ─── Tests ───────────────────────────────────────────────────────────

describe('BudgetImportService', () => {
  let dataSource: DataSource;
  let auditService: AuditService;
  let perimetre: PerimetreMock;
  let service: BudgetImportService;
  let ids: SeedIds;

  const adminUser = { userId: '1', email: 'admin@miznas.local' };

  beforeAll(async () => {
    dataSource = await createDataSource();
    auditService = new AuditService(dataSource.getRepository(AuditLog));
    perimetre = makePerimetreMock();
    service = new BudgetImportService(
      dataSource,
      perimetre as unknown as PerimetreService,
      auditService,
    );
    ids = await seedAll(dataSource);
  });

  afterAll(async () => {
    await dataSource.destroy();
  });

  beforeEach(async () => {
    await dataSource.query('DELETE FROM fait_budget');
    await dataSource.query('DELETE FROM audit_log');
    perimetre.setReturnValue(null); // admin par défaut
  });

  it('import 5 lignes valides → 5 inserees, 0 rejetees, audit OK, tauxChangeApplique=1', async () => {
    const file = csv([
      HEADER,
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-01,MONTANT,1000,,,Loyer Q1',
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-02,MONTANT,1100,,,',
      'BR_CIV,760000,RETAIL_PARTICULIERS,2027-01,MONTANT,5000,,,Produits',
      'BR_BFA,611100,RETAIL_PARTICULIERS,2027-01,MONTANT,800,,,',
      'BR_BFA,670000,RETAIL_PARTICULIERS,2027-01,MONTANT,300,,,Intérêts',
    ]);
    const r = await service.importFichier(
      file,
      ids.versionId,
      ids.scenarioId,
      adminUser,
    );
    expect(r.lignesTotal).toBe(5);
    expect(r.lignesValides).toBe(5);
    expect(r.lignesInserees).toBe(5);
    expect(r.lignesRejetees).toBe(0);
    expect(r.transactionRollback).toBe(false);
    const audit = (await dataSource.query(
      `SELECT type_action, statut FROM audit_log
        WHERE type_action='IMPORT_BUDGET_BULK'`,
    )) as Array<{ type_action: string; statut: string }>;
    expect(audit).toHaveLength(1);
    expect(audit[0]!.statut).toBe('success');

    // Mini-fix Lot 3.7 : taux_change_applique=1 (devise pivot XOF).
    // Sans cette valeur, l'INSERT en prod plantait sur la contrainte
    // NOT NULL — bug remonté au smoke test BSIC Niger.
    const taux = (await dataSource.query(
      `SELECT taux_change_applique FROM fait_budget`,
    )) as Array<{ taux_change_applique: string }>;
    expect(taux).toHaveLength(5);
    for (const t of taux) {
      expect(Number(t.taux_change_applique)).toBe(1);
    }
  });

  it('import 8 lignes mélangées (5 OK + 3 KO) → rapport détaillé', async () => {
    const file = csv([
      HEADER,
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-01,MONTANT,1000,,,',
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-02,MONTANT,1100,,,',
      'BR_CIV,760000,RETAIL_PARTICULIERS,2027-01,MONTANT,5000,,,',
      'BR_BFA,611100,RETAIL_PARTICULIERS,2027-01,MONTANT,800,,,',
      'BR_BFA,670000,RETAIL_PARTICULIERS,2027-01,MONTANT,300,,,',
      // 3 KO :
      'BR_INCONNU,611100,RETAIL_PARTICULIERS,2027-01,MONTANT,500,,,', // CR_INTROUVABLE
      'BR_CIV,999999,RETAIL_PARTICULIERS,2027-01,MONTANT,500,,,', // COMPTE_INTROUVABLE
      'BR_CIV,600000,RETAIL_PARTICULIERS,2027-01,MONTANT,500,,,', // COMPTE_AGREGE
    ]);
    const r = await service.importFichier(
      file,
      ids.versionId,
      ids.scenarioId,
      adminUser,
    );
    expect(r.lignesTotal).toBe(8);
    expect(r.lignesValides).toBe(5);
    expect(r.lignesRejetees).toBe(3);
    // Le taux d'erreurs = 3/8 = 37.5 % > 10 % → rollback
    expect(r.transactionRollback).toBe(true);
    expect(r.lignesInserees).toBe(0);
    const codes = r.erreurs.map((e) => e.code);
    expect(codes).toContain('CR_INTROUVABLE');
    expect(codes).toContain('COMPTE_INTROUVABLE');
    expect(codes).toContain('COMPTE_AGREGE');
  });

  it('CR hors périmètre → rejet ligne par ligne (CR_PERIMETRE_REFUSE)', async () => {
    perimetre.setReturnValue([ids.crCiv]); // user limité à BR_CIV
    const file = csv([
      HEADER,
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-01,MONTANT,1000,,,',
      'BR_BFA,611100,RETAIL_PARTICULIERS,2027-01,MONTANT,800,,,', // refusé
    ]);
    const r = await service.importFichier(
      file,
      ids.versionId,
      ids.scenarioId,
      adminUser,
    );
    expect(r.lignesValides).toBe(1);
    expect(r.lignesRejetees).toBe(1);
    // 1/2 = 50 % > 10 % → rollback (CR_PERIMETRE_REFUSE génère
    // tellement d'erreurs qu'on annule par sécurité)
    expect(r.transactionRollback).toBe(true);
    expect(r.erreurs[0]!.code).toBe('CR_PERIMETRE_REFUSE');
  });

  it('version statut=soumis → ConflictException (409)', async () => {
    const versionFermee = (
      (await dataSource.query(
        `SELECT id FROM dim_version WHERE code_version='BI_2026'`,
      )) as Array<{ id: string }>
    )[0]!.id;
    const file = csv([
      HEADER,
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-01,MONTANT,1000,,,',
    ]);
    await expect(
      service.importFichier(
        file,
        String(versionFermee),
        ids.scenarioId,
        adminUser,
      ),
    ).rejects.toThrow(ConflictException);
  });

  it('XLSX parsing → 2 lignes insérées', async () => {
    const file = await xlsx([
      HEADER.split(','),
      [
        'BR_CIV',
        '611100',
        'RETAIL_PARTICULIERS',
        '2027-01-01',
        'MONTANT',
        '1500',
        '',
        '',
        'Excel test',
      ],
      [
        'BR_BFA',
        '760000',
        'RETAIL_PARTICULIERS',
        '2027-02-01',
        'MONTANT',
        '4500',
        '',
        '',
        '',
      ],
    ]);
    const r = await service.importFichier(
      file,
      ids.versionId,
      ids.scenarioId,
      adminUser,
    );
    expect(r.formatDetecte).toBe('xlsx');
    expect(r.lignesInserees).toBe(2);
    expect(r.transactionRollback).toBe(false);
  });

  it('header invalide → BadRequestException', async () => {
    const file = csv([
      'colA,colB,colC',
      'BR_CIV,611100,2027-01',
    ]);
    await expect(
      service.importFichier(
        file,
        ids.versionId,
        ids.scenarioId,
        adminUser,
      ),
    ).rejects.toThrow(BadRequestException);
  });

  it('fichier vide (header seul) → BadRequestException', async () => {
    const file = csv([HEADER]);
    await expect(
      service.importFichier(
        file,
        ids.versionId,
        ids.scenarioId,
        adminUser,
      ),
    ).rejects.toThrow(BadRequestException);
  });

  it('mode ENCOURS_TIE recalcule montant + warning', async () => {
    const file = csv([
      HEADER,
      // encours=1200000, tie=0.06 → montant attendu = 6000
      // (1200000 * 0.06 / 12 = 6000) — mais l'utilisateur fournit 9999
      // → warning MONTANT_RECALCULE
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-01,ENCOURS_TIE,9999,1200000,0.06,',
    ]);
    const r = await service.importFichier(
      file,
      ids.versionId,
      ids.scenarioId,
      adminUser,
    );
    expect(r.lignesInserees).toBe(1);
    expect(r.warnings).toHaveLength(1);
    expect(r.warnings[0]!.code).toBe('MONTANT_RECALCULE');
    const inserted = (await dataSource.query(
      `SELECT montant_devise FROM fait_budget LIMIT 1`,
    )) as Array<{ montant_devise: string }>;
    expect(Number(inserted[0]!.montant_devise)).toBe(6000);
  });

  it('compte agrégé → COMPTE_AGREGE error', async () => {
    const file = csv([
      HEADER,
      'BR_CIV,600000,RETAIL_PARTICULIERS,2027-01,MONTANT,1000,,,',
    ]);
    const r = await service.importFichier(
      file,
      ids.versionId,
      ids.scenarioId,
      adminUser,
    );
    expect(r.lignesRejetees).toBe(1);
    expect(r.erreurs[0]!.code).toBe('COMPTE_AGREGE');
  });

  it('mois inconnu (dim_temps absent) → TEMPS_INTROUVABLE', async () => {
    const file = csv([
      HEADER,
      'BR_CIV,611100,RETAIL_PARTICULIERS,2099-12,MONTANT,1000,,,',
    ]);
    const r = await service.importFichier(
      file,
      ids.versionId,
      ids.scenarioId,
      adminUser,
    );
    expect(r.lignesRejetees).toBe(1);
    expect(r.erreurs[0]!.code).toBe('TEMPS_INTROUVABLE');
  });

  it('upsert : 2e import même clé met à jour la ligne', async () => {
    const file1 = csv([
      HEADER,
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-01,MONTANT,1000,,,',
    ]);
    await service.importFichier(file1, ids.versionId, ids.scenarioId, adminUser);
    const file2 = csv([
      HEADER,
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-01,MONTANT,1500,,,Modifié',
    ]);
    const r = await service.importFichier(
      file2,
      ids.versionId,
      ids.scenarioId,
      adminUser,
    );
    expect(r.lignesInserees).toBe(0);
    expect(r.lignesModifiees).toBe(1);
    const row = (await dataSource.query(
      `SELECT montant_devise, commentaire FROM fait_budget LIMIT 1`,
    )) as Array<{ montant_devise: string; commentaire: string }>;
    expect(Number(row[0]!.montant_devise)).toBe(1500);
    expect(row[0]!.commentaire).toBe('Modifié');
  });

  it('upsert : 2e import valeur identique → lignesIgnorees=1 (no-op)', async () => {
    const fileA = csv([
      HEADER,
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-01,MONTANT,1000,,,',
    ]);
    await service.importFichier(fileA, ids.versionId, ids.scenarioId, adminUser);
    const fileB = csv([
      HEADER,
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-01,MONTANT,1000,,,',
    ]);
    const r = await service.importFichier(
      fileB,
      ids.versionId,
      ids.scenarioId,
      adminUser,
    );
    expect(r.lignesIgnorees).toBe(1);
    expect(r.lignesInserees).toBe(0);
    expect(r.lignesModifiees).toBe(0);
  });

  it('rollback >10% : aucune ligne en base après import', async () => {
    // 2 OK + 8 KO = 80 % d'erreurs
    const file = csv([
      HEADER,
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-01,MONTANT,1,,,',
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-02,MONTANT,2,,,',
      ...Array.from({ length: 8 }, (_, i) =>
        `BR_CIV,99${i}000,RETAIL_PARTICULIERS,2027-01,MONTANT,1,,,`,
      ),
    ]);
    const r = await service.importFichier(
      file,
      ids.versionId,
      ids.scenarioId,
      adminUser,
    );
    expect(r.transactionRollback).toBe(true);
    expect(r.lignesInserees).toBe(0);
    const cnt = (await dataSource.query(
      `SELECT COUNT(*)::int AS n FROM fait_budget`,
    )) as Array<{ n: number }>;
    expect(cnt[0]!.n).toBe(0);
  });

  // Mini-fix critique Lot 3.7 — non-régression : imports successifs sur
  // 3 scénarios DIFFÉRENTS de la MÊME version doivent produire 3 jeux
  // de lignes indépendants (pas d'écrasement silencieux). Le grain
  // métier inclut fk_scenario (cf. uq_fait_budget_grain).
  it('imports multi-scénarios : chaque scénario garde ses propres lignes', async () => {
    // 2 scénarios supplémentaires (OPTIMISTE et PESSIMISTE) pour la
    // version BI_2027.
    await dataSource.query(
      `INSERT INTO dim_scenario (code_scenario)
       VALUES ('OPTIMISTE_2027'), ('PESSIMISTE_2027')`,
    );
    const scOpt = String(
      ((await dataSource.query(
        `SELECT id FROM dim_scenario WHERE code_scenario='OPTIMISTE_2027'`,
      )) as Array<{ id: string }>)[0]!.id,
    );
    const scPess = String(
      ((await dataSource.query(
        `SELECT id FROM dim_scenario WHERE code_scenario='PESSIMISTE_2027'`,
      )) as Array<{ id: string }>)[0]!.id,
    );

    // Mêmes (CR × compte × ligne_metier × mois) — seul le scénario
    // change → on doit obtenir 3 lignes distinctes après les 3 imports.
    const lignes = [
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-01,MONTANT,1000,,,',
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-02,MONTANT,1100,,,',
      'BR_CIV,760000,RETAIL_PARTICULIERS,2027-01,MONTANT,5000,,,',
    ];
    const fileMedian = csv([HEADER, ...lignes]);
    // Montants différents pour bien distinguer les scénarios.
    const fileOpt = csv([
      HEADER,
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-01,MONTANT,2000,,,',
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-02,MONTANT,2200,,,',
      'BR_CIV,760000,RETAIL_PARTICULIERS,2027-01,MONTANT,8000,,,',
    ]);
    const filePess = csv([
      HEADER,
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-01,MONTANT,500,,,',
      'BR_CIV,611100,RETAIL_PARTICULIERS,2027-02,MONTANT,550,,,',
      'BR_CIV,760000,RETAIL_PARTICULIERS,2027-01,MONTANT,3000,,,',
    ]);

    const r1 = await service.importFichier(
      fileMedian,
      ids.versionId,
      ids.scenarioId, // MEDIAN
      adminUser,
    );
    const r2 = await service.importFichier(
      fileOpt,
      ids.versionId,
      scOpt,
      adminUser,
    );
    const r3 = await service.importFichier(
      filePess,
      ids.versionId,
      scPess,
      adminUser,
    );

    // Chaque import insère ses 3 lignes — pas d'écrasement.
    expect(r1.lignesInserees).toBe(3);
    expect(r1.lignesModifiees).toBe(0);
    expect(r2.lignesInserees).toBe(3);
    expect(r2.lignesModifiees).toBe(0);
    expect(r3.lignesInserees).toBe(3);
    expect(r3.lignesModifiees).toBe(0);

    // Total = 9 lignes, 3 par scénario.
    const total = (await dataSource.query(
      `SELECT COUNT(*)::int AS n FROM fait_budget`,
    )) as Array<{ n: number }>;
    expect(total[0]!.n).toBe(9);

    const parScenario = (await dataSource.query(
      `SELECT fk_scenario, COUNT(*)::int AS n,
              SUM(montant_devise)::int AS total
         FROM fait_budget
        WHERE fk_version = $1
        GROUP BY fk_scenario`,
      [ids.versionId],
    )) as Array<{ fk_scenario: string; n: number; total: number }>;
    expect(parScenario).toHaveLength(3);

    const byId = new Map(parScenario.map((r) => [String(r.fk_scenario), r]));
    expect(byId.get(ids.scenarioId)!.n).toBe(3);
    expect(byId.get(ids.scenarioId)!.total).toBe(7100); // 1000+1100+5000
    expect(byId.get(scOpt)!.n).toBe(3);
    expect(byId.get(scOpt)!.total).toBe(12200); // 2000+2200+8000
    expect(byId.get(scPess)!.n).toBe(3);
    expect(byId.get(scPess)!.total).toBe(4050); // 500+550+3000
  });
});
