/**
 * Tests unitaires IndicateursService (Lot 3.6) via pg-mem.
 *
 * pg-mem ne supporte pas `CREATE MATERIALIZED VIEW`, donc on simule
 * la vue par une table régulière `mv_indicateurs_budget` peuplée
 * manuellement avec des lignes représentatives. Cela vérifie la
 * logique d'agrégation JS du service mais pas la recette SQL de la
 * migration (testée séparément au e2e contre Postgres réel).
 *
 * `refreshIndicateurs` est testé avec un DataSource mocké car
 * `REFRESH MATERIALIZED VIEW` n'a pas d'équivalent pg-mem.
 */
import { DataType, IMemoryDb, newDb } from 'pg-mem';
import { DataSource } from 'typeorm';

import { AuditLog } from '../../audit/entities/audit-log.entity';
import { AuditService } from '../../audit/audit.service';
import { IndicateursService } from './indicateurs.service';
import { PerimetreService } from './perimetre.service';

function buildMemDb(): IMemoryDb {
  const db = newDb({ autoCreateForeignKeyIndices: true });
  db.public.registerFunction({
    name: 'current_database',
    args: [],
    returns: DataType.text,
    implementation: () => 'test',
  });
  db.public.registerFunction({
    name: 'version',
    args: [],
    returns: DataType.text,
    implementation: () => 'PostgreSQL 15 (pg-mem)',
  });
  return db;
}

async function createDataSource(): Promise<DataSource> {
  const db = buildMemDb();
  const ds: DataSource = db.adapters.createTypeormDataSource({
    type: 'postgres',
    entities: [AuditLog],
    synchronize: true,
  });
  await ds.initialize();

  // Substitut de la vue matérialisée — schéma identique aux
  // colonnes lues par le service.
  await ds.query(`
    CREATE TABLE mv_indicateurs_budget (
      fk_version                bigint NOT NULL,
      fk_scenario               bigint NOT NULL,
      fk_centre                 bigint NOT NULL,
      code_cr                   varchar(50) NOT NULL,
      libelle_cr                varchar(200) NOT NULL,
      exercice                  int NOT NULL,
      total_classe_6            numeric(20,2) NOT NULL,
      total_classe_7            numeric(20,2) NOT NULL,
      total_67_charges_interets numeric(20,2) NOT NULL,
      total_76_produits_interets numeric(20,2) NOT NULL,
      pnb                       numeric(20,2) NOT NULL,
      mni                       numeric(20,2) NOT NULL,
      charges_hors_interets     numeric(20,2) NOT NULL,
      nb_lignes                 int NOT NULL,
      derniere_modif            timestamp NULL
    )
  `);
  // Table dim_scenario minimale pour le JOIN dans
  // getIndicateursComparaison.
  await ds.query(`
    CREATE TABLE dim_scenario (
      id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_scenario   varchar(50) NOT NULL,
      libelle         varchar(200) NOT NULL,
      type_scenario   varchar(30) NOT NULL
    )
  `);
  await ds.query(`
    CREATE TABLE dim_version (
      id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_version  varchar(50) NOT NULL,
      libelle       varchar(200) NOT NULL
    )
  `);
  return ds;
}

interface SeedRow {
  fkVersion: string;
  fkScenario: string;
  fkCentre: string;
  codeCr: string;
  libelleCr?: string;
  exercice?: number;
  totalClasse6?: number;
  totalClasse7?: number;
  total67?: number;
  total76?: number;
  chargesHorsInterets?: number;
  nbLignes?: number;
  derniereModif?: string;
}

async function seed(ds: DataSource, row: SeedRow): Promise<void> {
  const cl6 = row.totalClasse6 ?? 0;
  const cl7 = row.totalClasse7 ?? 0;
  const t67 = row.total67 ?? 0;
  const t76 = row.total76 ?? 0;
  const charges = row.chargesHorsInterets ?? cl6 - t67;
  const pnb = cl7 - t67;
  const mni = t76 - t67;
  await ds.query(
    `INSERT INTO mv_indicateurs_budget VALUES
       ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)`,
    [
      row.fkVersion,
      row.fkScenario,
      row.fkCentre,
      row.codeCr,
      row.libelleCr ?? row.codeCr,
      row.exercice ?? 2027,
      cl6,
      cl7,
      t67,
      t76,
      pnb,
      mni,
      charges,
      row.nbLignes ?? 12,
      row.derniereModif ?? '2026-05-01T10:00:00Z',
    ],
  );
}

async function seedScenario(
  ds: DataSource,
  id: string,
  code: string,
  type: 'central' | 'optimiste' | 'pessimiste' | 'alternatif',
): Promise<void> {
  await ds.query(
    `INSERT INTO dim_scenario (id, code_scenario, libelle, type_scenario)
     VALUES ($1, $2, $3, $4)`,
    [id, code, code, type],
  );
}

interface FakePerimetreService {
  setReturnValue: (v: string[] | null) => void;
  getCrAutorisesPourUser: (uid: string) => Promise<string[] | null>;
}

function makePerimetreMock(): FakePerimetreService {
  let value: string[] | null = null;
  return {
    setReturnValue: (v) => {
      value = v;
    },
    getCrAutorisesPourUser: async () => value,
  };
}

describe('IndicateursService — lecture (mv simulée)', () => {
  let dataSource: DataSource;
  let auditService: AuditService;
  let perimetre: FakePerimetreService;
  let service: IndicateursService;

  const adminUser = { userId: '1', email: 'admin@miznas.local' };
  const restrictedUser = { userId: '2', email: 'civ@miznas.local' };

  beforeAll(async () => {
    dataSource = await createDataSource();
    auditService = new AuditService(dataSource.getRepository(AuditLog));
    perimetre = makePerimetreMock();
    service = new IndicateursService(
      dataSource,
      perimetre as unknown as PerimetreService,
      auditService,
    );

    // Version + scénarios de référence
    await dataSource.query(
      `INSERT INTO dim_version (id, code_version, libelle)
       VALUES (10, 'BI_2027', 'Budget initial 2027')`,
    );
    await seedScenario(dataSource, '100', 'MEDIAN_2027', 'central');
    await seedScenario(dataSource, '101', 'OPTIMISTE_2027', 'optimiste');
    await seedScenario(dataSource, '102', 'PESSIMISTE_2027', 'pessimiste');
  });

  afterAll(async () => {
    await dataSource.destroy();
  });

  beforeEach(async () => {
    await dataSource.query('DELETE FROM mv_indicateurs_budget');
    await dataSource.query('DELETE FROM audit_log');
    perimetre.setReturnValue(null); // admin par défaut
  });

  it('getIndicateursGlobaux : agrège PNB / MNI sur 2 CR', async () => {
    // CR 200 : produits 100, charges 70 (dont 67 = 30) → PNB=70, MNI=20-30=-10
    await seed(dataSource, {
      fkVersion: '10',
      fkScenario: '100',
      fkCentre: '200',
      codeCr: 'BR_CIV',
      totalClasse7: 100,
      totalClasse6: 70,
      total67: 30,
      total76: 20,
    });
    // CR 201 : produits 50, charges 35 (dont 67=10) → PNB=40, MNI=15-10=5
    await seed(dataSource, {
      fkVersion: '10',
      fkScenario: '100',
      fkCentre: '201',
      codeCr: 'BR_BFA',
      totalClasse7: 50,
      totalClasse6: 35,
      total67: 10,
      total76: 15,
    });
    const res = await service.getIndicateursGlobaux(
      { versionId: '10', scenarioId: '100', exerciceFiscal: 2027 },
      adminUser,
    );
    expect(res.pnb).toBe(110); // (100-30) + (50-10) = 70+40
    expect(res.mni).toBe(-5); // (-10) + 5
    expect(res.totalProduits).toBe(150);
    expect(res.totalCharges).toBe(105);
    expect(res.nbCrInclus).toBe(2);
  });

  it('Coefficient = chargesHorsInterets / PNB × 100', async () => {
    await seed(dataSource, {
      fkVersion: '10',
      fkScenario: '100',
      fkCentre: '200',
      codeCr: 'BR_CIV',
      totalClasse7: 200,
      totalClasse6: 150,
      total67: 50,
      chargesHorsInterets: 100,
    });
    const res = await service.getIndicateursGlobaux(
      { versionId: '10', scenarioId: '100', exerciceFiscal: 2027 },
      adminUser,
    );
    // PNB = 200-50 = 150 ; coef = 100/150 ×100 ≈ 66.67
    expect(res.pnb).toBe(150);
    expect(res.coefExploitation).toBeCloseTo(66.6667, 2);
  });

  it('Coefficient = null si PNB ≤ 0 (évite division /0 et coef négatif)', async () => {
    await seed(dataSource, {
      fkVersion: '10',
      fkScenario: '100',
      fkCentre: '200',
      codeCr: 'BR_CIV',
      totalClasse7: 50,
      totalClasse6: 100,
      total67: 70,
      chargesHorsInterets: 30,
    });
    const res = await service.getIndicateursGlobaux(
      { versionId: '10', scenarioId: '100', exerciceFiscal: 2027 },
      adminUser,
    );
    // PNB = 50-70 = -20 → coef null
    expect(res.pnb).toBe(-20);
    expect(res.coefExploitation).toBeNull();
  });

  it('Coefficient > 100% reste valide (caller décidera de l\'alerte)', async () => {
    await seed(dataSource, {
      fkVersion: '10',
      fkScenario: '100',
      fkCentre: '200',
      codeCr: 'BR_CIV',
      totalClasse7: 100,
      totalClasse6: 200,
      total67: 50,
      chargesHorsInterets: 150,
    });
    const res = await service.getIndicateursGlobaux(
      { versionId: '10', scenarioId: '100', exerciceFiscal: 2027 },
      adminUser,
    );
    // PNB = 100-50 = 50 ; coef = 150/50 ×100 = 300
    expect(res.coefExploitation).toBe(300);
  });

  it('Filtrage périmètre : restricted_user ne voit que ses CR', async () => {
    await seed(dataSource, {
      fkVersion: '10',
      fkScenario: '100',
      fkCentre: '200',
      codeCr: 'BR_CIV',
      totalClasse7: 100,
      totalClasse6: 50,
      total67: 20,
    });
    await seed(dataSource, {
      fkVersion: '10',
      fkScenario: '100',
      fkCentre: '201',
      codeCr: 'BR_BFA',
      totalClasse7: 80,
      totalClasse6: 40,
      total67: 15,
    });
    perimetre.setReturnValue(['200']); // restreint à BR_CIV
    const res = await service.getIndicateursGlobaux(
      { versionId: '10', scenarioId: '100', exerciceFiscal: 2027 },
      restrictedUser,
    );
    expect(res.totalProduits).toBe(100); // pas 180
    expect(res.nbCrInclus).toBe(1);
  });

  it('Périmètre vide ([]) → tout à zéro', async () => {
    await seed(dataSource, {
      fkVersion: '10',
      fkScenario: '100',
      fkCentre: '200',
      codeCr: 'BR_CIV',
      totalClasse7: 999,
    });
    perimetre.setReturnValue([]);
    const res = await service.getIndicateursGlobaux(
      { versionId: '10', scenarioId: '100', exerciceFiscal: 2027 },
      restrictedUser,
    );
    expect(res.pnb).toBe(0);
    expect(res.totalProduits).toBe(0);
    expect(res.nbCrInclus).toBe(0);
  });

  it('getIndicateursParCr : 1 ligne par CR avec coef', async () => {
    await seed(dataSource, {
      fkVersion: '10',
      fkScenario: '100',
      fkCentre: '200',
      codeCr: 'BR_CIV',
      libelleCr: 'Côte d\'Ivoire',
      totalClasse7: 100,
      totalClasse6: 60,
      total67: 20,
      chargesHorsInterets: 40,
    });
    await seed(dataSource, {
      fkVersion: '10',
      fkScenario: '100',
      fkCentre: '201',
      codeCr: 'BR_BFA',
      libelleCr: 'Burkina',
      totalClasse7: 50,
      totalClasse6: 30,
      total67: 10,
      chargesHorsInterets: 20,
    });
    const res = await service.getIndicateursParCr(
      { versionId: '10', scenarioId: '100', exerciceFiscal: 2027 },
      adminUser,
    );
    expect(res).toHaveLength(2);
    const civ = res.find((r) => r.codeCr === 'BR_CIV')!;
    expect(civ.pnb).toBe(80); // 100-20
    expect(civ.coefExploitation).toBe(50); // 40/80 ×100
    expect(civ.libelleCr).toBe('Côte d\'Ivoire');
  });

  it('getIndicateursParCr : filtré par périmètre', async () => {
    await seed(dataSource, {
      fkVersion: '10',
      fkScenario: '100',
      fkCentre: '200',
      codeCr: 'BR_CIV',
      totalClasse7: 100,
    });
    await seed(dataSource, {
      fkVersion: '10',
      fkScenario: '100',
      fkCentre: '201',
      codeCr: 'BR_BFA',
      totalClasse7: 50,
    });
    perimetre.setReturnValue(['200']);
    const res = await service.getIndicateursParCr(
      { versionId: '10', scenarioId: '100', exerciceFiscal: 2027 },
      restrictedUser,
    );
    expect(res).toHaveLength(1);
    expect(res[0]!.codeCr).toBe('BR_CIV');
  });

  it('getIndicateursComparaison : 3 scénarios côte à côte', async () => {
    for (const [scId, total7] of [
      ['100', 100],
      ['101', 130],
      ['102', 80],
    ] as const) {
      await seed(dataSource, {
        fkVersion: '10',
        fkScenario: scId,
        fkCentre: '200',
        codeCr: 'BR_CIV',
        totalClasse7: total7,
        totalClasse6: 50,
        total67: 20,
      });
    }
    const res = await service.getIndicateursComparaison(
      { versionId: '10', exerciceFiscal: 2027 },
      adminUser,
    );
    expect(res.scenarios).toHaveLength(3);
    expect(res.version.codeVersion).toBe('BI_2027');
    expect(
      res.scenarios.find((s) => s.codeScenario === 'OPTIMISTE_2027')!.pnb,
    ).toBe(110); // 130-20
  });

  it('getIndicateursComparaison : 1 seul scénario → 1 entrée', async () => {
    await seed(dataSource, {
      fkVersion: '10',
      fkScenario: '100',
      fkCentre: '200',
      codeCr: 'BR_CIV',
      totalClasse7: 100,
    });
    const res = await service.getIndicateursComparaison(
      { versionId: '10', exerciceFiscal: 2027 },
      adminUser,
    );
    expect(res.scenarios).toHaveLength(1);
    expect(res.scenarios[0]!.codeScenario).toBe('MEDIAN_2027');
  });

  it('getIndicateursComparaison : périmètre vide → scenarios=[]', async () => {
    await seed(dataSource, {
      fkVersion: '10',
      fkScenario: '100',
      fkCentre: '200',
      codeCr: 'BR_CIV',
      totalClasse7: 100,
    });
    perimetre.setReturnValue([]);
    const res = await service.getIndicateursComparaison(
      { versionId: '10', exerciceFiscal: 2027 },
      restrictedUser,
    );
    expect(res.scenarios).toHaveLength(0);
    expect(res.version.codeVersion).toBe('BI_2027');
  });
});

// ─── refreshIndicateurs : mock du DataSource ─────────────────────────

describe('IndicateursService — refreshIndicateurs', () => {
  it('appelle REFRESH MATERIALIZED VIEW CONCURRENTLY et consigne audit', async () => {
    const queries: string[] = [];
    const audit = { log: jest.fn() } as unknown as AuditService;
    const ds = {
      query: jest.fn(async (sql: string) => {
        queries.push(sql.trim());
        if (/^REFRESH/i.test(sql)) return [];
        return [{ n: '42' }]; // count
      }),
    } as unknown as DataSource;
    const perim = {
      getCrAutorisesPourUser: async () => null,
    } as unknown as PerimetreService;
    const service = new IndicateursService(ds, perim, audit);

    const res = await service.refreshIndicateurs({
      email: 'admin@miznas.local',
    });

    expect(queries[0]).toMatch(/REFRESH MATERIALIZED VIEW CONCURRENTLY/i);
    expect(res.nbLignes).toBe(42);
    expect(res.dureeMs).toBeGreaterThanOrEqual(0);
    expect(audit.log).toHaveBeenCalledWith(
      expect.objectContaining({
        typeAction: 'RECALCUL_INDICATEURS',
        utilisateur: 'admin@miznas.local',
        statut: 'success',
        entiteCible: 'mv_indicateurs_budget',
      }),
    );
  });

  it('fallback non-concurrent si CONCURRENTLY refusé (premier refresh)', async () => {
    const queries: string[] = [];
    let firstRefresh = true;
    const ds = {
      query: jest.fn(async (sql: string) => {
        queries.push(sql.trim());
        if (firstRefresh && /CONCURRENTLY/i.test(sql)) {
          firstRefresh = false;
          throw new Error(
            'cannot refresh materialized view concurrently — first refresh',
          );
        }
        if (/^REFRESH/i.test(sql)) return [];
        return [{ n: '0' }];
      }),
    } as unknown as DataSource;
    const audit = { log: jest.fn() } as unknown as AuditService;
    const perim = {
      getCrAutorisesPourUser: async () => null,
    } as unknown as PerimetreService;
    const service = new IndicateursService(ds, perim, audit);

    const res = await service.refreshIndicateurs({ email: 'admin' });

    expect(
      queries.some(
        (q) =>
          /^REFRESH MATERIALIZED VIEW "mv_indicateurs_budget"$/i.test(q) ||
          q ===
            'REFRESH MATERIALIZED VIEW "mv_indicateurs_budget"',
      ),
    ).toBe(true);
    expect(res.nbLignes).toBe(0);
  });
});
