import { MigrationInterface, QueryRunner } from 'typeorm';
import {
  dropScd2Indexes,
  enforceAlwaysIdentity,
  scd2Columns,
  scd2Indexes,
} from '../common/migrations/scd2-helpers';

export class CreateDimSegment1777970000000 implements MigrationInterface {
  name = 'CreateDimSegment1777970000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "dim_segment" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "code_segment" varchar(50) NOT NULL,
        "libelle" varchar(200) NOT NULL,
        "categorie" varchar(30) NOT NULL,
        ${scd2Columns()},
        CONSTRAINT "ck_dim_segment_categorie" CHECK ("categorie" IN ('particulier','professionnel','pme','grande_entreprise','institutionnel','secteur_public')),
        CONSTRAINT "PK_dim_segment" PRIMARY KEY ("id")
      )
    `);

    await queryRunner.query(enforceAlwaysIdentity('dim_segment'));

    for (const sql of scd2Indexes('dim_segment', 'code_segment')) {
      await queryRunner.query(sql);
    }

    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_dim_segment_business_date" ON "dim_segment" ("code_segment", "date_debut_validite")`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_dim_segment_categorie" ON "dim_segment" ("categorie")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_dim_segment_categorie"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."uq_dim_segment_business_date"`,
    );
    for (const sql of dropScd2Indexes('dim_segment')) {
      await queryRunner.query(sql);
    }
    await queryRunner.query(`DROP TABLE "dim_segment"`);
  }
}
