import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateDimTemps1777680000000 implements MigrationInterface {
  name = 'CreateDimTemps1777680000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "dim_temps" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "date" date NOT NULL,
        "annee" int NOT NULL,
        "trimestre" int NOT NULL,
        "mois" int NOT NULL,
        "jour" int NOT NULL,
        "semaine_iso" int,
        "jour_ouvre" boolean NOT NULL,
        "est_fin_de_mois" boolean NOT NULL,
        "est_fin_de_trimestre" boolean NOT NULL,
        "est_fin_d_annee" boolean NOT NULL,
        "exercice_fiscal" int NOT NULL,
        "libelle_mois" varchar(20) NOT NULL,
        CONSTRAINT "ck_dim_temps_trimestre" CHECK ("trimestre" BETWEEN 1 AND 4),
        CONSTRAINT "ck_dim_temps_mois" CHECK ("mois" BETWEEN 1 AND 12),
        CONSTRAINT "ck_dim_temps_jour" CHECK ("jour" BETWEEN 1 AND 31),
        CONSTRAINT "PK_dim_temps" PRIMARY KEY ("id")
      )
    `);

    // Ajustements manuels (cf. docs/conventions.md §5.2.1) — TypeORM
    // produit `GENERATED BY DEFAULT`, on force `GENERATED ALWAYS`.
    await queryRunner.query(
      `ALTER TABLE "dim_temps" ALTER COLUMN "id" SET GENERATED ALWAYS`,
    );

    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_dim_temps_date" ON "dim_temps" ("date")`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_dim_temps_annee_mois" ON "dim_temps" ("annee", "mois")`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_dim_temps_exercice_fiscal" ON "dim_temps" ("exercice_fiscal")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_dim_temps_exercice_fiscal"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_dim_temps_annee_mois"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."uq_dim_temps_date"`,
    );
    await queryRunner.query(`DROP TABLE "dim_temps"`);
  }
}
