import { MigrationInterface, QueryRunner } from 'typeorm';
import {
  dropScd2Indexes,
  enforceAlwaysIdentity,
  scd2Columns,
  scd2Indexes,
} from '../common/migrations/scd2-helpers';

export class CreateDimCompte1777900000000 implements MigrationInterface {
  name = 'CreateDimCompte1777900000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "dim_compte" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "code_compte" varchar(20) NOT NULL,
        "libelle" varchar(200) NOT NULL,
        "classe" int NOT NULL,
        "sous_classe" varchar(20),
        "fk_compte_parent" bigint,
        "niveau" int NOT NULL,
        "sens" char(1),
        "code_poste_budgetaire" varchar(50),
        "est_compte_collectif" boolean NOT NULL DEFAULT false,
        "est_porteur_interets" boolean NOT NULL DEFAULT false,
        ${scd2Columns()},
        CONSTRAINT "ck_dim_compte_classe" CHECK ("classe" BETWEEN 1 AND 9),
        CONSTRAINT "ck_dim_compte_niveau" CHECK ("niveau" BETWEEN 1 AND 4),
        CONSTRAINT "ck_dim_compte_sens" CHECK ("sens" IS NULL OR "sens" IN ('D','C','M')),
        CONSTRAINT "PK_dim_compte" PRIMARY KEY ("id"),
        CONSTRAINT "FK_dim_compte_parent" FOREIGN KEY ("fk_compte_parent")
          REFERENCES "dim_compte"("id") ON DELETE RESTRICT ON UPDATE NO ACTION
      )
    `);

    await queryRunner.query(enforceAlwaysIdentity('dim_compte'));

    // Index SCD2 standards (incluant l'unique partiel `uq_dim_compte_courante`).
    for (const sql of scd2Indexes('dim_compte', 'code_compte')) {
      await queryRunner.query(sql);
    }

    // Défense en profondeur intra-jour (cf. fix 2.3A.1).
    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_dim_compte_business_date" ON "dim_compte" ("code_compte", "date_debut_validite")`,
    );

    // Index hiérarchie + filtres.
    await queryRunner.query(
      `CREATE INDEX "ix_dim_compte_parent" ON "dim_compte" ("fk_compte_parent")`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_dim_compte_classe" ON "dim_compte" ("classe")`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_dim_compte_collectif" ON "dim_compte" ("est_compte_collectif")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_dim_compte_collectif"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_dim_compte_classe"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_dim_compte_parent"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."uq_dim_compte_business_date"`,
    );
    for (const sql of dropScd2Indexes('dim_compte')) {
      await queryRunner.query(sql);
    }
    await queryRunner.query(
      `ALTER TABLE "dim_compte" DROP CONSTRAINT IF EXISTS "FK_dim_compte_parent"`,
    );
    await queryRunner.query(`DROP TABLE "dim_compte"`);
  }
}
