import { MigrationInterface, QueryRunner } from 'typeorm';
import {
  dropScd2Indexes,
  enforceAlwaysIdentity,
  scd2Columns,
  scd2Indexes,
} from '../common/migrations/scd2-helpers';

export class CreateDimProduit1777960000000 implements MigrationInterface {
  name = 'CreateDimProduit1777960000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "dim_produit" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "code_produit" varchar(50) NOT NULL,
        "libelle" varchar(200) NOT NULL,
        "type_produit" varchar(20) NOT NULL,
        "fk_produit_parent" bigint,
        "niveau" int NOT NULL,
        "est_porteur_interets" boolean NOT NULL DEFAULT false,
        ${scd2Columns()},
        CONSTRAINT "ck_dim_produit_niveau" CHECK ("niveau" BETWEEN 1 AND 4),
        CONSTRAINT "ck_dim_produit_type" CHECK ("type_produit" IN ('credit','depot','service','marche','autre')),
        CONSTRAINT "PK_dim_produit" PRIMARY KEY ("id"),
        CONSTRAINT "FK_dim_produit_parent" FOREIGN KEY ("fk_produit_parent")
          REFERENCES "dim_produit"("id") ON DELETE RESTRICT ON UPDATE NO ACTION
      )
    `);

    await queryRunner.query(enforceAlwaysIdentity('dim_produit'));

    for (const sql of scd2Indexes('dim_produit', 'code_produit')) {
      await queryRunner.query(sql);
    }

    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_dim_produit_business_date" ON "dim_produit" ("code_produit", "date_debut_validite")`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_dim_produit_parent" ON "dim_produit" ("fk_produit_parent")`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_dim_produit_type" ON "dim_produit" ("type_produit")`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_dim_produit_porteur_interets" ON "dim_produit" ("est_porteur_interets")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_dim_produit_porteur_interets"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_dim_produit_type"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_dim_produit_parent"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."uq_dim_produit_business_date"`,
    );
    for (const sql of dropScd2Indexes('dim_produit')) {
      await queryRunner.query(sql);
    }
    await queryRunner.query(
      `ALTER TABLE "dim_produit" DROP CONSTRAINT IF EXISTS "FK_dim_produit_parent"`,
    );
    await queryRunner.query(`DROP TABLE "dim_produit"`);
  }
}
