import { MigrationInterface, QueryRunner } from 'typeorm';
import {
  dropScd2Indexes,
  enforceAlwaysIdentity,
  scd2Columns,
  scd2Indexes,
} from '../common/migrations/scd2-helpers';

export class CreateDimLigneMetier1777950000000 implements MigrationInterface {
  name = 'CreateDimLigneMetier1777950000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "dim_ligne_metier" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "code_ligne_metier" varchar(50) NOT NULL,
        "libelle" varchar(200) NOT NULL,
        "fk_ligne_metier_parent" bigint,
        "niveau" int NOT NULL,
        ${scd2Columns()},
        CONSTRAINT "ck_dim_ligne_metier_niveau" CHECK ("niveau" BETWEEN 1 AND 4),
        CONSTRAINT "PK_dim_ligne_metier" PRIMARY KEY ("id"),
        CONSTRAINT "FK_dim_ligne_metier_parent" FOREIGN KEY ("fk_ligne_metier_parent")
          REFERENCES "dim_ligne_metier"("id") ON DELETE RESTRICT ON UPDATE NO ACTION
      )
    `);

    await queryRunner.query(enforceAlwaysIdentity('dim_ligne_metier'));

    for (const sql of scd2Indexes('dim_ligne_metier', 'code_ligne_metier')) {
      await queryRunner.query(sql);
    }

    // Défense en profondeur intra-jour (cf. fix 2.3A.1).
    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_dim_ligne_metier_business_date" ON "dim_ligne_metier" ("code_ligne_metier", "date_debut_validite")`,
    );

    // Index hiérarchie.
    await queryRunner.query(
      `CREATE INDEX "ix_dim_ligne_metier_parent" ON "dim_ligne_metier" ("fk_ligne_metier_parent")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_dim_ligne_metier_parent"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."uq_dim_ligne_metier_business_date"`,
    );
    for (const sql of dropScd2Indexes('dim_ligne_metier')) {
      await queryRunner.query(sql);
    }
    await queryRunner.query(
      `ALTER TABLE "dim_ligne_metier" DROP CONSTRAINT IF EXISTS "FK_dim_ligne_metier_parent"`,
    );
    await queryRunner.query(`DROP TABLE "dim_ligne_metier"`);
  }
}
