import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateDimDevise1777740000000 implements MigrationInterface {
  name = 'CreateDimDevise1777740000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "dim_devise" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "code_iso" char(3) NOT NULL,
        "libelle" varchar(100) NOT NULL,
        "symbole" varchar(10),
        "nb_decimales" int NOT NULL DEFAULT 2,
        "est_devise_pivot" boolean NOT NULL DEFAULT false,
        "est_active" boolean NOT NULL DEFAULT true,
        "date_creation" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "utilisateur_creation" varchar(255) NOT NULL DEFAULT 'system',
        "date_modification" timestamp,
        "utilisateur_modification" varchar(255),
        CONSTRAINT "ck_dim_devise_nb_decimales" CHECK ("nb_decimales" BETWEEN 0 AND 8),
        CONSTRAINT "PK_dim_devise" PRIMARY KEY ("id")
      )
    `);

    // Ajustement manuel : GENERATED ALWAYS (cf. conventions.md §5.2.1).
    await queryRunner.query(
      `ALTER TABLE "dim_devise" ALTER COLUMN "id" SET GENERATED ALWAYS`,
    );

    // Unicité du code ISO (à part de la contrainte inline pour bénéficier
    // d'un nom d'index lisible dans les diagnostics).
    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_dim_devise_code_iso" ON "dim_devise" ("code_iso")`,
    );

    // Index simple sur est_active pour les filtres de listing.
    await queryRunner.query(
      `CREATE INDEX "ix_dim_devise_est_active" ON "dim_devise" ("est_active")`,
    );

    // Index unique partiel CRITIQUE — invariant métier : une seule
    // devise pivot dans toute la table (cf. modele-donnees.md §3.8 et
    // conventions.md §5.2.2). TypeORM ne sait pas inférer les index
    // partiels depuis le metadata, à conserver manuellement à chaque
    // régénération de migration.
    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_dim_devise_pivot" ON "dim_devise" ("est_devise_pivot") WHERE "est_devise_pivot" = true`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."uq_dim_devise_pivot"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_dim_devise_est_active"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."uq_dim_devise_code_iso"`,
    );
    await queryRunner.query(`DROP TABLE "dim_devise"`);
  }
}
