import { MigrationInterface, QueryRunner } from 'typeorm';
import {
  dropScd2Indexes,
  enforceAlwaysIdentity,
  scd2Columns,
  scd2Indexes,
} from '../common/migrations/scd2-helpers';

export class CreateDimStructure1777800000000 implements MigrationInterface {
  name = 'CreateDimStructure1777800000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "dim_structure" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "code_structure" varchar(50) NOT NULL,
        "libelle" varchar(200) NOT NULL,
        "libelle_court" varchar(50),
        "type_structure" varchar(20) NOT NULL,
        "niveau_hierarchique" int NOT NULL,
        "fk_structure_parent" bigint,
        "code_pays" char(3),
        ${scd2Columns()},
        CONSTRAINT "ck_dim_structure_type" CHECK (
          "type_structure" IN ('entite_juridique','branche','direction','departement','agence')
        ),
        CONSTRAINT "ck_dim_structure_niveau" CHECK ("niveau_hierarchique" >= 1),
        CONSTRAINT "ck_dim_structure_pays" CHECK (
          "code_pays" IS NULL OR
          "code_pays" IN ('CIV','SEN','BEN','BFA','MLI','NER','TGO','GNB')
        ),
        CONSTRAINT "PK_dim_structure" PRIMARY KEY ("id"),
        CONSTRAINT "FK_dim_structure_parent" FOREIGN KEY ("fk_structure_parent")
          REFERENCES "dim_structure"("id") ON DELETE RESTRICT ON UPDATE NO ACTION
      )
    `);

    await queryRunner.query(enforceAlwaysIdentity('dim_structure'));

    // Index SCD2 standards : (code, version_courante), (code, date_debut),
    // et l'index unique partiel `uq_dim_structure_courante` (cf.
    // conventions.md §5.2.2).
    for (const sql of scd2Indexes('dim_structure', 'code_structure')) {
      await queryRunner.query(sql);
    }

    // Unicité (code_structure, date_debut_validite) — cf.
    // modele-donnees.md §3.2 « Unicité (code_structure, date_debut_validite) ».
    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_dim_structure_business_date" ON "dim_structure" ("code_structure", "date_debut_validite")`,
    );

    // Index hiérarchique : descendants directs.
    await queryRunner.query(
      `CREATE INDEX "ix_dim_structure_parent" ON "dim_structure" ("fk_structure_parent")`,
    );

    // Index pays : filtres listing par pays UEMOA.
    await queryRunner.query(
      `CREATE INDEX "ix_dim_structure_code_pays" ON "dim_structure" ("code_pays")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_dim_structure_code_pays"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_dim_structure_parent"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."uq_dim_structure_business_date"`,
    );
    for (const sql of dropScd2Indexes('dim_structure')) {
      await queryRunner.query(sql);
    }
    await queryRunner.query(
      `ALTER TABLE "dim_structure" DROP CONSTRAINT IF EXISTS "FK_dim_structure_parent"`,
    );
    await queryRunner.query(`DROP TABLE "dim_structure"`);
  }
}
