import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitAuthSchema1777384329141 implements MigrationInterface {
  name = 'InitAuthSchema1777384329141';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "ref_permission" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "code_permission" character varying(100) NOT NULL, "libelle" character varying(200) NOT NULL, "description" text, "module" character varying(50) NOT NULL, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "utilisateur_creation" character varying(255) NOT NULL DEFAULT 'system', CONSTRAINT "PK_01daf4870144d6b5eaf482832e1" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_ref_permission_code" ON "ref_permission" ("code_permission") `,
    );
    await queryRunner.query(
      `CREATE TABLE "bridge_role_permission" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "fk_role" bigint NOT NULL, "fk_permission" bigint NOT NULL, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_bridge_role_permission" UNIQUE ("fk_role", "fk_permission"), CONSTRAINT "PK_4538f0fdcd3e7be385aa2d11778" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_bridge_role_permission_permission" ON "bridge_role_permission" ("fk_permission") `,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_bridge_role_permission_role" ON "bridge_role_permission" ("fk_role") `,
    );
    await queryRunner.query(
      `CREATE TABLE "ref_role" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "code_role" character varying(50) NOT NULL, "libelle" character varying(150) NOT NULL, "description" text, "est_actif" boolean NOT NULL DEFAULT true, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "utilisateur_creation" character varying(255) NOT NULL DEFAULT 'system', "date_modification" TIMESTAMP, "utilisateur_modification" character varying(255), CONSTRAINT "PK_32ac3cd1926629ca8aba7ebf1d6" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_ref_role_code" ON "ref_role" ("code_role") `,
    );
    await queryRunner.query(
      `CREATE TABLE "bridge_user_role" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "fk_user" bigint NOT NULL, "fk_role" bigint NOT NULL, "perimetre_type" character varying(20), "perimetre_id" bigint, "date_debut_validite" date, "date_fin_validite" date, "est_actif" boolean NOT NULL DEFAULT true, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "utilisateur_creation" character varying(255) NOT NULL DEFAULT 'system', "date_modification" TIMESTAMP, "utilisateur_modification" character varying(255), CONSTRAINT "ck_bridge_user_role_perimetre_type" CHECK ("perimetre_type" IS NULL OR "perimetre_type" IN ('global','structure','centre_responsabilite')), CONSTRAINT "PK_b4784a361d1323403b175ca354f" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_bridge_user_role_role" ON "bridge_user_role" ("fk_role") `,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_bridge_user_role_user" ON "bridge_user_role" ("fk_user") `,
    );
    await queryRunner.query(
      `CREATE TABLE "user" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "email" character varying(255) NOT NULL, "mot_de_passe_hash" character varying(255) NOT NULL, "nom" character varying(100) NOT NULL, "prenom" character varying(100) NOT NULL, "est_actif" boolean NOT NULL DEFAULT true, "date_derniere_connexion" TIMESTAMP, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "utilisateur_creation" character varying(255) NOT NULL DEFAULT 'system', "date_modification" TIMESTAMP, "utilisateur_modification" character varying(255), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_user_email" ON "user" ("email") `,
    );
    await queryRunner.query(
      `ALTER TABLE "bridge_role_permission" ADD CONSTRAINT "FK_66e14b7f7ca62704726c00890c5" FOREIGN KEY ("fk_role") REFERENCES "ref_role"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "bridge_role_permission" ADD CONSTRAINT "FK_fb955a96ea912d16a717af5d6e6" FOREIGN KEY ("fk_permission") REFERENCES "ref_permission"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "bridge_user_role" ADD CONSTRAINT "FK_f1a38e766fa701b63451c943228" FOREIGN KEY ("fk_user") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "bridge_user_role" ADD CONSTRAINT "FK_d79cbebda1150b1540e576af9e5" FOREIGN KEY ("fk_role") REFERENCES "ref_role"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );

    // --- Ajustements manuels (cf. docs/modele-donnees.md §8) ---

    // 1. PK : passer de GENERATED BY DEFAULT à GENERATED ALWAYS AS IDENTITY
    //    pour respecter strictement la convention "bigint generated always as identity".
    await queryRunner.query(
      `ALTER TABLE "user" ALTER COLUMN "id" SET GENERATED ALWAYS`,
    );
    await queryRunner.query(
      `ALTER TABLE "ref_role" ALTER COLUMN "id" SET GENERATED ALWAYS`,
    );
    await queryRunner.query(
      `ALTER TABLE "ref_permission" ALTER COLUMN "id" SET GENERATED ALWAYS`,
    );
    await queryRunner.query(
      `ALTER TABLE "bridge_role_permission" ALTER COLUMN "id" SET GENERATED ALWAYS`,
    );
    await queryRunner.query(
      `ALTER TABLE "bridge_user_role" ALTER COLUMN "id" SET GENERATED ALWAYS`,
    );

    // 2. Unicité (fk_user, fk_role, perimetre_type, perimetre_id) sur bridge_user_role
    //    avec gestion des NULL : deux index uniques partiels.
    //    - Cas global : perimetre_id NULL → un seul rôle global par (user, role).
    //    - Cas avec périmètre : perimetre_id non NULL → un seul rôle par (user, role, type, id).
    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_bridge_user_role_global" ON "bridge_user_role" ("fk_user", "fk_role") WHERE "perimetre_id" IS NULL`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_bridge_user_role_perimetre" ON "bridge_user_role" ("fk_user", "fk_role", "perimetre_type", "perimetre_id") WHERE "perimetre_id" IS NOT NULL`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."uq_bridge_user_role_perimetre"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."uq_bridge_user_role_global"`,
    );
    await queryRunner.query(
      `ALTER TABLE "bridge_user_role" DROP CONSTRAINT "FK_d79cbebda1150b1540e576af9e5"`,
    );
    await queryRunner.query(
      `ALTER TABLE "bridge_user_role" DROP CONSTRAINT "FK_f1a38e766fa701b63451c943228"`,
    );
    await queryRunner.query(
      `ALTER TABLE "bridge_role_permission" DROP CONSTRAINT "FK_fb955a96ea912d16a717af5d6e6"`,
    );
    await queryRunner.query(
      `ALTER TABLE "bridge_role_permission" DROP CONSTRAINT "FK_66e14b7f7ca62704726c00890c5"`,
    );
    await queryRunner.query(`DROP INDEX "public"."uq_user_email"`);
    await queryRunner.query(`DROP TABLE "user"`);
    await queryRunner.query(`DROP INDEX "public"."ix_bridge_user_role_user"`);
    await queryRunner.query(`DROP INDEX "public"."ix_bridge_user_role_role"`);
    await queryRunner.query(`DROP TABLE "bridge_user_role"`);
    await queryRunner.query(`DROP INDEX "public"."uq_ref_role_code"`);
    await queryRunner.query(`DROP TABLE "ref_role"`);
    await queryRunner.query(
      `DROP INDEX "public"."ix_bridge_role_permission_role"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."ix_bridge_role_permission_permission"`,
    );
    await queryRunner.query(`DROP TABLE "bridge_role_permission"`);
    await queryRunner.query(`DROP INDEX "public"."uq_ref_permission_code"`);
    await queryRunner.query(`DROP TABLE "ref_permission"`);
  }
}
