import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddAuditLog1777388323583 implements MigrationInterface {
  name = 'AddAuditLog1777388323583';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "audit_log" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "date_action" TIMESTAMP NOT NULL DEFAULT now(), "utilisateur" character varying(255) NOT NULL, "ip_source" character varying(45), "user_agent" character varying(500), "type_action" character varying(50) NOT NULL, "entite_cible" character varying(100) NOT NULL, "id_cible" character varying, "payload_avant" jsonb, "payload_apres" jsonb, "commentaire" text, "statut" character varying(20) NOT NULL, "duree_ms" integer, CONSTRAINT "ck_audit_log_statut" CHECK ("statut" IN ('success','failure')), CONSTRAINT "PK_07fefa57f7f5ab8fc3f52b3ed0b" PRIMARY KEY ("id"))`,
    );

    // Aligner sur la convention : bigint GENERATED ALWAYS AS IDENTITY.
    await queryRunner.query(
      `ALTER TABLE "audit_log" ALTER COLUMN "id" SET GENERATED ALWAYS`,
    );

    // Index :
    //  - chronologique (DESC car les requêtes typiques tirent les plus récents en premier)
    //  - (entite_cible, id_cible) : historique d'une entité
    //  - (utilisateur, date_action DESC) : historique par utilisateur
    await queryRunner.query(
      `CREATE INDEX "ix_audit_log_date_action" ON "audit_log" ("date_action" DESC)`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_audit_log_entite_id" ON "audit_log" ("entite_cible", "id_cible")`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_audit_log_utilisateur_date" ON "audit_log" ("utilisateur", "date_action" DESC)`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_audit_log_utilisateur_date"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_audit_log_entite_id"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_audit_log_date_action"`,
    );
    await queryRunner.query(`DROP TABLE "audit_log"`);
  }
}
