import { MigrationInterface, QueryRunner } from "typeorm";

export class AddRefreshToken1777385004582 implements MigrationInterface {
    name = 'AddRefreshToken1777385004582'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "refresh_token" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "fk_user" bigint NOT NULL, "token_hash" character varying(255) NOT NULL, "date_expiration" TIMESTAMP NOT NULL, "date_revocation" TIMESTAMP, "motif_revocation" character varying(50), "ip_emission" character varying(45), "user_agent" character varying(500), "date_creation" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "ck_refresh_token_motif" CHECK ("motif_revocation" IS NULL OR "motif_revocation" IN ('logout','rotation','forced')), CONSTRAINT "PK_b575dd3c21fb0831013c909e7fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_refresh_token_hash" ON "refresh_token" ("token_hash") `);
        await queryRunner.query(`CREATE INDEX "ix_refresh_token_user" ON "refresh_token" ("fk_user") `);
        await queryRunner.query(`ALTER TABLE "refresh_token" ADD CONSTRAINT "FK_45a1382fea6ad8fb9104c6ed77f" FOREIGN KEY ("fk_user") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);

        // Aligner sur la convention "bigint GENERATED ALWAYS AS IDENTITY"
        await queryRunner.query(`ALTER TABLE "refresh_token" ALTER COLUMN "id" SET GENERATED ALWAYS`);

        // Index partiel : tokens encore actifs (non révoqués), pour accélérer les
        // recherches "tous les refresh actifs d'un utilisateur" lors des révocations.
        await queryRunner.query(
            `CREATE INDEX "ix_refresh_token_active" ON "refresh_token" ("fk_user") WHERE "date_revocation" IS NULL`
        );
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."ix_refresh_token_active"`);
        await queryRunner.query(`ALTER TABLE "refresh_token" DROP CONSTRAINT "FK_45a1382fea6ad8fb9104c6ed77f"`);
        await queryRunner.query(`DROP INDEX "public"."ix_refresh_token_user"`);
        await queryRunner.query(`DROP INDEX "public"."uq_refresh_token_hash"`);
        await queryRunner.query(`DROP TABLE "refresh_token"`);
    }

}
