import { MigrationInterface, QueryRunner } from 'typeorm';
import {
  dropScd2Indexes,
  enforceAlwaysIdentity,
  scd2Columns,
  scd2Indexes,
} from '../common/migrations/scd2-helpers';

export class CreateDimCentreResponsabilite1777850000000 implements MigrationInterface {
  name = 'CreateDimCentreResponsabilite1777850000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "dim_centre_responsabilite" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "code_cr" varchar(50) NOT NULL,
        "libelle" varchar(200) NOT NULL,
        "libelle_court" varchar(50),
        "type_cr" varchar(20) NOT NULL,
        "fk_structure" bigint NOT NULL,
        ${scd2Columns()},
        CONSTRAINT "ck_dim_cr_type_cr" CHECK (
          "type_cr" IN ('cdc','cdp','cdr','autre')
        ),
        CONSTRAINT "PK_dim_centre_responsabilite" PRIMARY KEY ("id"),
        CONSTRAINT "FK_dim_cr_structure" FOREIGN KEY ("fk_structure")
          REFERENCES "dim_structure"("id") ON DELETE RESTRICT ON UPDATE NO ACTION
      )
    `);

    await queryRunner.query(enforceAlwaysIdentity('dim_centre_responsabilite'));

    // Index SCD2 standards (incluant l'unique partiel `uq_dim_cr_courante`).
    for (const sql of scd2Indexes('dim_centre_responsabilite', 'code_cr')) {
      await queryRunner.query(sql);
    }

    // 2ᵉ ligne de défense contre les doublons intra-jour
    // (cf. fix 2.3A.1 sur dim_structure).
    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_dim_cr_business_date" ON "dim_centre_responsabilite" ("code_cr", "date_debut_validite")`,
    );

    // Index hiérarchie applicative.
    await queryRunner.query(
      `CREATE INDEX "ix_dim_cr_structure" ON "dim_centre_responsabilite" ("fk_structure")`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_dim_cr_type_cr" ON "dim_centre_responsabilite" ("type_cr")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_dim_cr_type_cr"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_dim_cr_structure"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."uq_dim_cr_business_date"`,
    );
    for (const sql of dropScd2Indexes('dim_centre_responsabilite')) {
      await queryRunner.query(sql);
    }
    await queryRunner.query(
      `ALTER TABLE "dim_centre_responsabilite" DROP CONSTRAINT IF EXISTS "FK_dim_cr_structure"`,
    );
    await queryRunner.query(`DROP TABLE "dim_centre_responsabilite"`);
  }
}
