import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateDimScenario1778010000000 implements MigrationInterface {
  name = 'CreateDimScenario1778010000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "dim_scenario" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "code_scenario" varchar(50) NOT NULL,
        "libelle" varchar(200) NOT NULL,
        "type_scenario" varchar(20) NOT NULL,
        "statut" varchar(20) NOT NULL DEFAULT 'actif',
        "commentaire" text,
        "date_creation" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "utilisateur_creation" varchar(255) NOT NULL DEFAULT 'system',
        "date_modification" timestamp,
        "utilisateur_modification" varchar(255),
        CONSTRAINT "ck_dim_scenario_type" CHECK ("type_scenario" IN ('central','optimiste','pessimiste','alternatif')),
        CONSTRAINT "ck_dim_scenario_statut" CHECK ("statut" IN ('actif','archive')),
        CONSTRAINT "PK_dim_scenario" PRIMARY KEY ("id")
      )
    `);

    await queryRunner.query(
      `ALTER TABLE "dim_scenario" ALTER COLUMN "id" SET GENERATED ALWAYS`,
    );

    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_dim_scenario_code" ON "dim_scenario" ("code_scenario")`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_dim_scenario_statut" ON "dim_scenario" ("statut")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_dim_scenario_statut"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."uq_dim_scenario_code"`,
    );
    await queryRunner.query(`DROP TABLE "dim_scenario"`);
  }
}
