import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateRefTauxChange1778020000000 implements MigrationInterface {
  name = 'CreateRefTauxChange1778020000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "ref_taux_change" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "fk_devise" bigint NOT NULL,
        "fk_temps" bigint NOT NULL,
        "taux_vers_pivot" numeric(18,8) NOT NULL,
        "source" varchar(50) NOT NULL DEFAULT 'BCEAO',
        "type_taux" varchar(30) NOT NULL,
        "date_creation" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "utilisateur_creation" varchar(255) NOT NULL DEFAULT 'system',
        CONSTRAINT "ck_ref_taux_change_taux_positif" CHECK ("taux_vers_pivot" > 0),
        CONSTRAINT "ck_ref_taux_change_type" CHECK ("type_taux" IN ('cloture','moyen_mensuel','fixe_budgetaire')),
        CONSTRAINT "PK_ref_taux_change" PRIMARY KEY ("id"),
        CONSTRAINT "FK_ref_taux_change_devise" FOREIGN KEY ("fk_devise")
          REFERENCES "dim_devise"("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
        CONSTRAINT "FK_ref_taux_change_temps" FOREIGN KEY ("fk_temps")
          REFERENCES "dim_temps"("id") ON DELETE RESTRICT ON UPDATE NO ACTION
      )
    `);

    await queryRunner.query(
      `ALTER TABLE "ref_taux_change" ALTER COLUMN "id" SET GENERATED ALWAYS`,
    );

    // Invariant CRITIQUE (cf. modele-donnees.md §5.1) : un seul taux
    // par triplet (devise, date, type).
    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_ref_taux_change_triplet" ON "ref_taux_change" ("fk_devise", "fk_temps", "type_taux")`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_ref_taux_change_devise" ON "ref_taux_change" ("fk_devise")`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_ref_taux_change_temps" ON "ref_taux_change" ("fk_temps")`,
    );
    // Index pour `findTauxApplicable` : (devise, type) avec ordre par
    // temps DESC, exploité par la requête du service.
    await queryRunner.query(
      `CREATE INDEX "ix_ref_taux_change_devise_type" ON "ref_taux_change" ("fk_devise", "type_taux")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_ref_taux_change_devise_type"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_ref_taux_change_temps"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_ref_taux_change_devise"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."uq_ref_taux_change_triplet"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ref_taux_change" DROP CONSTRAINT IF EXISTS "FK_ref_taux_change_temps"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ref_taux_change" DROP CONSTRAINT IF EXISTS "FK_ref_taux_change_devise"`,
    );
    await queryRunner.query(`DROP TABLE "ref_taux_change"`);
  }
}
