import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * `fait_budget` — table de faits centrale du module élaboration
 * budgétaire (cf. `docs/modele-donnees.md` §4.1).
 *
 * **Écart intentionnel au modele-donnees §4.1** : les FK
 * `fk_ligne_metier`, `fk_produit`, `fk_segment` sont rendues
 * **NOT NULL** (le doc les déclarait nullable avec ligne sentinelle
 * `id=0 NA`). Justification :
 *  a) Les 3 dimensions ont leur seed pédagogique en place (Lot 2.4).
 *  b) Une ligne sentinelle id=0 demande une migration séparée et
 *     complique l'invariant UNIQUE composite de grain.
 *  c) Extension non-cassante en V2 si le besoin émerge en saisie
 *     réelle (relâcher NOT NULL + ajouter sentinelle).
 *
 * Le doc §4.1 sera aligné sur ce choix au Lot 3.6 (doc fin de Lot 3).
 *
 * **Choix architectural Option B (cf. modele-donnees.md §6.3)** :
 * les FK SCD2 pointent vers la version VALIDE À LA DATE MÉTIER (date
 * portée par `fk_temps`), PAS vers la version courante au moment de
 * l'INSERT. Cette résolution est APPLICATIVE (service Lot 3.2B), pas
 * exprimable en CHECK constraint Postgres sans trigger.
 *
 * **Volumétrie cible** : 5M lignes par version. Index essentiels.
 */
export class CreateFaitBudget1778100000000 implements MigrationInterface {
  name = 'CreateFaitBudget1778100000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "fait_budget" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "fk_temps" bigint NOT NULL,
        "fk_compte" bigint NOT NULL,
        "fk_structure" bigint NOT NULL,
        "fk_centre" bigint NOT NULL,
        "fk_ligne_metier" bigint NOT NULL,
        "fk_produit" bigint NOT NULL,
        "fk_segment" bigint NOT NULL,
        "fk_devise" bigint NOT NULL,
        "fk_version" bigint NOT NULL,
        "fk_scenario" bigint NOT NULL,
        "montant_devise" numeric(20,4) NOT NULL,
        "montant_fcfa" numeric(20,4) NOT NULL,
        "taux_change_applique" numeric(18,8) NOT NULL,
        "date_creation" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "utilisateur_creation" varchar(255) NOT NULL,
        "date_modification" timestamp,
        "utilisateur_modification" varchar(255),
        CONSTRAINT "ck_fait_budget_taux_positif" CHECK ("taux_change_applique" > 0),
        CONSTRAINT "PK_fait_budget" PRIMARY KEY ("id"),
        CONSTRAINT "FK_fait_budget_temps" FOREIGN KEY ("fk_temps")
          REFERENCES "dim_temps"("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
        CONSTRAINT "FK_fait_budget_compte" FOREIGN KEY ("fk_compte")
          REFERENCES "dim_compte"("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
        CONSTRAINT "FK_fait_budget_structure" FOREIGN KEY ("fk_structure")
          REFERENCES "dim_structure"("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
        CONSTRAINT "FK_fait_budget_centre" FOREIGN KEY ("fk_centre")
          REFERENCES "dim_centre_responsabilite"("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
        CONSTRAINT "FK_fait_budget_ligne_metier" FOREIGN KEY ("fk_ligne_metier")
          REFERENCES "dim_ligne_metier"("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
        CONSTRAINT "FK_fait_budget_produit" FOREIGN KEY ("fk_produit")
          REFERENCES "dim_produit"("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
        CONSTRAINT "FK_fait_budget_segment" FOREIGN KEY ("fk_segment")
          REFERENCES "dim_segment"("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
        CONSTRAINT "FK_fait_budget_devise" FOREIGN KEY ("fk_devise")
          REFERENCES "dim_devise"("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
        CONSTRAINT "FK_fait_budget_version" FOREIGN KEY ("fk_version")
          REFERENCES "dim_version"("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
        CONSTRAINT "FK_fait_budget_scenario" FOREIGN KEY ("fk_scenario")
          REFERENCES "dim_scenario"("id") ON DELETE RESTRICT ON UPDATE NO ACTION
      )
    `);

    await queryRunner.query(
      `ALTER TABLE "fait_budget" ALTER COLUMN "id" SET GENERATED ALWAYS`,
    );

    // Index simples sur chacune des 10 FK (cf. modele-donnees §7.1).
    for (const col of [
      'temps',
      'compte',
      'structure',
      'centre',
      'ligne_metier',
      'produit',
      'segment',
      'devise',
      'version',
      'scenario',
    ]) {
      await queryRunner.query(
        `CREATE INDEX "ix_fait_budget_${col}" ON "fait_budget" ("fk_${col}")`,
      );
    }

    // Invariant CRITIQUE : un seul fait par grain métier (10-uplet).
    await queryRunner.query(`
      CREATE UNIQUE INDEX "uq_fait_budget_grain"
      ON "fait_budget" (
        "fk_temps", "fk_compte", "fk_structure", "fk_centre",
        "fk_ligne_metier", "fk_produit", "fk_segment",
        "fk_devise", "fk_version", "fk_scenario"
      )
    `);

    // Index composites pour requêtes de reporting Lot 5
    // (cf. modele-donnees §7.2).
    await queryRunner.query(
      `CREATE INDEX "ix_fait_budget_version_temps" ON "fait_budget" ("fk_version", "fk_temps")`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_fait_budget_version_centre_temps" ON "fait_budget" ("fk_version", "fk_centre", "fk_temps")`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_fait_budget_temps_compte" ON "fait_budget" ("fk_temps", "fk_compte")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_fait_budget_temps_compte"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_fait_budget_version_centre_temps"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_fait_budget_version_temps"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."uq_fait_budget_grain"`,
    );
    for (const col of [
      'temps',
      'compte',
      'structure',
      'centre',
      'ligne_metier',
      'produit',
      'segment',
      'devise',
      'version',
      'scenario',
    ]) {
      await queryRunner.query(
        `DROP INDEX IF EXISTS "public"."ix_fait_budget_${col}"`,
      );
    }
    for (const fk of [
      'temps',
      'compte',
      'structure',
      'centre',
      'ligne_metier',
      'produit',
      'segment',
      'devise',
      'version',
      'scenario',
    ]) {
      await queryRunner.query(
        `ALTER TABLE "fait_budget" DROP CONSTRAINT IF EXISTS "FK_fait_budget_${fk}"`,
      );
    }
    await queryRunner.query(`DROP TABLE "fait_budget"`);
  }
}
