import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateDimVersion1778000000000 implements MigrationInterface {
  name = 'CreateDimVersion1778000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "dim_version" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "code_version" varchar(50) NOT NULL,
        "libelle" varchar(200) NOT NULL,
        "type_version" varchar(30) NOT NULL,
        "exercice_fiscal" int NOT NULL,
        "statut" varchar(20) NOT NULL DEFAULT 'ouvert',
        "date_gel" timestamp,
        "utilisateur_gel" varchar(255),
        "commentaire" text,
        "date_creation" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "utilisateur_creation" varchar(255) NOT NULL DEFAULT 'system',
        "date_modification" timestamp,
        "utilisateur_modification" varchar(255),
        CONSTRAINT "ck_dim_version_type" CHECK ("type_version" IN ('budget_initial','reforecast_1','reforecast_2','atterrissage')),
        CONSTRAINT "ck_dim_version_statut" CHECK ("statut" IN ('ouvert','soumis','valide','gele')),
        CONSTRAINT "ck_dim_version_exercice" CHECK ("exercice_fiscal" BETWEEN 2020 AND 2050),
        CONSTRAINT "PK_dim_version" PRIMARY KEY ("id")
      )
    `);

    await queryRunner.query(
      `ALTER TABLE "dim_version" ALTER COLUMN "id" SET GENERATED ALWAYS`,
    );

    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_dim_version_code" ON "dim_version" ("code_version")`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_dim_version_exercice_statut" ON "dim_version" ("exercice_fiscal", "statut")`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_dim_version_type" ON "dim_version" ("type_version")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS "public"."ix_dim_version_type"`);
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."ix_dim_version_exercice_statut"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."uq_dim_version_code"`,
    );
    await queryRunner.query(`DROP TABLE "dim_version"`);
  }
}
