import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Lot 4.1.A — Modèle N-N user ↔ périmètre.
 *
 * Aujourd'hui, le périmètre d'un utilisateur est porté par
 * `bridge_user_role.perimetre_type` / `perimetre_id` (Lot 1) — un user
 * peut donc déjà avoir plusieurs périmètres si plusieurs rôles, mais
 * la sémantique est mélangée avec celle des rôles RBAC. Le Lot 4.1
 * sépare proprement les deux dimensions :
 *   - bridge_user_role → rôles + permissions (inchangé)
 *   - user_perimetres  → liste explicite des périmètres budgétaires
 *
 * 3 cible_type (décision produit D1) :
 *   - STRUCTURE : descente d'arborescence (BFS itératif via fk_structure_parent)
 *   - CR        : un seul centre de responsabilité (pas de descente)
 *   - CR_SET    : liste explicite ≥ 2 CR (pas de descente)
 *
 * Backfill : pour chaque ligne `bridge_user_role` active dont
 * `perimetre_type IN ('structure','centre_responsabilite')`, on
 * recopie une ligne user_perimetres avec origine='PRINCIPAL'. Les
 * rôles globaux (perimetre_type='global' ou NULL) NE génèrent PAS
 * de ligne — un admin global est détecté par l'absence de ligne
 * user_perimetres ET la présence d'un bridge_user_role 'global'
 * (cf. PerimetreService).
 *
 * Note : pas de FK delegations() — la table sera créée au Lot 4.2,
 * la colonne `delegation_id` est juste UUID-stringifié sans
 * contrainte référentielle pour l'instant (dette tracée).
 */
export class AjoutUserPerimetres1779200000080 implements MigrationInterface {
  name = 'AjoutUserPerimetres1779200000080';

  public async up(q: QueryRunner): Promise<void> {
    // Table user_perimetres
    await q.query(`
      CREATE TABLE "user_perimetres" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "fk_user" bigint NOT NULL,
        "cible_type" varchar(20) NOT NULL,
        "cible_id" bigint NULL,
        "cible_cr_ids" bigint[] NULL,
        "origine" varchar(30) NOT NULL DEFAULT 'PRINCIPAL',
        "delegation_id" bigint NULL,
        "date_debut" date NOT NULL DEFAULT CURRENT_DATE,
        "date_fin" date NULL,
        "actif" boolean NOT NULL DEFAULT true,
        "motif" text NULL,
        "date_creation" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "utilisateur_creation" varchar(255) NOT NULL DEFAULT 'system',
        "date_modification" timestamp NULL,
        "utilisateur_modification" varchar(255) NULL,
        CONSTRAINT "fk_user_perimetres_user"
          FOREIGN KEY ("fk_user") REFERENCES "user"("id") ON DELETE CASCADE,
        CONSTRAINT "ck_user_perimetres_cible_type"
          CHECK ("cible_type" IN ('STRUCTURE','CR','CR_SET')),
        CONSTRAINT "ck_user_perimetres_origine"
          CHECK ("origine" IN ('PRINCIPAL','AFFECTATION','DELEGATION')),
        CONSTRAINT "ck_user_perimetres_cible_coherence"
          CHECK (
            (
              "cible_type" IN ('STRUCTURE','CR')
              AND "cible_id" IS NOT NULL
              AND "cible_cr_ids" IS NULL
            )
            OR
            (
              "cible_type" = 'CR_SET'
              AND "cible_id" IS NULL
              AND "cible_cr_ids" IS NOT NULL
              AND array_length("cible_cr_ids", 1) >= 2
            )
          )
      )
    `);

    // Index principaux
    await q.query(`
      CREATE INDEX "idx_user_perimetres_user_actif"
        ON "user_perimetres" ("fk_user", "actif")
    `);
    await q.query(`
      CREATE INDEX "idx_user_perimetres_cible"
        ON "user_perimetres" ("cible_type", "cible_id")
    `);
    // Index GIN pour la recherche sur les listes CR_SET
    await q.query(`
      CREATE INDEX "idx_user_perimetres_cr_set"
        ON "user_perimetres" USING GIN ("cible_cr_ids")
    `);
    // Unique partielle : empêche la duplication d'une affectation
    // STRUCTURE/CR active de même origine pour le même user
    // (CR_SET exclu car un même user peut légitimement cumuler plusieurs
    // sets distincts).
    await q.query(`
      CREATE UNIQUE INDEX "uq_user_perimetres_actif"
        ON "user_perimetres" ("fk_user", "cible_type", "cible_id", "origine")
        WHERE "actif" = true AND "cible_type" IN ('STRUCTURE','CR')
    `);

    // Backfill depuis bridge_user_role (rôles avec périmètre)
    await q.query(`
      INSERT INTO "user_perimetres"
        ("fk_user", "cible_type", "cible_id", "origine",
         "date_debut", "date_fin", "actif", "utilisateur_creation",
         "motif")
      SELECT
        bur."fk_user",
        CASE
          WHEN bur."perimetre_type" = 'structure' THEN 'STRUCTURE'
          WHEN bur."perimetre_type" = 'centre_responsabilite' THEN 'CR'
        END AS cible_type,
        bur."perimetre_id" AS cible_id,
        'PRINCIPAL' AS origine,
        COALESCE(bur."date_debut_validite", CURRENT_DATE) AS date_debut,
        bur."date_fin_validite" AS date_fin,
        bur."est_actif" AS actif,
        'system (backfill 4.1)' AS utilisateur_creation,
        'Migration Lot 4.1 — recopié depuis bridge_user_role' AS motif
      FROM "bridge_user_role" bur
      WHERE bur."perimetre_type" IN ('structure','centre_responsabilite')
        AND bur."perimetre_id" IS NOT NULL
        AND bur."est_actif" = true
      ON CONFLICT DO NOTHING
    `);
  }

  public async down(q: QueryRunner): Promise<void> {
    await q.query(`DROP TABLE IF EXISTS "user_perimetres"`);
  }
}
