import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Lot 4.2 — Table `delegations` + permissions DELEGATION + FK
 * `user_perimetres.delegation_id` posée pour la 1re fois.
 *
 * Délégations temporaires de droits :
 *   un délégant `D` accorde à un délégataire `R` la possibilité
 *   d'effectuer certaines actions (SAISIE / SOUMISSION /
 *   VALIDATION / PUBLICATION) sur un sous-ensemble de ses
 *   périmètres `user_perimetres`, pendant une période bornée.
 *
 * Décision produit D2 (NON NÉGOCIABLE) — anti-chaînage strict :
 *   si A délègue à B, B ne peut PAS re-déléguer à C cette
 *   permission-là. La vérification est faite côté
 *   `DelegationService.creer` en lisant `user_perimetres.origine`.
 *   La table elle-même ne contraint pas le chaînage (la donnée
 *   anti-chaînage vit côté `user_perimetres.origine='DELEGATION'`).
 *
 * Idempotence :
 *  - `CREATE TABLE IF NOT EXISTS` pour la table
 *  - `ON CONFLICT DO NOTHING` pour les permissions
 *  - `INSERT … WHERE NOT EXISTS` pour les bridges
 *  - `IF NOT EXISTS` pour les index
 *  - FK `fk_user_perimetres_delegation` ajoutée seulement si
 *    elle n'existe pas (vérification information_schema).
 */
export class CreerTableDelegations1779200000120 implements MigrationInterface {
  name = 'CreerTableDelegations1779200000120';

  public async up(q: QueryRunner): Promise<void> {
    // ─── 1. Table delegations ───────────────────────────────────────
    await q.query(`
      CREATE TABLE IF NOT EXISTS "delegations" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "fk_delegant" bigint NOT NULL,
        "fk_delegataire" bigint NOT NULL,
        "perimetre_user_perimetre_ids" bigint[] NOT NULL,
        "permissions" text[] NOT NULL,
        "motif" text NOT NULL,
        "date_debut" date NOT NULL,
        "date_fin" date NOT NULL,
        "actif" boolean NOT NULL DEFAULT true,
        "revoquee_le" timestamp NULL,
        "fk_revoque_par" bigint NULL,
        "motif_revocation" text NULL,
        "date_creation" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "utilisateur_creation" varchar(255) NOT NULL DEFAULT 'system',
        "date_modification" timestamp NULL,
        "utilisateur_modification" varchar(255) NULL,
        CONSTRAINT "fk_delegations_delegant"
          FOREIGN KEY ("fk_delegant") REFERENCES "user"("id") ON DELETE RESTRICT,
        CONSTRAINT "fk_delegations_delegataire"
          FOREIGN KEY ("fk_delegataire") REFERENCES "user"("id") ON DELETE RESTRICT,
        CONSTRAINT "fk_delegations_revoque_par"
          FOREIGN KEY ("fk_revoque_par") REFERENCES "user"("id") ON DELETE SET NULL,
        CONSTRAINT "chk_delegation_diff_users"
          CHECK ("fk_delegant" <> "fk_delegataire"),
        CONSTRAINT "chk_delegation_dates"
          CHECK ("date_fin" >= "date_debut"),
        CONSTRAINT "chk_delegation_perimetres_non_vide"
          CHECK (array_length("perimetre_user_perimetre_ids", 1) >= 1),
        CONSTRAINT "chk_delegation_permissions_valides"
          CHECK (
            "permissions" <@ ARRAY['SAISIE','SOUMISSION','VALIDATION','PUBLICATION']
            AND array_length("permissions", 1) >= 1
          )
      )
    `);

    // ─── 2. Index ──────────────────────────────────────────────────
    await q.query(`
      CREATE INDEX IF NOT EXISTS "idx_delegations_delegant_actif"
        ON "delegations" ("fk_delegant", "actif")
    `);
    await q.query(`
      CREATE INDEX IF NOT EXISTS "idx_delegations_delegataire_actif"
        ON "delegations" ("fk_delegataire", "actif")
    `);
    await q.query(`
      CREATE INDEX IF NOT EXISTS "idx_delegations_dates"
        ON "delegations" ("date_debut", "date_fin")
        WHERE "actif" = true
    `);

    // ─── 3. Permissions DELEGATION ─────────────────────────────────
    await q.query(`
      INSERT INTO "ref_permission" ("code_permission", "libelle", "description", "module", "utilisateur_creation")
      VALUES
        ('DELEGATION.LIRE',
         'Consulter ses délégations',
         'Lister les délégations dont l''utilisateur est délégant ou délégataire (Lot 4.2).',
         'DELEGATION', 'system (Lot 4.2)'),
        ('DELEGATION.GERER',
         'Gérer les délégations (admin)',
         'Lister, révoquer, et auditer toutes les délégations (Lot 4.2). Permission admin globale — la création reste accessible à tout user authentifié pour ses propres délégations.',
         'DELEGATION', 'system (Lot 4.2)')
      ON CONFLICT ("code_permission") DO NOTHING
    `);

    // ─── 4. bridge_role_permission : attribution ───────────────────
    // ADMIN : DELEGATION.LIRE + DELEGATION.GERER
    // Tous les rôles métier (SAISISSEUR/VALIDATEUR/PUBLICATEUR/AUDITEUR) +
    //   LECTEUR : DELEGATION.LIRE (pour consulter leurs délégations).
    // Pas d'index UNIQUE sur (fk_role, fk_permission) → pattern
    // WHERE NOT EXISTS scalaire (cf. Lot 4.1-fix3).
    const ATTRIBUTIONS: Array<[string, string]> = [
      ['ADMIN', 'DELEGATION.LIRE'],
      ['ADMIN', 'DELEGATION.GERER'],
      ['LECTEUR', 'DELEGATION.LIRE'],
      ['SAISISSEUR', 'DELEGATION.LIRE'],
      ['VALIDATEUR', 'DELEGATION.LIRE'],
      ['PUBLICATEUR', 'DELEGATION.LIRE'],
      ['AUDITEUR', 'DELEGATION.LIRE'],
    ];
    for (const [roleCode, permCode] of ATTRIBUTIONS) {
      const roleRows = (await q.query(
        `SELECT "id" FROM "ref_role" WHERE "code_role" = $1`,
        [roleCode],
      )) as Array<{ id: string }>;
      const permRows = (await q.query(
        `SELECT "id" FROM "ref_permission" WHERE "code_permission" = $1`,
        [permCode],
      )) as Array<{ id: string }>;
      if (roleRows.length === 0 || permRows.length === 0) continue;
      await q.query(
        `INSERT INTO "bridge_role_permission" ("fk_role", "fk_permission")
         SELECT $1::bigint, $2::bigint
         WHERE NOT EXISTS (
           SELECT 1 FROM "bridge_role_permission"
            WHERE "fk_role" = $1::bigint AND "fk_permission" = $2::bigint
         )`,
        [roleRows[0]!.id, permRows[0]!.id],
      );
    }

    // ─── 5. FK user_perimetres.delegation_id ───────────────────────
    // La colonne existe depuis Lot 4.1.A (bigint NULL sans contrainte
    // référentielle). On pose la FK maintenant que `delegations` existe.
    const fkExists = (await q.query(
      `SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_user_perimetres_delegation'`,
    )) as Array<unknown>;
    if (fkExists.length === 0) {
      await q.query(`
        ALTER TABLE "user_perimetres"
          ADD CONSTRAINT "fk_user_perimetres_delegation"
          FOREIGN KEY ("delegation_id") REFERENCES "delegations"("id")
          ON DELETE SET NULL
      `);
    }
  }

  public async down(q: QueryRunner): Promise<void> {
    await q.query(`
      ALTER TABLE "user_perimetres"
        DROP CONSTRAINT IF EXISTS "fk_user_perimetres_delegation"
    `);
    // Retirer les bridges DELEGATION (sécuritaire — recréés à up).
    await q.query(`
      DELETE FROM "bridge_role_permission"
       WHERE "fk_permission" IN (
         SELECT "id" FROM "ref_permission"
          WHERE "code_permission" IN ('DELEGATION.LIRE','DELEGATION.GERER')
       )
    `);
    await q.query(`
      DELETE FROM "ref_permission"
       WHERE "code_permission" IN ('DELEGATION.LIRE','DELEGATION.GERER')
    `);
    await q.query(`DROP TABLE IF EXISTS "delegations"`);
  }
}
