import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Lot B1 — Configuration banque externalisée (multi-banques).
 *
 * Crée :
 *  - `configuration_banque` : table MONO-LIGNE (CHECK id = 1) portant
 *    l'identité institutionnelle + charte + contexte IA.
 *  - `configuration_banque_membre_comite` : membres du Comité Budgétaire.
 *  - Code audit `CONFIGURATION_BANQUE_MODIFIEE` (ref_type_action_audit).
 *  - Permission `BANQUE.GERER` (ref_permission, module CONFIGURATION) +
 *    attribution au rôle ADMIN.
 *
 * Seed : valeurs BSIC NIGER (adresse « Boulevard de la Liberté, BP 12 080 »
 * alignée sur les bordereaux R3/R5 existants) + 5 membres du Comité.
 * Tous les INSERT sont idempotents (ON CONFLICT DO NOTHING / NOT EXISTS).
 */
interface RoleRow {
  id: string;
}

export class CreerConfigurationBanque1779200000590 implements MigrationInterface {
  name = 'CreerConfigurationBanque1779200000590';

  public async up(q: QueryRunner): Promise<void> {
    // ─── 1. Table configuration_banque (mono-ligne) ───────────────
    await q.query(`
      CREATE TABLE IF NOT EXISTS "configuration_banque" (
        "id" bigint PRIMARY KEY,
        "nom" varchar(200) NOT NULL,
        "sigle" varchar(50) NOT NULL,
        "nom_commercial_complet" text,
        "forme_juridique" varchar(50),
        "groupe" varchar(200),
        "siege_social" text,
        "ville_siege" varchar(100),
        "pays" varchar(100),
        "telephone" varchar(50),
        "email_contact" varchar(255),
        "ref_reglementaire_bceao" varchar(255),
        "exercice_fiscal_libelle" varchar(100),
        "couleur_primaire" varchar(7) NOT NULL,
        "couleur_primaire_dark" varchar(7) NOT NULL,
        "couleur_secondaire" varchar(7) NOT NULL,
        "logo_ref" varchar(500),
        "contexte_marche" text,
        "concurrents" varchar(500),
        "positionnement" text,
        "date_creation" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "utilisateur_creation" varchar(255) NOT NULL DEFAULT 'system',
        "date_modification" timestamp,
        "utilisateur_modification" varchar(255),
        CONSTRAINT "chk_configuration_banque_singleton" CHECK ("id" = 1)
      )
    `);

    // ─── 2. Table membres du Comité ───────────────────────────────
    await q.query(`
      CREATE TABLE IF NOT EXISTS "configuration_banque_membre_comite" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "fk_configuration_banque" bigint NOT NULL,
        "nom_prenom" varchar(200) NOT NULL,
        "titre" varchar(20),
        "fonction" varchar(20) NOT NULL,
        "ordre_affichage" int NOT NULL DEFAULT 0,
        "est_actif" boolean NOT NULL DEFAULT true,
        "date_creation" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "utilisateur_creation" varchar(255) NOT NULL DEFAULT 'system',
        CONSTRAINT "fk_config_banque_membre_config"
          FOREIGN KEY ("fk_configuration_banque")
          REFERENCES "configuration_banque" ("id") ON DELETE CASCADE
      )
    `);
    await q.query(`
      CREATE INDEX IF NOT EXISTS "ix_config_banque_membre_config"
        ON "configuration_banque_membre_comite" ("fk_configuration_banque")
    `);

    // ─── 3. Code audit CONFIGURATION_BANQUE_MODIFIEE ──────────────
    await q.query(`
      INSERT INTO "ref_type_action_audit"
        ("code","libelle","description","ordre","est_systeme","est_actif","utilisateur_creation")
      VALUES
        ('CONFIGURATION_BANQUE_MODIFIEE',
         'Configuration banque modifiée',
         'Modification de la configuration institutionnelle (nom, adresse, charte, membres Comité, contexte IA) via l''UI admin (BANQUE.GERER). Lot B1.',
         640, true, true, 'migration 590')
      ON CONFLICT ("code") DO NOTHING
    `);

    // ─── 4. Permission BANQUE.GERER ───────────────────────────────
    await q.query(`
      INSERT INTO "ref_permission" ("code_permission","libelle","description","module","utilisateur_creation")
      VALUES
        ('BANQUE.GERER',
         'Gérer la configuration de la banque',
         'Modifier les paramètres institutionnels : nom, adresse, membres Comité, couleurs, contexte IA. Lot B1.',
         'CONFIGURATION','migration 590')
      ON CONFLICT ("code_permission") DO NOTHING
    `);

    // ─── 5. Attribution BANQUE.GERER au rôle ADMIN ────────────────
    const adminRows = (await q.query(
      `SELECT id FROM ref_role WHERE code_role = 'ADMIN' LIMIT 1`,
    )) as RoleRow[];
    if (adminRows.length > 0) {
      await q.query(
        `INSERT INTO bridge_role_permission (fk_role, fk_permission)
         SELECT $1::bigint, p.id FROM ref_permission p
         WHERE p.code_permission = 'BANQUE.GERER'
         ON CONFLICT (fk_role, fk_permission) DO NOTHING`,
        [String(adminRows[0]!.id)],
      );
    }

    // ─── 6. Seed configuration BSIC NIGER (id = 1) ────────────────
    await q.query(`
      INSERT INTO "configuration_banque"
        ("id","nom","sigle","nom_commercial_complet","forme_juridique","groupe",
         "siege_social","ville_siege","pays",
         "couleur_primaire","couleur_primaire_dark","couleur_secondaire",
         "utilisateur_creation")
      VALUES
        (1,'BSIC NIGER','BSIC',
         'Banque Sahélo-Saharienne pour l''Investissement et le Commerce',
         'SA','Groupe BSIC S.A. (Tripoli)',
         'Boulevard de la Liberté, BP 12 080','Niamey','Niger',
         '#1B2A4E','#0F1B33','#C49B3F',
         'migration 590')
      ON CONFLICT ("id") DO NOTHING
    `);

    // ─── 7. Seed membres du Comité (idempotent : guard table vide) ─
    await q.query(`
      INSERT INTO "configuration_banque_membre_comite"
        ("fk_configuration_banque","nom_prenom","titre","fonction","ordre_affichage","utilisateur_creation")
      SELECT * FROM (VALUES
        (1,'Souleymane DIORI','M.','PRESIDENT',1,'migration 590'),
        (1,'Halima OUSMANE','Mme','MEMBRE',2,'migration 590'),
        (1,'Ibrahima MAHAMADOU','M.','MEMBRE',3,'migration 590'),
        (1,'Ousmane MAMANE','M.','SECRETAIRE',4,'migration 590'),
        (1,'Issoufou BARRY','M.','DG',5,'migration 590')
      ) AS v(fk, nom, titre, fonction, ordre, ucr)
      WHERE NOT EXISTS (SELECT 1 FROM "configuration_banque_membre_comite")
    `);
  }

  public async down(q: QueryRunner): Promise<void> {
    await q.query(
      `DELETE FROM bridge_role_permission
       WHERE fk_permission IN (
         SELECT id FROM ref_permission WHERE code_permission = 'BANQUE.GERER'
       )`,
    );
    await q.query(
      `DELETE FROM ref_permission WHERE code_permission = 'BANQUE.GERER'`,
    );
    await q.query(
      `DELETE FROM ref_type_action_audit WHERE code = 'CONFIGURATION_BANQUE_MODIFIEE'`,
    );
    await q.query(`DROP TABLE IF EXISTS "configuration_banque_membre_comite"`);
    await q.query(`DROP TABLE IF EXISTS "configuration_banque"`);
  }
}
