import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Chantier C1 — historisation des analyses IA.
 *
 * Crée :
 *  - table `analyse_ia` (contenu markdown + métadonnées + kpi_snapshot) + index.
 *  - permission `AI.HISTORIQUE` (module AI) attribuée à ADMIN et AUDITEUR.
 *  - codes audit `ANALYSE_IA_CONSULTEE` et `ANALYSE_IA_SUPPRIMEE`.
 *
 * Tous les INSERT sont idempotents (IF NOT EXISTS / ON CONFLICT DO NOTHING).
 */
interface RoleRow {
  id: string;
}

export class CreerAnalyseIa1779200000610 implements MigrationInterface {
  name = 'CreerAnalyseIa1779200000610';

  public async up(q: QueryRunner): Promise<void> {
    // ─── 1. Table analyse_ia ──────────────────────────────────────
    await q.query(`
      CREATE TABLE IF NOT EXISTS "analyse_ia" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "fk_user" bigint NOT NULL,
        "date_generation" timestamp NOT NULL,
        "version_id" bigint NOT NULL,
        "scenario_id" bigint NOT NULL,
        "mois_debut" varchar(7) NOT NULL,
        "mois_fin" varchar(7) NOT NULL,
        "crs_selectionnes" jsonb,
        "modele" varchar(60) NOT NULL,
        "prompt_version" varchar(40) NOT NULL,
        "reponse_markdown" text NOT NULL,
        "kpi_snapshot" jsonb,
        "tokens_in" int NOT NULL,
        "tokens_out" int NOT NULL,
        "duree_ms" int NOT NULL,
        "cout_estime" numeric(10,5) NOT NULL,
        "dry_run" boolean NOT NULL,
        "statut" varchar(10) NOT NULL DEFAULT 'success',
        "date_creation" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "utilisateur_creation" varchar(255) NOT NULL DEFAULT 'system'
      )
    `);
    await q.query(`
      CREATE INDEX IF NOT EXISTS "ix_analyse_ia_user_date"
        ON "analyse_ia" ("fk_user", "date_generation" DESC)
    `);
    await q.query(`
      CREATE INDEX IF NOT EXISTS "ix_analyse_ia_version_scenario"
        ON "analyse_ia" ("version_id", "scenario_id")
    `);

    // ─── 2. Codes audit ───────────────────────────────────────────
    await q.query(`
      INSERT INTO "ref_type_action_audit"
        ("code","libelle","description","ordre","est_systeme","est_actif","utilisateur_creation")
      VALUES
        ('ANALYSE_IA_CONSULTEE','Analyse IA consultée',
         'Consultation du detail d''une analyse MIZNAS AI historisee. Chantier C1.',
         660, true, true, 'migration 610'),
        ('ANALYSE_IA_SUPPRIMEE','Analyse IA supprimée',
         'Suppression d''une analyse MIZNAS AI historisee (AI.HISTORIQUE). Chantier C1.',
         661, true, true, 'migration 610')
      ON CONFLICT ("code") DO NOTHING
    `);

    // ─── 3. Permission AI.HISTORIQUE ──────────────────────────────
    await q.query(`
      INSERT INTO "ref_permission" ("code_permission","libelle","description","module","utilisateur_creation")
      VALUES
        ('AI.HISTORIQUE',
         'Consulter tout l''historique des analyses IA',
         'Acces a l''historique complet des analyses MIZNAS AI de tous les utilisateurs (liste, detail, suppression). Chantier C1.',
         'AI','migration 610')
      ON CONFLICT ("code_permission") DO NOTHING
    `);

    // ─── 4. Attribution AI.HISTORIQUE à ADMIN + AUDITEUR ──────────
    const roles = (await q.query(
      `SELECT id FROM ref_role WHERE code_role IN ('ADMIN','AUDITEUR')`,
    )) as RoleRow[];
    for (const role of roles) {
      await q.query(
        `INSERT INTO bridge_role_permission (fk_role, fk_permission)
         SELECT $1::bigint, p.id FROM ref_permission p
         WHERE p.code_permission = 'AI.HISTORIQUE'
         ON CONFLICT (fk_role, fk_permission) DO NOTHING`,
        [String(role.id)],
      );
    }
  }

  public async down(q: QueryRunner): Promise<void> {
    await q.query(
      `DELETE FROM bridge_role_permission
       WHERE fk_permission IN (
         SELECT id FROM ref_permission WHERE code_permission = 'AI.HISTORIQUE'
       )`,
    );
    await q.query(
      `DELETE FROM ref_permission WHERE code_permission = 'AI.HISTORIQUE'`,
    );
    await q.query(
      `DELETE FROM ref_type_action_audit WHERE code IN ('ANALYSE_IA_CONSULTEE','ANALYSE_IA_SUPPRIMEE')`,
    );
    await q.query(`DROP TABLE IF EXISTS "analyse_ia"`);
  }
}
