import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Lot 5.1 — Réalisé (`fait_realise`).
 *
 * Crée la table de faits dédiée au réalisé budgétaire (mensuel),
 * ses permissions RBAC (5 codes REALISE.*), ses codes audit
 * (4 codes verbe-sujet) et l'attribution des permissions par rôle.
 *
 * Décisions produit (Lot 5.1) :
 *  - Q3 : table dédiée (pas de réutilisation de fait_budget).
 *  - Q4 : workflow simple à 2 statuts (IMPORTE → VALIDE).
 *  - Granularité mensuelle (fk_temps = 1er du mois).
 *
 * Idempotente : CREATE TABLE IF NOT EXISTS, ON CONFLICT DO NOTHING
 * pour les permissions / codes audit, INSERT WHERE NOT EXISTS pour
 * les bridges_role_permission (pas d'index UNIQUE en base).
 */
export class CreerFaitRealiseEtPermissions1779200000150
  implements MigrationInterface
{
  name = 'CreerFaitRealiseEtPermissions1779200000150';

  public async up(q: QueryRunner): Promise<void> {
    // ─── 1. Table fait_realise ─────────────────────────────────────
    await q.query(`
      CREATE TABLE IF NOT EXISTS "fait_realise" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "fk_centre_responsabilite" bigint NOT NULL,
        "fk_compte" bigint NOT NULL,
        "fk_ligne_metier" bigint NOT NULL,
        "fk_temps" bigint NOT NULL,
        "fk_devise" bigint NOT NULL,
        "montant" numeric(20,2) NOT NULL,
        "taux_change_applique" numeric(10,6) NOT NULL DEFAULT 1,
        "mode" varchar(10) NOT NULL DEFAULT 'MNT',
        "statut" varchar(20) NOT NULL DEFAULT 'IMPORTE',
        "source" varchar(20) NOT NULL,
        "commentaire" text NULL,
        "valide_le" timestamp NULL,
        "fk_valide_par" bigint NULL,
        "date_creation" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "utilisateur_creation" varchar(255) NOT NULL DEFAULT 'system',
        "date_modification" timestamp NULL,
        "utilisateur_modification" varchar(255) NULL,
        CONSTRAINT "fk_fait_realise_cr"
          FOREIGN KEY ("fk_centre_responsabilite")
          REFERENCES "dim_centre_responsabilite"("id") ON DELETE RESTRICT,
        CONSTRAINT "fk_fait_realise_compte"
          FOREIGN KEY ("fk_compte")
          REFERENCES "dim_compte"("id") ON DELETE RESTRICT,
        CONSTRAINT "fk_fait_realise_ligne_metier"
          FOREIGN KEY ("fk_ligne_metier")
          REFERENCES "dim_ligne_metier"("id") ON DELETE RESTRICT,
        CONSTRAINT "fk_fait_realise_temps"
          FOREIGN KEY ("fk_temps")
          REFERENCES "dim_temps"("id") ON DELETE RESTRICT,
        CONSTRAINT "fk_fait_realise_devise"
          FOREIGN KEY ("fk_devise")
          REFERENCES "dim_devise"("id") ON DELETE RESTRICT,
        CONSTRAINT "fk_fait_realise_validateur"
          FOREIGN KEY ("fk_valide_par")
          REFERENCES "user"("id") ON DELETE SET NULL,
        CONSTRAINT "chk_fait_realise_statut"
          CHECK ("statut" IN ('IMPORTE','VALIDE')),
        CONSTRAINT "chk_fait_realise_source"
          CHECK ("source" IN ('IMPORT','SAISIE')),
        CONSTRAINT "chk_fait_realise_mode"
          CHECK ("mode" IN ('MNT','VOL','UNIT')),
        CONSTRAINT "chk_fait_realise_valide_coherence"
          CHECK (
            ("statut" = 'VALIDE'
              AND "valide_le" IS NOT NULL
              AND "fk_valide_par" IS NOT NULL)
            OR
            ("statut" = 'IMPORTE'
              AND "valide_le" IS NULL
              AND "fk_valide_par" IS NULL)
          )
      )
    `);

    // ─── 2. Index ──────────────────────────────────────────────────
    await q.query(`
      CREATE INDEX IF NOT EXISTS "idx_fait_realise_cr_temps"
        ON "fait_realise" ("fk_centre_responsabilite", "fk_temps")
    `);
    await q.query(`
      CREATE INDEX IF NOT EXISTS "idx_fait_realise_compte_temps"
        ON "fait_realise" ("fk_compte", "fk_temps")
    `);
    await q.query(`
      CREATE INDEX IF NOT EXISTS "idx_fait_realise_statut"
        ON "fait_realise" ("statut")
    `);
    await q.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "uq_fait_realise_dimensions"
        ON "fait_realise" (
          "fk_centre_responsabilite",
          "fk_compte",
          "fk_ligne_metier",
          "fk_temps",
          "fk_devise"
        )
    `);

    // ─── 3. Permissions REALISE.* ──────────────────────────────────
    await q.query(`
      INSERT INTO "ref_permission" ("code_permission","libelle","description","module","utilisateur_creation")
      VALUES
        ('REALISE.LIRE',
         'Consulter le réalisé',
         'Lire les lignes fait_realise et la grille de consultation. Pas de filtrage périmètre en lecture (cohérent avec décision Lot Administration ADMIN.D).',
         'REALISE','system (Lot 5.1)'),
        ('REALISE.SAISIR',
         'Saisir / modifier le réalisé',
         'Créer / modifier une ligne fait_realise en mode IMPORTE. Filtrage périmètre user_perimetres appliqué en écriture.',
         'REALISE','system (Lot 5.1)'),
        ('REALISE.IMPORTER',
         'Importer un fichier de réalisé',
         'Lancer un import Excel/CSV de réalisé (POST /realise/import). Filtrage périmètre appliqué pendant le traitement.',
         'REALISE','system (Lot 5.1)'),
        ('REALISE.VALIDER',
         'Valider une ligne réalisée',
         'Passer une ligne fait_realise du statut IMPORTE à VALIDE en lot. Pas de filtrage périmètre (validateur transverse).',
         'REALISE','system (Lot 5.1)'),
        ('REALISE.SUPPRIMER',
         'Supprimer une ligne réalisée',
         'Supprimer une ligne fait_realise (statut=IMPORTE uniquement). Filtrage périmètre appliqué.',
         'REALISE','system (Lot 5.1)')
      ON CONFLICT ("code_permission") DO NOTHING
    `);

    // ─── 4. Attribution permissions par rôle ──────────────────────
    const ATTRIBUTIONS: Array<[string, string]> = [
      // ADMIN : tout
      ['ADMIN', 'REALISE.LIRE'],
      ['ADMIN', 'REALISE.SAISIR'],
      ['ADMIN', 'REALISE.IMPORTER'],
      ['ADMIN', 'REALISE.VALIDER'],
      ['ADMIN', 'REALISE.SUPPRIMER'],
      // SAISISSEUR : lire + saisir + importer
      ['SAISISSEUR', 'REALISE.LIRE'],
      ['SAISISSEUR', 'REALISE.SAISIR'],
      ['SAISISSEUR', 'REALISE.IMPORTER'],
      // VALIDATEUR : lire + valider + supprimer
      ['VALIDATEUR', 'REALISE.LIRE'],
      ['VALIDATEUR', 'REALISE.VALIDER'],
      ['VALIDATEUR', 'REALISE.SUPPRIMER'],
      // PUBLICATEUR : lire seul
      ['PUBLICATEUR', 'REALISE.LIRE'],
      // AUDITEUR : lire seul
      ['AUDITEUR', 'REALISE.LIRE'],
      // LECTEUR : lire seul
      ['LECTEUR', 'REALISE.LIRE'],
    ];
    for (const [roleCode, permCode] of ATTRIBUTIONS) {
      const roleRows = (await q.query(
        `SELECT "id" FROM "ref_role" WHERE "code_role" = $1`,
        [roleCode],
      )) as Array<{ id: string }>;
      const permRows = (await q.query(
        `SELECT "id" FROM "ref_permission" WHERE "code_permission" = $1`,
        [permCode],
      )) as Array<{ id: string }>;
      if (roleRows.length === 0 || permRows.length === 0) continue;
      await q.query(
        `INSERT INTO "bridge_role_permission" ("fk_role","fk_permission")
         SELECT $1::bigint, $2::bigint
         WHERE NOT EXISTS (
           SELECT 1 FROM "bridge_role_permission"
            WHERE "fk_role" = $1::bigint AND "fk_permission" = $2::bigint
         )`,
        [roleRows[0]!.id, permRows[0]!.id],
      );
    }

    // ─── 5. Codes audit ───────────────────────────────────────────
    await q.query(`
      INSERT INTO "ref_type_action_audit"
        ("code","libelle","description","ordre","est_systeme","est_actif","utilisateur_creation")
      VALUES
        ('IMPORTER_REALISE',
         'Importer un fichier de réalisé',
         'Import Excel/CSV de lignes fait_realise (1 ligne audit par fichier). Lot 5.1.',
         130, true, true, 'system (Lot 5.1)'),
        ('SAISIR_REALISE',
         'Saisir / modifier une ligne réalisé',
         'Création ou modification (PATCH) d''une ligne fait_realise. Lot 5.1.',
         131, true, true, 'system (Lot 5.1)'),
        ('VALIDER_REALISE',
         'Valider une ligne réalisée',
         'Passage IMPORTE → VALIDE d''une ligne fait_realise (1 ligne audit par ligne validée). Lot 5.1.',
         132, true, true, 'system (Lot 5.1)'),
        ('SUPPRIMER_REALISE',
         'Supprimer une ligne réalisée',
         'Suppression hard d''une ligne fait_realise (statut=IMPORTE uniquement). Lot 5.1.',
         133, true, true, 'system (Lot 5.1)')
      ON CONFLICT ("code") DO NOTHING
    `);
  }

  public async down(q: QueryRunner): Promise<void> {
    await q.query(`
      DELETE FROM "ref_type_action_audit"
       WHERE "code" IN (
         'IMPORTER_REALISE','SAISIR_REALISE',
         'VALIDER_REALISE','SUPPRIMER_REALISE'
       )
    `);
    await q.query(`
      DELETE FROM "bridge_role_permission"
       WHERE "fk_permission" IN (
         SELECT "id" FROM "ref_permission" WHERE "module" = 'REALISE'
       )
    `);
    await q.query(`
      DELETE FROM "ref_permission" WHERE "module" = 'REALISE'
    `);
    await q.query(`DROP TABLE IF EXISTS "fait_realise"`);
  }
}
