import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Palier 1 — Gouvernance de la saisie du réalisé.
 *
 *  1. Table `parametre_systeme` (clé-valeur générique) + seed du
 *     paramètre `mode_saisie_realise = 'CENTRALISE'` (mode par défaut :
 *     seule la Direction Finance alimente le réalisé par import).
 *  2. Code audit `MODIFIER_PARAMETRE_SYSTEME` (ref_type_action_audit).
 *  3. Permission `REALISE.VALIDER` ajoutée au rôle COORDINATEUR
 *     (Ousmane auto-valide ses imports en mode centralisé).
 *  4. Permission `REALISE.SUPPRIMER` retirée du rôle VALIDATEUR
 *     (garde-fou : le validateur voit/valide mais ne supprime plus).
 *
 * Idempotente et réversible (down complet). CONFIGURATION.GERER (qui
 * garde l'écriture du toggle) existe déjà et est portée par ADMIN.
 */
export class CreerParametreSystemeEtModeRealise1779200000570 implements MigrationInterface {
  name = 'CreerParametreSystemeEtModeRealise1779200000570';

  public async up(q: QueryRunner): Promise<void> {
    // 1. Table parametre_systeme.
    await q.query(`
      CREATE TABLE IF NOT EXISTS "parametre_systeme" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "cle" varchar(100) NOT NULL,
        "valeur" text NOT NULL,
        "type" varchar(20) NOT NULL DEFAULT 'STRING',
        "description" text NULL,
        "date_creation" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "utilisateur_creation" varchar(255) NOT NULL DEFAULT 'system',
        "date_modification" timestamp NULL,
        "utilisateur_modification" varchar(255) NULL
      )
    `);
    await q.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "uq_parametre_systeme_cle"
        ON "parametre_systeme" ("cle")
    `);

    // Seed mode_saisie_realise = CENTRALISE (idempotent).
    await q.query(`
      INSERT INTO "parametre_systeme"
        ("cle", "valeur", "type", "description", "utilisateur_creation")
      VALUES
        ('mode_saisie_realise', 'CENTRALISE', 'ENUM',
         'Mode de saisie du réalisé : CENTRALISE (import Direction Finance seul), DECENTRALISE (saisie par CR), MIXTE.',
         'migration 570')
      ON CONFLICT ("cle") DO NOTHING
    `);

    // 2. Code audit.
    await q.query(`
      INSERT INTO "ref_type_action_audit"
        ("code","libelle","description","ordre","est_systeme","est_actif","utilisateur_creation")
      VALUES
        ('MODIFIER_PARAMETRE_SYSTEME',
         'Modifier un paramètre système',
         'Modification d''un paramètre global (ex. mode_saisie_realise) via PATCH /configuration. Permission CONFIGURATION.GERER.',
         620, true, true, 'migration 570')
      ON CONFLICT ("code") DO NOTHING
    `);

    // 3. REALISE.VALIDER → COORDINATEUR.
    await q.query(`
      INSERT INTO "bridge_role_permission" ("fk_role", "fk_permission")
      SELECT r."id", p."id"
      FROM "ref_role" r, "ref_permission" p
      WHERE r."code_role" = 'COORDINATEUR'
        AND p."code_permission" = 'REALISE.VALIDER'
      ON CONFLICT ("fk_role", "fk_permission") DO NOTHING
    `);

    // 4. REALISE.SUPPRIMER retirée de VALIDATEUR.
    await q.query(`
      DELETE FROM "bridge_role_permission"
      WHERE "fk_role" IN (SELECT id FROM "ref_role" WHERE code_role = 'VALIDATEUR')
        AND "fk_permission" IN (
          SELECT id FROM "ref_permission" WHERE code_permission = 'REALISE.SUPPRIMER'
        )
    `);
  }

  public async down(q: QueryRunner): Promise<void> {
    // 4 inverse : ré-attribue REALISE.SUPPRIMER à VALIDATEUR.
    await q.query(`
      INSERT INTO "bridge_role_permission" ("fk_role", "fk_permission")
      SELECT r."id", p."id"
      FROM "ref_role" r, "ref_permission" p
      WHERE r."code_role" = 'VALIDATEUR'
        AND p."code_permission" = 'REALISE.SUPPRIMER'
      ON CONFLICT ("fk_role", "fk_permission") DO NOTHING
    `);

    // 3 inverse : retire REALISE.VALIDER de COORDINATEUR.
    await q.query(`
      DELETE FROM "bridge_role_permission"
      WHERE "fk_role" IN (SELECT id FROM "ref_role" WHERE code_role = 'COORDINATEUR')
        AND "fk_permission" IN (
          SELECT id FROM "ref_permission" WHERE code_permission = 'REALISE.VALIDER'
        )
    `);

    // 2 inverse.
    await q.query(`
      DELETE FROM "ref_type_action_audit"
      WHERE "code" = 'MODIFIER_PARAMETRE_SYSTEME'
    `);

    // 1 inverse.
    await q.query(`DROP TABLE IF EXISTS "parametre_systeme"`);
  }
}
