import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Lot 4.3 — Notifications email.
 *
 * Crée :
 *  1. Table `email_log` qui trace chaque tentative d'envoi (réelle
 *     ou dry-run) avec statut, payload et nb de tentatives.
 *  2. 2 colonnes ajoutées sur `"user"` pour les préférences de
 *     notifications :
 *     - `notifications_email_actives` BOOLEAN DEFAULT true (toggle global)
 *     - `notifications_email_types` TEXT[] DEFAULT NULL (NULL = tous
 *       les types acceptés, sinon liste blanche stricte)
 *
 * Choix d'implémentation préférences (commenté dans le commit) :
 * 2 colonnes sur `"user"` plutôt qu'une table dédiée
 * `user_notifications_preferences` car (a) 1 user = 1 jeu de
 * préférences (pas de variantes contextuelles), (b) pas besoin
 * d'historisation des changements de préférences (l'audit est
 * déjà couvert par audit_log via @Auditable), (c) sur-architecture
 * pour 2 colonnes booléen + array. Si on doit ajouter d'autres
 * préférences UI plus tard (langue, thème, etc.), migration aisée
 * vers une table dédiée.
 *
 * Idempotence : CREATE TABLE/COLUMN IF NOT EXISTS partout, vérification
 * par information_schema pour les colonnes user.
 */
export class CreerEmailLogEtPreferencesNotifications1779200000130 implements MigrationInterface {
  name = 'CreerEmailLogEtPreferencesNotifications1779200000130';

  public async up(q: QueryRunner): Promise<void> {
    // ─── 1. Table email_log ────────────────────────────────────────
    await q.query(`
      CREATE TABLE IF NOT EXISTS "email_log" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "evenement" varchar(64) NOT NULL,
        "fk_destinataire" bigint NULL,
        "destinataire_email" varchar(255) NOT NULL,
        "sujet" text NOT NULL,
        "template" varchar(64) NOT NULL,
        "payload" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "statut" varchar(20) NOT NULL,
        "tentatives" int NOT NULL DEFAULT 0,
        "dernier_message_erreur" text NULL,
        "envoye_le" timestamp NULL,
        "date_creation" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "utilisateur_creation" varchar(255) NOT NULL DEFAULT 'system',
        "date_modification" timestamp NULL,
        "utilisateur_modification" varchar(255) NULL,
        CONSTRAINT "fk_email_log_destinataire"
          FOREIGN KEY ("fk_destinataire") REFERENCES "user"("id") ON DELETE SET NULL,
        CONSTRAINT "chk_email_log_statut"
          CHECK ("statut" IN ('EN_ATTENTE','ENVOYE','ECHEC','SUPPRIME'))
      )
    `);

    // ─── 2. Index ──────────────────────────────────────────────────
    await q.query(`
      CREATE INDEX IF NOT EXISTS "idx_email_log_statut"
        ON "email_log" ("statut")
    `);
    await q.query(`
      CREATE INDEX IF NOT EXISTS "idx_email_log_destinataire"
        ON "email_log" ("fk_destinataire", "date_creation" DESC)
    `);
    await q.query(`
      CREATE INDEX IF NOT EXISTS "idx_email_log_evenement"
        ON "email_log" ("evenement", "date_creation" DESC)
    `);

    // ─── 3. Préférences user (2 colonnes) ──────────────────────────
    // Vérification idempotente via information_schema. ON ne peut pas
    // utiliser ADD COLUMN IF NOT EXISTS sur tous les Postgres, donc
    // pattern conditionnel safe.
    const colActives = (await q.query(
      `SELECT 1 FROM information_schema.columns
        WHERE table_name = 'user'
          AND column_name = 'notifications_email_actives'`,
    )) as Array<unknown>;
    if (colActives.length === 0) {
      await q.query(
        `ALTER TABLE "user"
           ADD COLUMN "notifications_email_actives" boolean NOT NULL DEFAULT true`,
      );
    }
    const colTypes = (await q.query(
      `SELECT 1 FROM information_schema.columns
        WHERE table_name = 'user'
          AND column_name = 'notifications_email_types'`,
    )) as Array<unknown>;
    if (colTypes.length === 0) {
      await q.query(
        `ALTER TABLE "user"
           ADD COLUMN "notifications_email_types" text[] NULL`,
      );
    }
  }

  public async down(q: QueryRunner): Promise<void> {
    await q.query(
      `ALTER TABLE "user" DROP COLUMN IF EXISTS "notifications_email_types"`,
    );
    await q.query(
      `ALTER TABLE "user" DROP COLUMN IF EXISTS "notifications_email_actives"`,
    );
    await q.query(`DROP TABLE IF EXISTS "email_log"`);
  }
}
