/**
 * Helpers SQL pour les migrations SCD2.
 *
 * À utiliser dans les `up()` des migrations TypeORM des futurs `dim_*`
 * pour éviter la copie-colle du DDL des colonnes SCD2 + audit, et pour
 * appliquer systématiquement les ajustements manuels que TypeORM ne
 * sait pas générer (cf. docs/conventions.md §5.2).
 *
 * Usage type :
 * ```typescript
 * await queryRunner.query(`
 *   CREATE TABLE "dim_structure" (
 *     "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 *     "code_structure" varchar(50) NOT NULL,
 *     "libelle" varchar(150) NOT NULL,
 *     ${scd2Columns()},
 *     CONSTRAINT "PK_dim_structure" PRIMARY KEY ("id")
 *   )
 * `);
 * await queryRunner.query(enforceAlwaysIdentity('dim_structure'));
 * for (const sql of scd2Indexes('dim_structure', 'code_structure')) {
 *   await queryRunner.query(sql);
 * }
 * ```
 */

/**
 * Retourne le SQL des 8 colonnes SCD2 + audit, sans virgule de fin.
 * À insérer dans un `CREATE TABLE` après les colonnes métier.
 */
export function scd2Columns(): string {
  return `
    "date_debut_validite" date NOT NULL,
    "date_fin_validite" date,
    "version_courante" boolean NOT NULL DEFAULT true,
    "est_actif" boolean NOT NULL DEFAULT true,
    "date_creation" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "utilisateur_creation" varchar(255) NOT NULL DEFAULT 'system',
    "date_modification" timestamp,
    "utilisateur_modification" varchar(255)
  `.trim();
}

/**
 * Index standards sur une dimension SCD2 :
 *  - business key + version_courante (recherche du courant)
 *  - business key + date_debut_validite (jointure historisée par les faits)
 *  - index unique partiel garantissant 1 seule ligne courante par business key
 *
 * @param tableName     Nom de la table (ex. 'dim_structure')
 * @param businessKey   Nom de la colonne business key (ex. 'code_structure')
 */
export function scd2Indexes(tableName: string, businessKey: string): string[] {
  return [
    `CREATE INDEX "ix_${tableName}_business_key_courant" ON "${tableName}" ("${businessKey}", "version_courante")`,
    `CREATE INDEX "ix_${tableName}_business_key_debut" ON "${tableName}" ("${businessKey}", "date_debut_validite")`,
    `CREATE UNIQUE INDEX "uq_${tableName}_courante" ON "${tableName}" ("${businessKey}") WHERE "version_courante" = true`,
  ];
}

/**
 * Force la PK en `GENERATED ALWAYS AS IDENTITY` (TypeORM produit `BY DEFAULT`).
 * Cf. ADR #2 dans docs/architecture.md §12.
 */
export function enforceAlwaysIdentity(tableName: string): string {
  return `ALTER TABLE "${tableName}" ALTER COLUMN "id" SET GENERATED ALWAYS`;
}

/**
 * Drop des index SCD2 — à utiliser dans `down()` symétriquement.
 */
export function dropScd2Indexes(tableName: string): string[] {
  return [
    `DROP INDEX IF EXISTS "public"."uq_${tableName}_courante"`,
    `DROP INDEX IF EXISTS "public"."ix_${tableName}_business_key_debut"`,
    `DROP INDEX IF EXISTS "public"."ix_${tableName}_business_key_courant"`,
  ];
}
